/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-sysadmin-cm.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-sysadmin-cm.yang */
public class CiscoIOSXRSysadminCm extends ConfNamespace {
    public static final int hash = 832661383;
    public int hash() {
        return CiscoIOSXRSysadminCm.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-cm";
    public String id() {
        return CiscoIOSXRSysadminCm.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-cm";
    public String uri() {
        return CiscoIOSXRSysadminCm.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRSysadminCm.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-sysadmin-cm";
    public String prefix() {
        return CiscoIOSXRSysadminCm.prefix;
    }

    public CiscoIOSXRSysadminCm() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _sdr_id = 2051870111;
    public static final String _sdr_id_ = "sdr_id";
    public static final int    _l1_dis = 1698831041;
    public static final String _l1_dis_ = "l1_dis";
    public static final int    _nodei = 1884937908;
    public static final String _nodei_ = "nodei";
    public static final int    _system_service_inventory = 564395102;
    public static final String _system_service_inventory_ = "system-service-inventory";
    public static final int    _placement = 651606183;
    public static final String _placement_ = "placement";
    public static final int    _nbr_area_type = 404136725;
    public static final String _nbr_area_type_ = "nbr_area_type";
    public static final int    _ssvci = 829536748;
    public static final String _ssvci_ = "ssvci";
    public static final int    _sdr_version = 220125482;
    public static final String _sdr_version_ = "sdr_version";
    public static final int    _rack_number = 41234932;
    public static final String _rack_number_ = "rack_number";
    public static final int    _l2_dis = 2003336777;
    public static final String _l2_dis_ = "l2_dis";
    public static final int    _sdr_locations = 1970962355;
    public static final String _sdr_locations_ = "sdr_locations";
    public static final int    _lsp_id = 802628203;
    public static final String _lsp_id_ = "lsp_id";
    public static final int    _sdr_location = 1959267686;
    public static final String _sdr_location_ = "sdr_location";
    public static final int    _nbr_state = 1168454893;
    public static final String _nbr_state_ = "nbr_state";
    public static final int    _sw_state = 1404116129;
    public static final String _sw_state_ = "sw_state";
    public static final int    _rack_service_inventory = 743550486;
    public static final String _rack_service_inventory_ = "rack-service-inventory";
    public static final int    _rsvci = 1249406084;
    public static final String _rsvci_ = "rsvci";
    public static final int    _mac_address = 1511184968;
    public static final String _mac_address_ = "mac_address";
    public static final int    _card_type = 1609141393;
    public static final String _card_type_ = "card_type";
    public static final int    _topology_neighbors = 1333448463;
    public static final String _topology_neighbors_ = "topology-neighbors";
    public static final int    _nbr_location = 2059864693;
    public static final String _nbr_location_ = "nbr_location";
    public static final int    _rack_location = 1476937337;
    public static final String _rack_location_ = "rack_location";
    public static final int    _bkup_syslead = 453422888;
    public static final String _bkup_syslead_ = "bkup_syslead";
    public static final int    _sdr_inventory = 1475557249;
    public static final String _sdr_inventory_ = "sdr-inventory";
    public static final int    _rack_locations = 1676002780;
    public static final String _rack_locations_ = "rack_locations";
    public static final int    _lsp_sequence = 713211173;
    public static final String _lsp_sequence_ = "lsp_sequence";
    public static final int    _racklead = 251137118;
    public static final String _racklead_ = "racklead";
    public static final int    _sdr_vlan_baseid = 1933684877;
    public static final String _sdr_vlan_baseid_ = "sdr_vlan_baseid";
    public static final int    _sdr = 302613920;
    public static final String _sdr_ = "sdr";
    public static final int    _nodeid_first = 558967511;
    public static final String _nodeid_first_ = "nodeid_first";
    public static final int    _cardi = 1119622012;
    public static final String _cardi_ = "cardi";
    public static final int    _card_serial = 1294262923;
    public static final String _card_serial_ = "card_serial";
    public static final int    _lspdb_location = 2081516011;
    public static final String _lspdb_location_ = "lspdb_location";
    public static final int    _bkup_racklead = 1401995739;
    public static final String _bkup_racklead_ = "bkup_racklead";
    public static final int    _slot = 1340146283;
    public static final String _slot_ = "slot";
    public static final int    _node_inventory = 788976373;
    public static final String _node_inventory_ = "node-inventory";
    public static final int    _placement_first = 545365394;
    public static final String _placement_first_ = "placement_first";
    public static final int    _nbr_locations = 47835841;
    public static final String _nbr_locations_ = "nbr_locations";
    public static final int    _syslead = 780704672;
    public static final String _syslead_ = "syslead";
    public static final int    _detail = 984599342;
    public static final String _detail_ = "detail";
    public static final int    _card_location = 1005161714;
    public static final String _card_location_ = "card_location";
    public static final int    _ip_address = 358839875;
    public static final String _ip_address_ = "ip_address";
    public static final int    _node_id = 1569894691;
    public static final String _node_id_ = "node_id";
    public static final int    _racki = 245713850;
    public static final String _racki_ = "racki";
    public static final int    _nbr_system_id = 1495497709;
    public static final String _nbr_system_id_ = "nbr_system_id";
    public static final int    _sdr_name = 1923963030;
    public static final String _sdr_name_ = "sdr_name";
    public static final int    _lsp_area_type = 473378291;
    public static final String _lsp_area_type_ = "lsp_area_type";
    public static final int    _nbri = 1083399951;
    public static final String _nbri_ = "nbri";
    public static final int    _sdri = 1905282698;
    public static final String _sdri_ = "sdri";
    public static final int    _placement_second = 586860924;
    public static final String _placement_second_ = "placement_second";
    public static final int    _rack_state = 702224211;
    public static final String _rack_state_ = "rack_state";
    public static final int    _nti = 1990892474;
    public static final String _nti_ = "nti";
    public static final int    _nodeid_second = 1964600793;
    public static final String _nodeid_second_ = "nodeid_second";
    public static final int    _rsvc_locations = 993275473;
    public static final String _rsvc_locations_ = "rsvc_locations";
    public static final int    _lsp_core = 250950528;
    public static final String _lsp_core_ = "lsp_core";
    public static final int    _data = 535242711;
    public static final String _data_ = "data";
    public static final int    _lspdbi = 1812458943;
    public static final String _lspdbi_ = "lspdbi";
    public static final int    _ldr_locations = 1276302389;
    public static final String _ldr_locations_ = "ldr_locations";
    public static final int    _lsp_tlvs = 1360658753;
    public static final String _lsp_tlvs_ = "lsp_tlvs";
    public static final int    _ldr_location = 1615771908;
    public static final String _ldr_location_ = "ldr_location";
    public static final int    _summary = 738895761;
    public static final String _summary_ = "summary";
    public static final int    _node_locations = 392062;
    public static final String _node_locations_ = "node_locations";
    public static final int    _leader_statistics = 1484989782;
    public static final String _leader_statistics_ = "leader-statistics";
    public static final int    _restart = 864065282;
    public static final String _restart_ = "restart";
    public static final int    _lsp = 2093596695;
    public static final String _lsp_ = "lsp";
    public static final int    _svc_load = 774418406;
    public static final String _svc_load_ = "svc_load";
    public static final int    _cti = 666736513;
    public static final String _cti_ = "cti";
    public static final int    _nbr_interface = 285819563;
    public static final String _nbr_interface_ = "nbr_interface";
    public static final int    _hw_state = 1914916865;
    public static final String _hw_state_ = "hw_state";
    public static final int    _svc_name = 243552246;
    public static final String _svc_name_ = "svc_name";
    public static final int    _node_location = 1202184073;
    public static final String _node_location_ = "node_location";
    public static final int    _ssvc_location = 1892473695;
    public static final String _ssvc_location_ = "ssvc_location";
    public static final int    _rack_inventory = 1995804850;
    public static final String _rack_inventory_ = "rack-inventory";
    public static final int    _nbr_uptime = 1996190823;
    public static final String _nbr_uptime_ = "nbr_uptime";
    public static final int    _rsvc_location = 674081369;
    public static final String _rsvc_location_ = "rsvc_location";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _reoptimize = 1477838371;
    public static final String _reoptimize_ = "reoptimize";
    public static final int    _nbr_holdtime = 1088973001;
    public static final String _nbr_holdtime_ = "nbr_holdtime";
    public static final int    _lspdb_locations = 1943507329;
    public static final String _lspdb_locations_ = "lspdb_locations";
    public static final int    _card_locations = 878906061;
    public static final String _card_locations_ = "card_locations";
    public static final int    _card_inventory = 1228209061;
    public static final String _card_inventory_ = "card-inventory";
    public static final int    _rack_serial = 2009725075;
    public static final String _rack_serial_ = "rack_serial";
    public static final int    _ssvc_locations = 689352161;
    public static final String _ssvc_locations_ = "ssvc_locations";
}
