/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-hwmod-mpa-reload-act.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-hwmod-mpa-reload-act.yang */
public class CiscoIOSXRHwmodMpaReloadAct extends ConfNamespace {
    public static final int hash = 1807569;
    public int hash() {
        return CiscoIOSXRHwmodMpaReloadAct.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-hwmod-mpa-reload-act";
    public String id() {
        return CiscoIOSXRHwmodMpaReloadAct.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-hwmod-mpa-reload-act";
    public String uri() {
        return CiscoIOSXRHwmodMpaReloadAct.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRHwmodMpaReloadAct.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-hwmod-mpa-reload-act";
    public String prefix() {
        return CiscoIOSXRHwmodMpaReloadAct.prefix;
    }

    public CiscoIOSXRHwmodMpaReloadAct() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _rpc_hw_module_subslot = 2011910304;
    public static final String _rpc_hw_module_subslot_ = "rpc-hw-module-subslot";
    public static final int    _hw_module_subslot = 1592421128;
    public static final String _hw_module_subslot_ = "hw-module-subslot";
    public static final int    _reload = 1336127569;
    public static final String _reload_ = "reload";
    public static final int    _subslot = 1668055854;
    public static final String _subslot_ = "subslot";
}
