/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-drivers-mpa-infra-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-drivers-mpa-infra-cfg.yang */
public class CiscoIOSXRDriversMpaInfraCfg extends ConfNamespace {
    public static final int hash = 2038584686;
    public int hash() {
        return CiscoIOSXRDriversMpaInfraCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-drivers-mpa-infra-cfg";
    public String id() {
        return CiscoIOSXRDriversMpaInfraCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-drivers-mpa-infra-cfg";
    public String uri() {
        return CiscoIOSXRDriversMpaInfraCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRDriversMpaInfraCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-drivers-mpa-infra-cfg";
    public String prefix() {
        return CiscoIOSXRDriversMpaInfraCfg.prefix;
    }

    public CiscoIOSXRDriversMpaInfraCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _hardware_module = 194943774;
    public static final String _hardware_module_ = "hardware-module";
    public static final int    _shutdown = 460723287;
    public static final String _shutdown_ = "shutdown";
    public static final int    _nodes = 650955465;
    public static final String _nodes_ = "nodes";
    public static final int    _node_name = 122353445;
    public static final String _node_name_ = "node-name";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
}
