/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-es-acl-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-es-acl-cfg.yang */
public class CiscoIOSXREsAclCfg extends ConfNamespace {
    public static final int hash = 1031481275;
    public int hash() {
        return CiscoIOSXREsAclCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-es-acl-cfg";
    public String id() {
        return CiscoIOSXREsAclCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-es-acl-cfg";
    public String uri() {
        return CiscoIOSXREsAclCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXREsAclCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-es-acl-cfg";
    public String prefix() {
        return CiscoIOSXREsAclCfg.prefix;
    }

    public CiscoIOSXREsAclCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _sequence_str = 104619270;
    public static final String _sequence_str_ = "sequence-str";
    public static final int    _inner_vlan2 = 2034379403;
    public static final String _inner_vlan2_ = "inner-vlan2";
    public static final int    _grant = 2112160108;
    public static final String _grant_ = "grant";
    public static final int    _ether_type_number = 965227538;
    public static final String _ether_type_number_ = "ether-type-number";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _inner_cos = 1292350954;
    public static final String _inner_cos_ = "inner-cos";
    public static final int    _access_list_entry = 804152639;
    public static final String _access_list_entry_ = "access-list-entry";
    public static final int    _es_acl = 1834267713;
    public static final String _es_acl_ = "es-acl";
    public static final int    _source_address = 554848846;
    public static final String _source_address_ = "source-address";
    public static final int    _inner_vlan1 = 1221403367;
    public static final String _inner_vlan1_ = "inner-vlan1";
    public static final int    _inner_dei = 579685107;
    public static final String _inner_dei_ = "inner-dei";
    public static final int    _destination_address = 1799113401;
    public static final String _destination_address_ = "destination-address";
    public static final int    _destination_wild_card_bits = 1302792712;
    public static final String _destination_wild_card_bits_ = "destination-wild-card-bits";
    public static final int    _dei = 1423139725;
    public static final String _dei_ = "dei";
    public static final int    _log_option = 818026233;
    public static final String _log_option_ = "log-option";
    public static final int    _sequence_number = 996433488;
    public static final String _sequence_number_ = "sequence-number";
    public static final int    _cos = 762246620;
    public static final String _cos_ = "cos";
    public static final int    _capture = 731380543;
    public static final String _capture_ = "capture";
    public static final int    _access = 304644663;
    public static final String _access_ = "access";
    public static final int    _destination_network = 139859025;
    public static final String _destination_network_ = "destination-network";
    public static final int    _vlan1 = 617877509;
    public static final String _vlan1_ = "vlan1";
    public static final int    _remark = 1708461866;
    public static final String _remark_ = "remark";
    public static final int    _accesses = 1456747142;
    public static final String _accesses_ = "accesses";
    public static final int    _access_list_entries = 825024675;
    public static final String _access_list_entries_ = "access-list-entries";
    public static final int    _source_wild_card_bits = 1659415782;
    public static final String _source_wild_card_bits_ = "source-wild-card-bits";
    public static final int    _source_network = 1816407268;
    public static final String _source_network_ = "source-network";
    public static final int    _vlan2 = 1606336217;
    public static final String _vlan2_ = "vlan2";
}
