/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-mdrv-lib-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-mdrv-lib-cfg.yang */
public class CiscoIOSXRMdrvLibCfg extends ConfNamespace {
    public static final int hash = 2033843658;
    public int hash() {
        return CiscoIOSXRMdrvLibCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mdrv-lib-cfg";
    public String id() {
        return CiscoIOSXRMdrvLibCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mdrv-lib-cfg";
    public String uri() {
        return CiscoIOSXRMdrvLibCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRMdrvLibCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-mdrv-lib-cfg";
    public String prefix() {
        return CiscoIOSXRMdrvLibCfg.prefix;
    }

    public CiscoIOSXRMdrvLibCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ethernet = 766975154;
    public static final String _ethernet_ = "ethernet";
    public static final int    _mac_addr = 153686390;
    public static final String _mac_addr_ = "mac-addr";
    public static final int    _fast_shutdown = 484124650;
    public static final String _fast_shutdown_ = "fast-shutdown";
}
