/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-man-xml-ttyagent-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-man-xml-ttyagent-cfg.yang */
public class CiscoIOSXRManXmlTtyagentCfg extends ConfNamespace {
    public static final int hash = 408895810;
    public int hash() {
        return CiscoIOSXRManXmlTtyagentCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-man-xml-ttyagent-cfg";
    public String id() {
        return CiscoIOSXRManXmlTtyagentCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-man-xml-ttyagent-cfg";
    public String uri() {
        return CiscoIOSXRManXmlTtyagentCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRManXmlTtyagentCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-man-xml-ttyagent-cfg";
    public String prefix() {
        return CiscoIOSXRManXmlTtyagentCfg.prefix;
    }

    public CiscoIOSXRManXmlTtyagentCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _throttle = 714657076;
    public static final String _throttle_ = "throttle";
    public static final int    _process_rate = 591638559;
    public static final String _process_rate_ = "process-rate";
    public static final int    _access_list = 1900334689;
    public static final String _access_list_ = "access-list";
    public static final int    _ipv6_enable = 2112559417;
    public static final String _ipv6_enable_ = "ipv6-enable";
    public static final int    _vrf = 1281310328;
    public static final String _vrf_ = "vrf";
    public static final int    _enable = 448570367;
    public static final String _enable_ = "enable";
    public static final int    _shutdown = 460723287;
    public static final String _shutdown_ = "shutdown";
    public static final int    _default = 515137925;
    public static final String _default_ = "default";
    public static final int    _agent = 15006109;
    public static final String _agent_ = "agent";
    public static final int    _session = 1896174846;
    public static final String _session_ = "session";
    public static final int    _ipv4_disable = 714226641;
    public static final String _ipv4_disable_ = "ipv4-disable";
    public static final int    _vrf_name = 2140916904;
    public static final String _vrf_name_ = "vrf-name";
    public static final int    _streaming_size = 2006604220;
    public static final String _streaming_size_ = "streaming-size";
    public static final int    _iteration_size = 631579747;
    public static final String _iteration_size_ = "iteration-size";
    public static final int    _ipv4_access_list = 30161481;
    public static final String _ipv4_access_list_ = "ipv4-access-list";
    public static final int    _ipv6_access_list = 656457521;
    public static final String _ipv6_access_list_ = "ipv6-access-list";
    public static final int    _timeout = 614210192;
    public static final String _timeout_ = "timeout";
    public static final int    _ssl = 979553486;
    public static final String _ssl_ = "ssl";
    public static final int    _tty = 2034439888;
    public static final String _tty_ = "tty";
    public static final int    _memory = 1156186237;
    public static final String _memory_ = "memory";
    public static final int    _xr_xml = 871356897;
    public static final String _xr_xml_ = "xr-xml";
    public static final int    _netconf = 1625535416;
    public static final String _netconf_ = "netconf";
    public static final int    _vrfs = 777611836;
    public static final String _vrfs_ = "vrfs";
    public static final int    _offload_memory = 1741681837;
    public static final String _offload_memory_ = "offload-memory";
}
