/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-infra-alarm-logger-datatypes.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-infra-alarm-logger-datatypes.yang */
public class CiscoIOSXRInfraAlarmLoggerDatatypes extends ConfNamespace {
    public static final int hash = 35357066;
    public int hash() {
        return CiscoIOSXRInfraAlarmLoggerDatatypes.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-alarm-logger-datatypes";
    public String id() {
        return CiscoIOSXRInfraAlarmLoggerDatatypes.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-alarm-logger-datatypes";
    public String uri() {
        return CiscoIOSXRInfraAlarmLoggerDatatypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRInfraAlarmLoggerDatatypes.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-infra-alarm-logger-datatypes";
    public String prefix() {
        return CiscoIOSXRInfraAlarmLoggerDatatypes.prefix;
    }

    public CiscoIOSXRInfraAlarmLoggerDatatypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
