/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-telemetry-model-driven-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-telemetry-model-driven-oper.yang */
public class CiscoIOSXRTelemetryModelDrivenOper extends ConfNamespace {
    public static final int hash = 1377600136;
    public int hash() {
        return CiscoIOSXRTelemetryModelDrivenOper.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-telemetry-model-driven-oper";
    public String id() {
        return CiscoIOSXRTelemetryModelDrivenOper.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-telemetry-model-driven-oper";
    public String uri() {
        return CiscoIOSXRTelemetryModelDrivenOper.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRTelemetryModelDrivenOper.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-telemetry-model-driven-oper";
    public String prefix() {
        return CiscoIOSXRTelemetryModelDrivenOper.prefix;
    }

    public CiscoIOSXRTelemetryModelDrivenOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _subscription = 982993959;
    public static final String _subscription_ = "subscription";
    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _total_get_errors = 757372005;
    public static final String _total_get_errors_ = "total-get-errors";
    public static final int    _vrf_id = 2037305089;
    public static final String _vrf_id_ = "vrf-id";
    public static final int    _collection_path = 1062877992;
    public static final String _collection_path_ = "collection-path";
    public static final int    _num_of_active_subscriptions = 1144533490;
    public static final String _num_of_active_subscriptions_ = "num-of-active-subscriptions";
    public static final int    _total_num_of_bytes_sent = 975537319;
    public static final String _total_num_of_bytes_sent_ = "total-num-of-bytes-sent";
    public static final int    _max_collection_time = 1865967517;
    public static final String _max_collection_time_ = "max-collection-time";
    public static final int    _total_not_ready = 284743195;
    public static final String _total_not_ready_ = "total-not-ready";
    public static final int    _total_encode_notready = 618668140;
    public static final String _total_encode_notready_ = "total-encode-notready";
    public static final int    _last_collection_start_time = 647066798;
    public static final String _last_collection_start_time_ = "last-collection-start-time";
    public static final int    _total_collections_missed = 1120837067;
    public static final String _total_collections_missed_ = "total-collections-missed";
    public static final int    _total_datalist_count = 358328223;
    public static final String _total_datalist_count_ = "total-datalist-count";
    public static final int    _source_qos_marking = 1759577328;
    public static final String _source_qos_marking_ = "source-qos-marking";
    public static final int    _total_num_of_packets_sent = 1530579910;
    public static final String _total_num_of_packets_sent_ = "total-num-of-packets-sent";
    public static final int    _ipv6_address = 731894850;
    public static final String _ipv6_address_ = "ipv6-address";
    public static final int    _num_of_connecting_sessions = 311155647;
    public static final String _num_of_connecting_sessions_ = "num-of-connecting-sessions";
    public static final int    _sensor_path = 424127023;
    public static final String _sensor_path_ = "sensor-path";
    public static final int    _internal_collection_group = 1180702643;
    public static final String _internal_collection_group_ = "internal-collection-group";
    public static final int    _avg_collection_time = 471419262;
    public static final String _avg_collection_time_ = "avg-collection-time";
    public static final int    _subscription_id = 1687818382;
    public static final String _subscription_id_ = "subscription-id";
    public static final int    _max_sensor_paths = 413346479;
    public static final String _max_sensor_paths_ = "max-sensor-paths";
    public static final int    _total_finddata_errors = 1188794023;
    public static final String _total_finddata_errors_ = "total-finddata-errors";
    public static final int    _last_collection_end_time = 1205005390;
    public static final String _last_collection_end_time_ = "last-collection-end-time";
    public static final int    _strict_timer = 845682667;
    public static final String _strict_timer_ = "strict-timer";
    public static final int    _destination_id = 2142582101;
    public static final String _destination_id_ = "destination-id";
    public static final int    _sample_interval = 1730479987;
    public static final String _sample_interval_ = "sample-interval";
    public static final int    _ipv4_address = 400734928;
    public static final String _ipv4_address_ = "ipv4-address";
    public static final int    _sensor_profile = 1970107157;
    public static final String _sensor_profile_ = "sensor-profile";
    public static final int    _num_of_dialins = 1553053857;
    public static final String _num_of_dialins_ = "num-of-dialins";
    public static final int    _encoding = 180862443;
    public static final String _encoding_ = "encoding";
    public static final int    _vrf = 1281310328;
    public static final String _vrf_ = "vrf";
    public static final int    _num_of_unique_sensor_paths = 1793008602;
    public static final String _num_of_unique_sensor_paths_ = "num-of-unique-sensor-paths";
    public static final int    _max_containers_per_path = 1497155084;
    public static final String _max_containers_per_path_ = "max-containers-per-path";
    public static final int    _total_list_count = 1771486806;
    public static final String _total_list_count_ = "total-list-count";
    public static final int    _last_collection_time = 1046807166;
    public static final String _last_collection_time_ = "last-collection-time";
    public static final int    _total_send_drops = 314169791;
    public static final String _total_send_drops_ = "total-send-drops";
    public static final int    _num_of_grpc_tls_dialouts = 1570591583;
    public static final String _num_of_grpc_tls_dialouts_ = "num-of-grpc-tls-dialouts";
    public static final int    _collection_group = 1493042832;
    public static final String _collection_group_ = "collection-group";
    public static final int    _num_of_connected_sessions = 123168814;
    public static final String _num_of_connected_sessions_ = "num-of-connected-sessions";
    public static final int    _total_item_count = 2011605751;
    public static final String _total_item_count_ = "total-item-count";
    public static final int    _num_of_destination_groups = 498471521;
    public static final String _num_of_destination_groups_ = "num-of-destination-groups";
    public static final int    _cadence = 1655887379;
    public static final String _cadence_ = "cadence";
    public static final int    _interface_name = 1322899300;
    public static final String _interface_name_ = "interface-name";
    public static final int    _sub_id_str = 2124952770;
    public static final String _sub_id_str_ = "sub-id-str";
    public static final int    _total_finddata_count = 473358934;
    public static final String _total_finddata_count_ = "total-finddata-count";
    public static final int    _destinations = 1001041063;
    public static final String _destinations_ = "destinations";
    public static final int    _transport = 514190987;
    public static final String _transport_ = "transport";
    public static final int    _configured = 727385972;
    public static final String _configured_ = "configured";
    public static final int    _collection_method = 1548149582;
    public static final String _collection_method_ = "collection-method";
    public static final int    _sub_id = 697678039;
    public static final String _sub_id_ = "sub-id";
    public static final int    _min_collection_time = 1270899777;
    public static final String _min_collection_time_ = "min-collection-time";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _total_sent_bytes = 1484399278;
    public static final String _total_sent_bytes_ = "total-sent-bytes";
    public static final int    _num_of_udp_dialouts = 833991249;
    public static final String _num_of_udp_dialouts_ = "num-of-udp-dialouts";
    public static final int    _num_of_active_sensor_paths = 1045726652;
    public static final String _num_of_active_sensor_paths_ = "num-of-active-sensor-paths";
    public static final int    _max_total_time = 1695358362;
    public static final String _max_total_time_ = "max-total-time";
    public static final int    _destination = 1426812369;
    public static final String _destination_ = "destination";
    public static final int    _num_of_active_destinations = 1616833948;
    public static final String _num_of_active_destinations_ = "num-of-active-destinations";
    public static final int    _total_send_packets = 1689794858;
    public static final String _total_send_packets_ = "total-send-packets";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _total_on_data_instances = 894204578;
    public static final String _total_on_data_instances_ = "total-on-data-instances";
    public static final int    _total_other_errors = 232216291;
    public static final String _total_other_errors_ = "total-other-errors";
    public static final int    _num_of_paused_subscriptions = 134248536;
    public static final String _num_of_paused_subscriptions_ = "num-of-paused-subscriptions";
    public static final int    _total_get_count = 2005615482;
    public static final String _total_get_count_ = "total-get-count";
    public static final int    _total_send_errors = 1306733446;
    public static final String _total_send_errors_ = "total-send-errors";
    public static final int    _udp_mtu = 363746033;
    public static final String _udp_mtu_ = "udp-mtu";
    public static final int    _status_str = 1183617012;
    public static final String _status_str_ = "status-str";
    public static final int    _heartbeat_interval = 1281304246;
    public static final String _heartbeat_interval_ = "heartbeat-interval";
    public static final int    _total_collections = 928821088;
    public static final String _total_collections_ = "total-collections";
    public static final int    _total_datalist_errors = 1140804515;
    public static final String _total_datalist_errors_ = "total-datalist-errors";
    public static final int    _num_of_sensor_paths = 47345630;
    public static final String _num_of_sensor_paths_ = "num-of-sensor-paths";
    public static final int    _num_of_sensor_groups = 1678886558;
    public static final String _num_of_sensor_groups_ = "num-of-sensor-groups";
    public static final int    _dest_port = 1457745272;
    public static final String _dest_port_ = "dest-port";
    public static final int    _dscp = 1118112132;
    public static final String _dscp_ = "dscp";
    public static final int    _avg_total_time = 1852203551;
    public static final String _avg_total_time_ = "avg-total-time";
    public static final int    _total_send_bytes_dropped = 1168555143;
    public static final String _total_send_bytes_dropped_ = "total-send-bytes-dropped";
    public static final int    _ip_type = 511249701;
    public static final String _ip_type_ = "ip-type";
    public static final int    _summary = 738895761;
    public static final String _summary_ = "summary";
    public static final int    _tls_host = 1786649981;
    public static final String _tls_host_ = "tls-host";
    public static final int    _total_get_bulk_count = 1987730682;
    public static final String _total_get_bulk_count_ = "total-get-bulk-count";
    public static final int    _suppress_redundant = 1367205526;
    public static final String _suppress_redundant_ = "suppress-redundant";
    public static final int    _num_of_grpc_non_tls_dialouts = 2121005866;
    public static final String _num_of_grpc_non_tls_dialouts_ = "num-of-grpc-non-tls-dialouts";
    public static final int    _sensor_group = 521692491;
    public static final String _sensor_group_ = "sensor-group";
    public static final int    _destination_grp = 186657202;
    public static final String _destination_grp_ = "destination-grp";
    public static final int    _sensor_groups = 1378032050;
    public static final String _sensor_groups_ = "sensor-groups";
    public static final int    _num_of_not_resolved_sensor_paths = 989773896;
    public static final String _num_of_not_resolved_sensor_paths_ = "num-of-not-resolved-sensor-paths";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _dest_ip_address = 1038854502;
    public static final String _dest_ip_address_ = "dest-ip-address";
    public static final int    _total_encode_errors = 840654130;
    public static final String _total_encode_errors_ = "total-encode-errors";
    public static final int    _num_of_subscriptions = 1835982553;
    public static final String _num_of_subscriptions_ = "num-of-subscriptions";
    public static final int    _num_of_destinations = 446596962;
    public static final String _num_of_destinations_ = "num-of-destinations";
    public static final int    _num_of_tcp_dialouts = 1296489226;
    public static final String _num_of_tcp_dialouts_ = "num-of-tcp-dialouts";
    public static final int    _tls = 1160896511;
    public static final String _tls_ = "tls";
    public static final int    _total_list_errors = 23096151;
    public static final String _total_list_errors_ = "total-list-errors";
    public static final int    _total_get_bulk_errors = 1828481952;
    public static final String _total_get_bulk_errors_ = "total-get-bulk-errors";
    public static final int    _sensor_group_id = 1378386708;
    public static final String _sensor_group_id_ = "sensor-group-id";
    public static final int    _min_total_time = 52395929;
    public static final String _min_total_time_ = "min-total-time";
    public static final int    _source_interface = 1180772123;
    public static final String _source_interface_ = "source-interface";
    public static final int    _subscriptions = 886823438;
    public static final String _subscriptions_ = "subscriptions";
    public static final int    _telemetry_model_driven = 362813461;
    public static final String _telemetry_model_driven_ = "telemetry-model-driven";
}
