/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-ipv6-smiap-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-ipv6-smiap-cfg.yang */
public class CiscoIOSXRIpv6SmiapCfg extends ConfNamespace {
    public static final int hash = 627652407;
    public int hash() {
        return CiscoIOSXRIpv6SmiapCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv6-smiap-cfg";
    public String id() {
        return CiscoIOSXRIpv6SmiapCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv6-smiap-cfg";
    public String uri() {
        return CiscoIOSXRIpv6SmiapCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRIpv6SmiapCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-ipv6-smiap-cfg";
    public String prefix() {
        return CiscoIOSXRIpv6SmiapCfg.prefix;
    }

    public CiscoIOSXRIpv6SmiapCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ipv6_virtual = 1264382204;
    public static final String _ipv6_virtual_ = "ipv6-virtual";
    public static final int    _vrf = 1281310328;
    public static final String _vrf_ = "vrf";
    public static final int    _use_as_source_address = 1352972109;
    public static final String _use_as_source_address_ = "use-as-source-address";
    public static final int    _vrf_name = 2140916904;
    public static final String _vrf_name_ = "vrf-name";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _vrfs = 777611836;
    public static final String _vrfs_ = "vrfs";
    public static final int    _prefix_length = 524393771;
    public static final String _prefix_length_ = "prefix-length";
}
