/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-ipv4-acl-datatypes.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-ipv4-acl-datatypes.yang */
public class CiscoIOSXRIpv4AclDatatypes extends ConfNamespace {
    public static final int hash = 982452883;
    public int hash() {
        return CiscoIOSXRIpv4AclDatatypes.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-acl-datatypes";
    public String id() {
        return CiscoIOSXRIpv4AclDatatypes.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-acl-datatypes";
    public String uri() {
        return CiscoIOSXRIpv4AclDatatypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRIpv4AclDatatypes.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-ipv4-acl-datatypes";
    public String prefix() {
        return CiscoIOSXRIpv4AclDatatypes.prefix;
    }

    public CiscoIOSXRIpv4AclDatatypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    __bm_Ipv4_acl_tcp_bits_number_urg = 32;
    public static final String __bm_Ipv4_acl_tcp_bits_number_urg_ = "urg";
    public static final int    __bm_Ipv4_acl_tcp_bits_number_ack = 16;
    public static final String __bm_Ipv4_acl_tcp_bits_number_ack_ = "ack";
    public static final int    __bm_Ipv4_acl_tcp_bits_number_syn = 2;
    public static final String __bm_Ipv4_acl_tcp_bits_number_syn_ = "syn";
    public static final int    __bm_Ipv4_acl_tcp_bits_number_fin = 1;
    public static final String __bm_Ipv4_acl_tcp_bits_number_fin_ = "fin";
    public static final int    __bm_Ipv4_acl_tcp_bits_number_rst = 4;
    public static final String __bm_Ipv4_acl_tcp_bits_number_rst_ = "rst";
    public static final int    __bm_Ipv4_acl_tcp_bits_number_psh = 8;
    public static final String __bm_Ipv4_acl_tcp_bits_number_psh_ = "psh";
}
