/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-cfgmgr-rollback-act.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-cfgmgr-rollback-act.yang */
public class CiscoIOSXRCfgmgrRollbackAct extends ConfNamespace {
    public static final int hash = 454061033;
    public int hash() {
        return CiscoIOSXRCfgmgrRollbackAct.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-cfgmgr-rollback-act";
    public String id() {
        return CiscoIOSXRCfgmgrRollbackAct.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-cfgmgr-rollback-act";
    public String uri() {
        return CiscoIOSXRCfgmgrRollbackAct.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRCfgmgrRollbackAct.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-cfgmgr-rollback-act";
    public String prefix() {
        return CiscoIOSXRCfgmgrRollbackAct.prefix;
    }

    public CiscoIOSXRCfgmgrRollbackAct() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _roll_back_configuration = 1857334945;
    public static final String _roll_back_configuration_ = "roll-back-configuration";
    public static final int    _roll_back_configuration_last = 931872933;
    public static final String _roll_back_configuration_last_ = "roll-back-configuration-last";
    public static final int    _comment = 452863039;
    public static final String _comment_ = "comment";
    public static final int    _best_effort = 1556684121;
    public static final String _best_effort_ = "best-effort";
    public static final int    _roll_back_configuration_to = 1892435338;
    public static final String _roll_back_configuration_to_ = "roll-back-configuration-to";
    public static final int    _count = 180894398;
    public static final String _count_ = "count";
    public static final int    _rpc_roll_back_configuration_last = 648529142;
    public static final String _rpc_roll_back_configuration_last_ = "rpc-roll-back-configuration-last";
    public static final int    _rpc_roll_back_configuration = 2033886143;
    public static final String _rpc_roll_back_configuration_ = "rpc-roll-back-configuration";
    public static final int    _label = 1570796500;
    public static final String _label_ = "label";
    public static final int    _force = 1475309827;
    public static final String _force_ = "force";
    public static final int    _rpc_roll_back_configuration_to_exclude = 127897281;
    public static final String _rpc_roll_back_configuration_to_exclude_ = "rpc-roll-back-configuration-to-exclude";
    public static final int    _rpc_roll_back_configuration_to = 119117724;
    public static final String _rpc_roll_back_configuration_to_ = "rpc-roll-back-configuration-to";
    public static final int    _roll_back_configuration_to_exclude = 786585898;
    public static final String _roll_back_configuration_to_exclude_ = "roll-back-configuration-to-exclude";
    public static final int    _commit_id = 738560138;
    public static final String _commit_id_ = "commit-id";
}
