/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-ipv4-bgp-oc-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-ipv4-bgp-oc-oper.yang */
public class CiscoIOSXRIpv4BgpOcOper extends ConfNamespace {
    public static final int hash = 747740774;
    public int hash() {
        return CiscoIOSXRIpv4BgpOcOper.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-bgp-oc-oper";
    public String id() {
        return CiscoIOSXRIpv4BgpOcOper.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-bgp-oc-oper";
    public String uri() {
        return CiscoIOSXRIpv4BgpOcOper.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRIpv4BgpOcOper.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-ipv4-bgp-oc-oper";
    public String prefix() {
        return CiscoIOSXRIpv4BgpOcOper.prefix;
    }

    public CiscoIOSXRIpv4BgpOcOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _med = 643391629;
    public static final String _med_ = "med";
    public static final int    _aigp = 886491317;
    public static final String _aigp_ = "aigp";
    public static final int    _prefix = 1408440115;
    public static final String _prefix_ = "prefix";
    public static final int    _local_pref = 155876354;
    public static final String _local_pref_ = "local-pref";
    public static final int    _adj_rib_in_post = 685167621;
    public static final String _adj_rib_in_post_ = "adj-rib-in-post";
    public static final int    _open_config_neighbor = 384858759;
    public static final String _open_config_neighbor_ = "open-config-neighbor";
    public static final int    _as4 = 2009670240;
    public static final String _as4_ = "as4";
    public static final int    _ipv6_address = 731894850;
    public static final String _ipv6_address_ = "ipv6-address";
    public static final int    _prefix_name = 749451404;
    public static final String _prefix_name_ = "prefix-name";
    public static final int    _best_path = 1247989707;
    public static final String _best_path_ = "best-path";
    public static final int    _path_id = 374655410;
    public static final String _path_id_ = "path-id";
    public static final int    _atomic_aggr = 417521223;
    public static final String _atomic_aggr_ = "atomic-aggr";
    public static final int    _next_hop = 1889650088;
    public static final String _next_hop_ = "next-hop";
    public static final int    _route = 2058743578;
    public static final String _route_ = "route";
    public static final int    _as4_path = 1050092225;
    public static final String _as4_path_ = "as4-path";
    public static final int    _attribute_value = 252079604;
    public static final String _attribute_value_ = "attribute-value";
    public static final int    _invalid_reason = 1171922829;
    public static final String _invalid_reason_ = "invalid-reason";
    public static final int    _ipv4_address = 400734928;
    public static final String _ipv4_address_ = "ipv4-address";
    public static final int    _open_config_neighbors = 1871755929;
    public static final String _open_config_neighbors_ = "open-config-neighbors";
    public static final int    _bgp_rib = 1260184611;
    public static final String _bgp_rib_ = "bgp-rib";
    public static final int    _num_routes = 1024724404;
    public static final String _num_routes_ = "num-routes";
    public static final int    _last_update_recieved = 1624705760;
    public static final String _last_update_recieved_ = "last-update-recieved";
    public static final int    _origin_type = 677965987;
    public static final String _origin_type_ = "origin-type";
    public static final int    _as_path = 192495808;
    public static final String _as_path_ = "as-path";
    public static final int    _valid_route = 799747014;
    public static final String _valid_route_ = "valid-route";
    public static final int    _attribute_type = 757417286;
    public static final String _attribute_type_ = "attribute-type";
    public static final int    _ext_community = 240286423;
    public static final String _ext_community_ = "ext-community";
    public static final int    _aggregrator_attributes = 147380095;
    public static final String _aggregrator_attributes_ = "aggregrator-attributes";
    public static final int    _oc_bgp = 765047506;
    public static final String _oc_bgp_ = "oc-bgp";
    public static final int    _time_value = 1553632148;
    public static final String _time_value_ = "time-value";
    public static final int    _ipv6_unicast = 540616510;
    public static final String _ipv6_unicast_ = "ipv6-unicast";
    public static final int    _loc_rib = 1251443267;
    public static final String _loc_rib_ = "loc-rib";
    public static final int    _ipv4_unicast = 2018585830;
    public static final String _ipv4_unicast_ = "ipv4-unicast";
    public static final int    _adj_rib_out_pre = 845334501;
    public static final String _adj_rib_out_pre_ = "adj-rib-out-pre";
    public static final int    _adj_rib_out_post = 2112852334;
    public static final String _adj_rib_out_post_ = "adj-rib-out-post";
    public static final int    _routes = 278551890;
    public static final String _routes_ = "routes";
    public static final int    _ext_attributes_list = 100948528;
    public static final String _ext_attributes_list_ = "ext-attributes-list";
    public static final int    _adj_rib_in_pre = 26383927;
    public static final String _adj_rib_in_pre_ = "adj-rib-in-pre";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _afi_safi_table = 969534443;
    public static final String _afi_safi_table_ = "afi-safi-table";
    public static final int    _as = 388223143;
    public static final String _as_ = "as";
    public static final int    _neighbor_address = 1654322417;
    public static final String _neighbor_address_ = "neighbor-address";
    public static final int    _cluster = 2004626063;
    public static final String _cluster_ = "cluster";
    public static final int    _objects = 798508253;
    public static final String _objects_ = "objects";
    public static final int    _afi = 1110348992;
    public static final String _afi_ = "afi";
    public static final int    _last_modified_date = 441470232;
    public static final String _last_modified_date_ = "last-modified-date";
    public static final int    _unknown_attributes = 622663763;
    public static final String _unknown_attributes_ = "unknown-attributes";
    public static final int    _community = 81681536;
    public static final String _community_ = "community";
    public static final int    _route_attr_list = 1557683614;
    public static final String _route_attr_list_ = "route-attr-list";
    public static final int    _originator_id = 919533201;
    public static final String _originator_id_ = "originator-id";
    public static final int    _attribute_length = 252924590;
    public static final String _attribute_length_ = "attribute-length";
    public static final int    _prefix_length = 524393771;
    public static final String _prefix_length_ = "prefix-length";
}
