/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-cdp-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-cdp-oper.yang */
public class CiscoIOSXRCdpOper extends ConfNamespace {
    public static final int hash = 2056389170;
    public int hash() {
        return CiscoIOSXRCdpOper.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-cdp-oper";
    public String id() {
        return CiscoIOSXRCdpOper.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-cdp-oper";
    public String uri() {
        return CiscoIOSXRCdpOper.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRCdpOper.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-cdp-oper";
    public String prefix() {
        return CiscoIOSXRCdpOper.prefix;
    }

    public CiscoIOSXRCdpOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _interface_handle = 1919201419;
    public static final String _interface_handle_ = "interface-handle";
    public static final int    _neighbors = 1478644450;
    public static final String _neighbors_ = "neighbors";
    public static final int    _ipv6_address = 731894850;
    public static final String _ipv6_address_ = "ipv6-address";
    public static final int    _cdp = 1086691831;
    public static final String _cdp_ = "cdp";
    public static final int    _bad_packet_errors = 568959796;
    public static final String _bad_packet_errors_ = "bad-packet-errors";
    public static final int    _duplex = 1052737030;
    public static final String _duplex_ = "duplex";
    public static final int    _system_name = 1975516496;
    public static final String _system_name_ = "system-name";
    public static final int    _details = 817440806;
    public static final String _details_ = "details";
    public static final int    _transmitted_packets = 2089984096;
    public static final String _transmitted_packets_ = "transmitted-packets";
    public static final int    _cdp_addr_entry = 1376236570;
    public static final String _cdp_addr_entry_ = "cdp-addr-entry";
    public static final int    _basecaps_state = 186537885;
    public static final String _basecaps_state_ = "basecaps-state";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _encapsulation_errors = 325923432;
    public static final String _encapsulation_errors_ = "encapsulation-errors";
    public static final int    _received_packets_v1 = 407505568;
    public static final String _received_packets_v1_ = "received-packets-v1";
    public static final int    _header_errors = 1968898069;
    public static final String _header_errors_ = "header-errors";
    public static final int    _header_version_errors = 214184389;
    public static final String _header_version_errors_ = "header-version-errors";
    public static final int    _ipv4_address = 400734928;
    public static final String _ipv4_address_ = "ipv4-address";
    public static final int    _devices = 270307409;
    public static final String _devices_ = "devices";
    public static final int    _hello_message = 1641733459;
    public static final String _hello_message_ = "hello-message";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _vtp_domain = 1115792932;
    public static final String _vtp_domain_ = "vtp-domain";
    public static final int    _version = 1714291735;
    public static final String _version_ = "version";
    public static final int    _device_id = 669279939;
    public static final String _device_id_ = "device-id";
    public static final int    _truncated_packet_errors = 408157228;
    public static final String _truncated_packet_errors_ = "truncated-packet-errors";
    public static final int    _summaries = 1812098070;
    public static final String _summaries_ = "summaries";
    public static final int    _interface_name = 1322899300;
    public static final String _interface_name_ = "interface-name";
    public static final int    _header_version = 1359704219;
    public static final String _header_version_ = "header-version";
    public static final int    _checksum_errors = 1863207457;
    public static final String _checksum_errors_ = "checksum-errors";
    public static final int    _protocol_hello_list = 2004803114;
    public static final String _protocol_hello_list_ = "protocol-hello-list";
    public static final int    _interface_encaps = 541949349;
    public static final String _interface_encaps_ = "interface-encaps";
    public static final int    _statistics = 1049034618;
    public static final String _statistics_ = "statistics";
    public static final int    _native_vlan = 1159886695;
    public static final String _native_vlan_ = "native-vlan";
    public static final int    _detail = 984599342;
    public static final String _detail_ = "detail";
    public static final int    _nodes = 650955465;
    public static final String _nodes_ = "nodes";
    public static final int    _hold_time = 204730640;
    public static final String _hold_time_ = "hold-time";
    public static final int    _node_name = 122353445;
    public static final String _node_name_ = "node-name";
    public static final int    _cdp_prot_hello_entry = 146392960;
    public static final String _cdp_prot_hello_entry_ = "cdp-prot-hello-entry";
    public static final int    _transmitted_packets_v1 = 1832814744;
    public static final String _transmitted_packets_v1_ = "transmitted-packets-v1";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _cdp_protocol_state = 44041483;
    public static final String _cdp_protocol_state_ = "cdp-protocol-state";
    public static final int    _transmitted_packets_v2 = 1341113934;
    public static final String _transmitted_packets_v2_ = "transmitted-packets-v2";
    public static final int    _summary = 738895761;
    public static final String _summary_ = "summary";
    public static final int    _received_packets_v2 = 1648094623;
    public static final String _received_packets_v2_ = "received-packets-v2";
    public static final int    _out_of_memory_errors = 1907009434;
    public static final String _out_of_memory_errors_ = "out-of-memory-errors";
    public static final int    _platform = 688179959;
    public static final String _platform_ = "platform";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _receiving_interface_name = 176228443;
    public static final String _receiving_interface_name_ = "receiving-interface-name";
    public static final int    _address_type = 1062059366;
    public static final String _address_type_ = "address-type";
    public static final int    _cdp_neighbor = 752098561;
    public static final String _cdp_neighbor_ = "cdp-neighbor";
    public static final int    _received_packets = 458197719;
    public static final String _received_packets_ = "received-packets";
    public static final int    _capabilities = 1381570067;
    public static final String _capabilities_ = "capabilities";
    public static final int    _port_id = 411479338;
    public static final String _port_id_ = "port-id";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
    public static final int    _network_addresses = 573483958;
    public static final String _network_addresses_ = "network-addresses";
    public static final int    _open_file_errors = 1022280004;
    public static final String _open_file_errors_ = "open-file-errors";
}
