/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-sysadmin-aaa-aaa-show.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-sysadmin-aaa-aaa-show.yang */
public class CiscoIOSXRSysadminAaaAaaShow extends ConfNamespace {
    public static final int hash = 428148509;
    public int hash() {
        return CiscoIOSXRSysadminAaaAaaShow.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-aaa-aaa-show";
    public String id() {
        return CiscoIOSXRSysadminAaaAaaShow.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-aaa-aaa-show";
    public String uri() {
        return CiscoIOSXRSysadminAaaAaaShow.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRSysadminAaaAaaShow.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-sysadmin-aaa-aaa-show";
    public String prefix() {
        return CiscoIOSXRSysadminAaaAaaShow.prefix;
    }

    public CiscoIOSXRSysadminAaaAaaShow() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _log_data = 562544428;
    public static final String _log_data_ = "log-data";
    public static final int    _first_user_change = 1075308945;
    public static final String _first_user_change_ = "first-user-change";
    public static final int    _privileged_access = 2072027350;
    public static final String _privileged_access_ = "privileged-access";
    public static final int    _grp_data = 904055972;
    public static final String _grp_data_ = "grp-data";
    public static final int    _shell_access = 1078605932;
    public static final String _shell_access_ = "shell-access";
    public static final int    _current_disaster_recovery_user = 889513736;
    public static final String _current_disaster_recovery_user_ = "current-disaster-recovery-user";
    public static final int    _user_group = 980494910;
    public static final String _user_group_ = "user-group";
    public static final int    _first_user = 156942528;
    public static final String _first_user_ = "first-user";
    public static final int    _accounting = 803748480;
    public static final String _accounting_ = "accounting";
}
