/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-l2-eth-infra-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-l2-eth-infra-oper.yang */
public class CiscoIOSXRL2EthInfraOper extends ConfNamespace {
    public static final int hash = 588549292;
    public int hash() {
        return CiscoIOSXRL2EthInfraOper.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-l2-eth-infra-oper";
    public String id() {
        return CiscoIOSXRL2EthInfraOper.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-l2-eth-infra-oper";
    public String uri() {
        return CiscoIOSXRL2EthInfraOper.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRL2EthInfraOper.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-l2-eth-infra-oper";
    public String prefix() {
        return CiscoIOSXRL2EthInfraOper.prefix;
    }

    public CiscoIOSXRL2EthInfraOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _vlan_switched = 176113053;
    public static final String _vlan_switched_ = "vlan-switched";
    public static final int    _up = 1984149991;
    public static final String _up_ = "up";
    public static final int    _tag = 21925559;
    public static final String _tag_ = "tag";
    public static final int    _vlan = 71481437;
    public static final String _vlan_ = "vlan";
    public static final int    _untagged_count = 890932427;
    public static final String _untagged_count_ = "untagged-count";
    public static final int    _parent_interface = 169482247;
    public static final String _parent_interface_ = "parent-interface";
    public static final int    _stack = 755571952;
    public static final String _stack_ = "stack";
    public static final int    _pushe = 1255600286;
    public static final String _pushe_ = "pushe";
    public static final int    _trunks = 15913961;
    public static final String _trunks_ = "trunks";
    public static final int    _admin_down = 353371103;
    public static final String _admin_down_ = "admin-down";
    public static final int    _priority = 1346277862;
    public static final String _priority_ = "priority";
    public static final int    _payload_ethertype = 1782051540;
    public static final String _payload_ethertype_ = "payload-ethertype";
    public static final int    _qin_any_count = 908706550;
    public static final String _qin_any_count_ = "qin-any-count";
    public static final int    _mtu = 1751455506;
    public static final String _mtu_ = "mtu";
    public static final int    _mac_accounting = 1100121058;
    public static final String _mac_accounting_ = "mac-accounting";
    public static final int    _service = 855380710;
    public static final String _service_ = "service";
    public static final int    _first_tag = 1064947953;
    public static final String _first_tag_ = "first-tag";
    public static final int    _unicast_mac_filters = 1093773375;
    public static final String _unicast_mac_filters_ = "unicast-mac-filters";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _untagged_interface = 1724364561;
    public static final String _untagged_interface_ = "untagged-interface";
    public static final int    _vlan_encapsulation = 1591324560;
    public static final String _vlan_encapsulation_ = "vlan-encapsulation";
    public static final int    _is_ingress_enabled = 1315540384;
    public static final String _is_ingress_enabled_ = "is-ingress-enabled";
    public static final int    _tags_to_match = 752703354;
    public static final String _tags_to_match_ = "tags-to-match";
    public static final int    _outer_tag = 1041977611;
    public static final String _outer_tag_ = "outer-tag";
    public static final int    _mode = 575893728;
    public static final String _mode_ = "mode";
    public static final int    _packets = 384560432;
    public static final String _packets_ = "packets";
    public static final int    _trunk = 797138583;
    public static final String _trunk_ = "trunk";
    public static final int    _encapsulation_details = 899525969;
    public static final String _encapsulation_details_ = "encapsulation-details";
    public static final int    _switched_mtu = 541004324;
    public static final String _switched_mtu_ = "switched-mtu";
    public static final int    _mac_address = 2110689796;
    public static final String _mac_address_ = "mac-address";
    public static final int    _layer2_sub_interfaces = 2123646351;
    public static final String _layer2_sub_interfaces_ = "layer2-sub-interfaces";
    public static final int    _source_mac_match = 1054878695;
    public static final String _source_mac_match_ = "source-mac-match";
    public static final int    _native_tag = 1307598455;
    public static final String _native_tag_ = "native-tag";
    public static final int    _destination_mac_match = 1406631843;
    public static final String _destination_mac_match_ = "destination-mac-match";
    public static final int    _local_traffic_stack = 327120964;
    public static final String _local_traffic_stack_ = "local-traffic-stack";
    public static final int    _interface_name = 1322899300;
    public static final String _interface_name_ = "interface-name";
    public static final int    _ingress_statistic = 2073785263;
    public static final String _ingress_statistic_ = "ingress-statistic";
    public static final int    _bytes = 1113108825;
    public static final String _bytes_ = "bytes";
    public static final int    _dot1ad_count = 108797711;
    public static final String _dot1ad_count_ = "dot1ad-count";
    public static final int    _unicast_filter = 1447502790;
    public static final String _unicast_filter_ = "unicast-filter";
    public static final int    _state_counters = 1943313169;
    public static final String _state_counters_ = "state-counters";
    public static final int    _ethertype = 1713629078;
    public static final String _ethertype_ = "ethertype";
    public static final int    _tag_allocation = 197182137;
    public static final String _tag_allocation_ = "tag-allocation";
    public static final int    _unicast_mac_filter = 141173893;
    public static final String _unicast_mac_filter_ = "unicast-mac-filter";
    public static final int    _egress_statistic = 1496628402;
    public static final String _egress_statistic_ = "egress-statistic";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _native_vlan = 1159886695;
    public static final String _native_vlan_ = "native-vlan";
    public static final int    _dot1q_count = 1537496177;
    public static final String _dot1q_count_ = "dot1q-count";
    public static final int    _node_id = 98319925;
    public static final String _node_id_ = "node-id";
    public static final int    _tag_allocations = 718382639;
    public static final String _tag_allocations_ = "tag-allocations";
    public static final int    _is_native_preserving = 787083443;
    public static final String _is_native_preserving_ = "is-native-preserving";
    public static final int    _total_count = 1253123293;
    public static final String _total_count_ = "total-count";
    public static final int    _vlan_id_high = 1153245341;
    public static final String _vlan_id_high_ = "vlan-id-high";
    public static final int    _nodes = 650955465;
    public static final String _nodes_ = "nodes";
    public static final int    _node_name = 122353445;
    public static final String _node_name_ = "node-name";
    public static final int    _number_available_ingress = 1114935084;
    public static final String _number_available_ingress_ = "number-available-ingress";
    public static final int    _interface_xr = 788356460;
    public static final String _interface_xr_ = "interface-xr";
    public static final int    _vlan_id_low = 336391082;
    public static final String _vlan_id_low_ = "vlan-id-low";
    public static final int    _number_available_egress = 808167951;
    public static final String _number_available_egress_ = "number-available-egress";
    public static final int    _service_instance_details = 80333550;
    public static final String _service_instance_details_ = "service-instance-details";
    public static final int    _vlan_range = 2099740110;
    public static final String _vlan_range_ = "vlan-range";
    public static final int    _vlan_id = 1443431623;
    public static final String _vlan_id_ = "vlan-id";
    public static final int    _dot1ad_native_tag = 1985160511;
    public static final String _dot1ad_native_tag_ = "dot1ad-native-tag";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _second_tag = 1851784776;
    public static final String _second_tag_ = "second-tag";
    public static final int    _is_native_vlan = 2045342272;
    public static final String _is_native_vlan_ = "is-native-vlan";
    public static final int    _qin_q_count = 462244771;
    public static final String _qin_q_count_ = "qin-q-count";
    public static final int    _ethernet_encapsulation = 1151352917;
    public static final String _ethernet_encapsulation_ = "ethernet-encapsulation";
    public static final int    _dot1ad_outer_tag = 1176098488;
    public static final String _dot1ad_outer_tag_ = "dot1ad-outer-tag";
    public static final int    _number_available_on_node = 349534988;
    public static final String _number_available_on_node_ = "number-available-on-node";
    public static final int    _is_egress_enabled = 1647443954;
    public static final String _is_egress_enabled_ = "is-egress-enabled";
    public static final int    _trunk_vlan_ranges = 39950477;
    public static final String _trunk_vlan_ranges_ = "trunk-vlan-ranges";
    public static final int    _layer3_sub_interfaces = 898906147;
    public static final String _layer3_sub_interfaces_ = "layer3-sub-interfaces";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
    public static final int    _mac_filtering = 971526764;
    public static final String _mac_filtering_ = "mac-filtering";
    public static final int    _down = 940209651;
    public static final String _down_ = "down";
    public static final int    _local_traffic_tag = 465652150;
    public static final String _local_traffic_tag_ = "local-traffic-tag";
    public static final int    _tags_popped = 624990411;
    public static final String _tags_popped_ = "tags-popped";
    public static final int    _access_vlan = 2014822852;
    public static final String _access_vlan_ = "access-vlan";
    public static final int    _qinq_outer_ether_type = 1149538889;
    public static final String _qinq_outer_ether_type_ = "qinq-outer-ether-type";
    public static final int    _is_exact_match = 393336001;
    public static final String _is_exact_match_ = "is-exact-match";
    public static final int    _dot1ad_tag = 1857140456;
    public static final String _dot1ad_tag_ = "dot1ad-tag";
    public static final int    _dot1ad_dot1q_stack = 1608473163;
    public static final String _dot1ad_dot1q_stack_ = "dot1ad-dot1q-stack";
}
