/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-dnx-port-mapper-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-dnx-port-mapper-oper.yang */
public class CiscoIOSXRDnxPortMapperOper extends ConfNamespace {
    public static final int hash = 200308785;
    public int hash() {
        return CiscoIOSXRDnxPortMapperOper.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-dnx-port-mapper-oper";
    public String id() {
        return CiscoIOSXRDnxPortMapperOper.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-dnx-port-mapper-oper";
    public String uri() {
        return CiscoIOSXRDnxPortMapperOper.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRDnxPortMapperOper.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-dnx-port-mapper-oper";
    public String prefix() {
        return CiscoIOSXRDnxPortMapperOper.prefix;
    }

    public CiscoIOSXRDnxPortMapperOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _oor = 2032710627;
    public static final String _oor_ = "oor";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _interface_names = 1817034827;
    public static final String _interface_names_ = "interface-names";
    public static final int    _npu_id = 1045918085;
    public static final String _npu_id_ = "npu-id";
    public static final int    _interface_name = 1322899300;
    public static final String _interface_name_ = "interface-name";
    public static final int    _green = 829185461;
    public static final String _green_ = "green";
    public static final int    _red = 2127368523;
    public static final String _red_ = "red";
    public static final int    _interface_status = 1493757347;
    public static final String _interface_status_ = "interface-status";
    public static final int    _yel_low = 681146200;
    public static final String _yel_low_ = "yel-low";
    public static final int    _nodes = 650955465;
    public static final String _nodes_ = "nodes";
    public static final int    _node_name = 122353445;
    public static final String _node_name_ = "node-name";
    public static final int    _hardware_resource = 1244927386;
    public static final String _hardware_resource_ = "hardware-resource";
    public static final int    _summary = 738895761;
    public static final String _summary_ = "summary";
    public static final int    _time_stamp = 1142368672;
    public static final String _time_stamp_ = "time-stamp";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
}
