/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-mpls-oam-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-mpls-oam-cfg.yang */
public class CiscoIOSXRMplsOamCfg extends ConfNamespace {
    public static final int hash = 1390619568;
    public int hash() {
        return CiscoIOSXRMplsOamCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mpls-oam-cfg";
    public String id() {
        return CiscoIOSXRMplsOamCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mpls-oam-cfg";
    public String uri() {
        return CiscoIOSXRMplsOamCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRMplsOamCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-mpls-oam-cfg";
    public String prefix() {
        return CiscoIOSXRMplsOamCfg.prefix;
    }

    public CiscoIOSXRMplsOamCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _allow_reverse_lsp = 553257459;
    public static final String _allow_reverse_lsp_ = "allow-reverse-lsp";
    public static final int    _enable_oam = 32895100;
    public static final String _enable_oam_ = "enable-oam";
    public static final int    _control_channel = 894250229;
    public static final String _control_channel_ = "control-channel";
    public static final int    _mpls_oam = 1256629070;
    public static final String _mpls_oam_ = "mpls-oam";
    public static final int    _disable_vendor_extension = 1374951834;
    public static final String _disable_vendor_extension_ = "disable-vendor-extension";
    public static final int    _reply_mode = 1518912922;
    public static final String _reply_mode_ = "reply-mode";
}
