/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-fretta-grid-svr-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-fretta-grid-svr-oper.yang */
public class CiscoIOSXRFrettaGridSvrOper extends ConfNamespace {
    public static final int hash = 1246757416;
    public int hash() {
        return CiscoIOSXRFrettaGridSvrOper.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-fretta-grid-svr-oper";
    public String id() {
        return CiscoIOSXRFrettaGridSvrOper.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-fretta-grid-svr-oper";
    public String uri() {
        return CiscoIOSXRFrettaGridSvrOper.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRFrettaGridSvrOper.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-fretta-grid-svr-oper";
    public String prefix() {
        return CiscoIOSXRFrettaGridSvrOper.prefix;
    }

    public CiscoIOSXRFrettaGridSvrOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _client_name = 805960493;
    public static final String _client_name_ = "client-name";
    public static final int    _client_xr = 494894495;
    public static final String _client_xr_ = "client-xr";
    public static final int    _grid = 2062441156;
    public static final String _grid_ = "grid";
    public static final int    _client = 2128680708;
    public static final String _client_ = "client";
    public static final int    _client_data = 651784979;
    public static final String _client_data_ = "client-data";
    public static final int    _res_id = 1094861740;
    public static final String _res_id_ = "res-id";
    public static final int    _nodes = 650955465;
    public static final String _nodes_ = "nodes";
    public static final int    _node_name = 122353445;
    public static final String _node_name_ = "node-name";
    public static final int    _clients = 2113358574;
    public static final String _clients_ = "clients";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
}
