/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-syslog-act.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-syslog-act.yang */
public class CiscoIOSXRSyslogAct extends ConfNamespace {
    public static final int hash = 12232856;
    public int hash() {
        return CiscoIOSXRSyslogAct.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-syslog-act";
    public String id() {
        return CiscoIOSXRSyslogAct.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-syslog-act";
    public String uri() {
        return CiscoIOSXRSyslogAct.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRSyslogAct.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-syslog-act";
    public String prefix() {
        return CiscoIOSXRSyslogAct.prefix;
    }

    public CiscoIOSXRSyslogAct() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _logmsg = 470414941;
    public static final String _logmsg_ = "logmsg";
    public static final int    _message = 1674281495;
    public static final String _message_ = "message";
    public static final int    _rpc_logmsg = 580077073;
    public static final String _rpc_logmsg_ = "rpc-logmsg";
    public static final int    _severity = 483607279;
    public static final String _severity_ = "severity";
}
