/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-sysadmin-entity-mib.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-sysadmin-entity-mib.yang */
public class CiscoIOSXRSysadminEntityMib extends ConfNamespace {
    public static final int hash = 192468457;
    public int hash() {
        return CiscoIOSXRSysadminEntityMib.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-entity-mib";
    public String id() {
        return CiscoIOSXRSysadminEntityMib.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-entity-mib";
    public String uri() {
        return CiscoIOSXRSysadminEntityMib.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRSysadminEntityMib.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-sysadmin-entity-mib";
    public String prefix() {
        return CiscoIOSXRSysadminEntityMib.prefix;
    }

    public CiscoIOSXRSysadminEntityMib() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _entPhysicalFirmwareRev = 1502178123;
    public static final String _entPhysicalFirmwareRev_ = "entPhysicalFirmwareRev";
    public static final int    _entPhysicalClass = 837256101;
    public static final String _entPhysicalClass_ = "entPhysicalClass";
    public static final int    _entPhysicalContainsEntry = 2128783499;
    public static final String _entPhysicalContainsEntry_ = "entPhysicalContainsEntry";
    public static final int    _entLogicalTAddress = 1163207655;
    public static final String _entLogicalTAddress_ = "entLogicalTAddress";
    public static final int    _entLogicalContextName = 1772107546;
    public static final String _entLogicalContextName_ = "entLogicalContextName";
    public static final int    _entPhysicalVendorType = 1497975472;
    public static final String _entPhysicalVendorType_ = "entPhysicalVendorType";
    public static final int    _entPhysicalTable = 933965314;
    public static final String _entPhysicalTable_ = "entPhysicalTable";
    public static final int    _entLPPhysicalIndex = 761758204;
    public static final String _entLPPhysicalIndex_ = "entLPPhysicalIndex";
    public static final int    _entPhysicalContainsTable = 1531489612;
    public static final String _entPhysicalContainsTable_ = "entPhysicalContainsTable";
    public static final int    _entLogicalTDomain = 734816689;
    public static final String _entLogicalTDomain_ = "entLogicalTDomain";
    public static final int    _entPhysicalIsFRU = 902460344;
    public static final String _entPhysicalIsFRU_ = "entPhysicalIsFRU";
    public static final int    _entAliasMappingIdentifier = 242538309;
    public static final String _entAliasMappingIdentifier_ = "entAliasMappingIdentifier";
    public static final int    _entPhysicalContainedIn = 1515434692;
    public static final String _entPhysicalContainedIn_ = "entPhysicalContainedIn";
    public static final int    _entAliasMappingTable = 1196694356;
    public static final String _entAliasMappingTable_ = "entAliasMappingTable";
    public static final int    _entLPMappingTable = 1234653233;
    public static final String _entLPMappingTable_ = "entLPMappingTable";
    public static final int    _entPhysicalIndex = 1204442522;
    public static final String _entPhysicalIndex_ = "entPhysicalIndex";
    public static final int    _entAliasLogicalIndexOrZero = 436401232;
    public static final String _entAliasLogicalIndexOrZero_ = "entAliasLogicalIndexOrZero";
    public static final int    _entPhysicalAssetID = 921280317;
    public static final String _entPhysicalAssetID_ = "entPhysicalAssetID";
    public static final int    _entLogicalType = 1575910689;
    public static final String _entLogicalType_ = "entLogicalType";
    public static final int    _entPhysicalDescr = 770510405;
    public static final String _entPhysicalDescr_ = "entPhysicalDescr";
    public static final int    _entPhysicalParentRelPos = 1190216296;
    public static final String _entPhysicalParentRelPos_ = "entPhysicalParentRelPos";
    public static final int    _entPhysicalModelName = 1648927721;
    public static final String _entPhysicalModelName_ = "entPhysicalModelName";
    public static final int    _entPhysicalSerialNum = 2106499242;
    public static final String _entPhysicalSerialNum_ = "entPhysicalSerialNum";
    public static final int    _entAliasMappingEntry = 503850494;
    public static final String _entAliasMappingEntry_ = "entAliasMappingEntry";
    public static final int    _entLPMappingEntry = 495528800;
    public static final String _entLPMappingEntry_ = "entLPMappingEntry";
    public static final int    _entLogicalDescr = 1032590012;
    public static final String _entLogicalDescr_ = "entLogicalDescr";
    public static final int    _entPhysicalSoftwareRev = 1216689416;
    public static final String _entPhysicalSoftwareRev_ = "entPhysicalSoftwareRev";
    public static final int    _entLogicalCommunity = 795585428;
    public static final String _entLogicalCommunity_ = "entLogicalCommunity";
    public static final int    _entPhysicalMfgName = 192565187;
    public static final String _entPhysicalMfgName_ = "entPhysicalMfgName";
    public static final int    _entLogicalContextEngineID = 1837977313;
    public static final String _entLogicalContextEngineID_ = "entLogicalContextEngineID";
    public static final int    _entLogicalIndex = 1428089914;
    public static final String _entLogicalIndex_ = "entLogicalIndex";
    public static final int    _entLastChangeTime = 1869408861;
    public static final String _entLastChangeTime_ = "entLastChangeTime";
    public static final int    _ENTITY_MIB = 1623520613;
    public static final String _ENTITY_MIB_ = "ENTITY-MIB";
    public static final int    _entLogicalTable = 1223963716;
    public static final String _entLogicalTable_ = "entLogicalTable";
    public static final int    _entityGeneral = 1546797888;
    public static final String _entityGeneral_ = "entityGeneral";
    public static final int    _entPhysicalHardwareRev = 1478637336;
    public static final String _entPhysicalHardwareRev_ = "entPhysicalHardwareRev";
    public static final int    _entLogicalEntry = 2042349926;
    public static final String _entLogicalEntry_ = "entLogicalEntry";
    public static final int    _entPhysicalEntry = 199182460;
    public static final String _entPhysicalEntry_ = "entPhysicalEntry";
    public static final int    _entPhysicalName = 803957675;
    public static final String _entPhysicalName_ = "entPhysicalName";
    public static final int    _entPhysicalChildIndex = 479866645;
    public static final String _entPhysicalChildIndex_ = "entPhysicalChildIndex";
    public static final int    _entPhysicalAlias = 1015702998;
    public static final String _entPhysicalAlias_ = "entPhysicalAlias";
}
