/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-aaa-lib-datatypes.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-aaa-lib-datatypes.yang */
public class CiscoIOSXRAaaLibDatatypes extends ConfNamespace {
    public static final int hash = 883439436;
    public int hash() {
        return CiscoIOSXRAaaLibDatatypes.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-lib-datatypes";
    public String id() {
        return CiscoIOSXRAaaLibDatatypes.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-lib-datatypes";
    public String uri() {
        return CiscoIOSXRAaaLibDatatypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRAaaLibDatatypes.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-aaa-lib-datatypes";
    public String prefix() {
        return CiscoIOSXRAaaLibDatatypes.prefix;
    }

    public CiscoIOSXRAaaLibDatatypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
