/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-sysadmin-show-diag.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-sysadmin-show-diag.yang */
public class CiscoIOSXRSysadminShowDiag extends ConfNamespace {
    public static final int hash = 731296206;
    public int hash() {
        return CiscoIOSXRSysadminShowDiag.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-show-diag";
    public String id() {
        return CiscoIOSXRSysadminShowDiag.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-show-diag";
    public String uri() {
        return CiscoIOSXRSysadminShowDiag.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRSysadminShowDiag.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-sysadmin-show-diag";
    public String prefix() {
        return CiscoIOSXRSysadminShowDiag.prefix;
    }

    public CiscoIOSXRSysadminShowDiag() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _default_list = 1377331998;
    public static final String _default_list_ = "default_list";
    public static final int    _chassis_eeprom_cnt = 2077456802;
    public static final String _chassis_eeprom_cnt_ = "chassis_eeprom_cnt";
    public static final int    _chassis_list = 7053547;
    public static final String _chassis_list_ = "chassis_list";
    public static final int    _default_out_list = 1622903993;
    public static final String _default_out_list_ = "default_out_list";
    public static final int    _fans_list = 424330907;
    public static final String _fans_list_ = "fans_list";
    public static final int    _location = 1827424758;
    public static final String _location_ = "location";
    public static final int    _eeprom_list = 336449503;
    public static final String _eeprom_list_ = "eeprom_list";
    public static final int    _eeprom_data = 807499095;
    public static final String _eeprom_data_ = "eeprom-data";
    public static final int    _default = 515137925;
    public static final String _default_ = "default";
    public static final int    _eeprom = 1243770252;
    public static final String _eeprom_ = "eeprom";
    public static final int    _chassis = 247732213;
    public static final String _chassis_ = "chassis";
    public static final int    _detail_list = 1675510792;
    public static final String _detail_list_ = "detail_list";
    public static final int    _raw_list = 1690800123;
    public static final String _raw_list_ = "raw_list";
    public static final int    _detail = 984599342;
    public static final String _detail_ = "detail";
    public static final int    _fans = 50638464;
    public static final String _fans_ = "fans";
    public static final int    _power_supply = 1094968203;
    public static final String _power_supply_ = "power-supply";
    public static final int    _chassis_eeprom_list = 1646961942;
    public static final String _chassis_eeprom_list_ = "chassis_eeprom_list";
    public static final int    _diag = 2046963701;
    public static final String _diag_ = "diag";
    public static final int    _detail_data = 138145036;
    public static final String _detail_data_ = "detail-data";
    public static final int    _chassis_cnt = 842863430;
    public static final String _chassis_cnt_ = "chassis_cnt";
    public static final int    _summary = 738895761;
    public static final String _summary_ = "summary";
    public static final int    _default_data = 1199634267;
    public static final String _default_data_ = "default-data";
    public static final int    _pwr_list = 1530577720;
    public static final String _pwr_list_ = "pwr_list";
    public static final int    _detail_out_list = 1490761126;
    public static final String _detail_out_list_ = "detail_out_list";
    public static final int    _summary_out_list = 224676442;
    public static final String _summary_out_list_ = "summary_out_list";
    public static final int    _summary_list = 402477733;
    public static final String _summary_list_ = "summary_list";
    public static final int    _summary_data = 868291525;
    public static final String _summary_data_ = "summary-data";
}
