/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-watchd-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-watchd-cfg.yang */
public class CiscoIOSXRWatchdCfg extends ConfNamespace {
    public static final int hash = 41405930;
    public int hash() {
        return CiscoIOSXRWatchdCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-watchd-cfg";
    public String id() {
        return CiscoIOSXRWatchdCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-watchd-cfg";
    public String uri() {
        return CiscoIOSXRWatchdCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRWatchdCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-watchd-cfg";
    public String prefix() {
        return CiscoIOSXRWatchdCfg.prefix;
    }

    public CiscoIOSXRWatchdCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _threshold_memory = 1323613705;
    public static final String _threshold_memory_ = "threshold-memory";
    public static final int    _restart_memoryhog_disable = 1084270518;
    public static final String _restart_memoryhog_disable_ = "restart-memoryhog-disable";
    public static final int    _minor = 589662983;
    public static final String _minor_ = "minor";
    public static final int    _watchdog_node_threshold = 85784173;
    public static final String _watchdog_node_threshold_ = "watchdog-node-threshold";
    public static final int    _watchd = 803333141;
    public static final String _watchd_ = "watchd";
    public static final int    _overload_throttle_timeout = 1398951154;
    public static final String _overload_throttle_timeout_ = "overload-throttle-timeout";
    public static final int    _memory_threshold = 2065709127;
    public static final String _memory_threshold_ = "memory-threshold";
    public static final int    _overload_notification = 1388405155;
    public static final String _overload_notification_ = "overload-notification";
    public static final int    _watchdog = 1352410101;
    public static final String _watchdog_ = "watchdog";
    public static final int    _timeout = 614210192;
    public static final String _timeout_ = "timeout";
    public static final int    _disk_limit = 1073826599;
    public static final String _disk_limit_ = "disk-limit";
    public static final int    _disk_threshold = 788954322;
    public static final String _disk_threshold_ = "disk-threshold";
    public static final int    _restart_deadlock_disable = 2034209728;
    public static final String _restart_deadlock_disable_ = "restart-deadlock-disable";
    public static final int    _critical = 1856469166;
    public static final String _critical_ = "critical";
    public static final int    _severe = 2064617282;
    public static final String _severe_ = "severe";
}
