/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-mpls-io-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-mpls-io-oper.yang */
public class CiscoIOSXRMplsIoOper extends ConfNamespace {
    public static final int hash = 536833803;
    public int hash() {
        return CiscoIOSXRMplsIoOper.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mpls-io-oper";
    public String id() {
        return CiscoIOSXRMplsIoOper.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mpls-io-oper";
    public String uri() {
        return CiscoIOSXRMplsIoOper.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRMplsIoOper.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-mpls-io-oper";
    public String prefix() {
        return CiscoIOSXRMplsIoOper.prefix;
    }

    public CiscoIOSXRMplsIoOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _srte_label_stack_depth = 2010198068;
    public static final String _srte_label_stack_depth_ = "srte-label-stack-depth";
    public static final int    _mtu = 1751455506;
    public static final String _mtu_ = "mtu";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _pri_label_stack_depth = 129803306;
    public static final String _pri_label_stack_depth_ = "pri-label-stack-depth";
    public static final int    _bkp_label_stack_depth = 937828125;
    public static final String _bkp_label_stack_depth_ = "bkp-label-stack-depth";
    public static final int    _mpls_ma = 148889303;
    public static final String _mpls_ma_ = "mpls-ma";
    public static final int    _interface_name = 1322899300;
    public static final String _interface_name_ = "interface-name";
    public static final int    _nodes = 650955465;
    public static final String _nodes_ = "nodes";
    public static final int    _node_name = 122353445;
    public static final String _node_name_ = "node-name";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
    public static final int    _mpls_ea = 481098347;
    public static final String _mpls_ea_ = "mpls-ea";
}
