/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-mpls-lsd-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-mpls-lsd-cfg.yang */
public class CiscoIOSXRMplsLsdCfg extends ConfNamespace {
    public static final int hash = 1783538310;
    public int hash() {
        return CiscoIOSXRMplsLsdCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mpls-lsd-cfg";
    public String id() {
        return CiscoIOSXRMplsLsdCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mpls-lsd-cfg";
    public String uri() {
        return CiscoIOSXRMplsLsdCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRMplsLsdCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-mpls-lsd-cfg";
    public String prefix() {
        return CiscoIOSXRMplsLsdCfg.prefix;
    }

    public CiscoIOSXRMplsLsdCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _label_range = 3169036;
    public static final String _label_range_ = "label-range";
    public static final int    _mpls_lsd = 1768347525;
    public static final String _mpls_lsd_ = "mpls-lsd";
    public static final int    _minvalue = 1804936381;
    public static final String _minvalue_ = "minvalue";
    public static final int    _ttl_expiration_pop = 1629564736;
    public static final String _ttl_expiration_pop_ = "ttl-expiration-pop";
    public static final int    _max_value = 772314694;
    public static final String _max_value_ = "max-value";
    public static final int    _label_database = 1863182287;
    public static final String _label_database_ = "label-database";
    public static final int    _label_database_id = 225920547;
    public static final String _label_database_id_ = "label-database-id";
    public static final int    _label_databases = 1908041681;
    public static final String _label_databases_ = "label-databases";
    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _max_static_value = 496057413;
    public static final String _max_static_value_ = "max-static-value";
    public static final int    _ltrace_multiplier = 493728310;
    public static final String _ltrace_multiplier_ = "ltrace-multiplier";
    public static final int    _ipv6 = 1228132394;
    public static final String _ipv6_ = "ipv6";
    public static final int    _min_static_value = 144162523;
    public static final String _min_static_value_ = "min-static-value";
    public static final int    _mpls_entropy_label = 1551112481;
    public static final String _mpls_entropy_label_ = "mpls-entropy-label";
    public static final int    _mpls_ip_ttl_propagate_disable = 491109287;
    public static final String _mpls_ip_ttl_propagate_disable_ = "mpls-ip-ttl-propagate-disable";
    public static final int    _app_reg_delay_disable = 1746919571;
    public static final String _app_reg_delay_disable_ = "app-reg-delay-disable";
}
