/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-ip-udp-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-ip-udp-oper.yang */
public class CiscoIOSXRIpUdpOper extends ConfNamespace {
    public static final int hash = 566339629;
    public int hash() {
        return CiscoIOSXRIpUdpOper.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-udp-oper";
    public String id() {
        return CiscoIOSXRIpUdpOper.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-udp-oper";
    public String uri() {
        return CiscoIOSXRIpUdpOper.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRIpUdpOper.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-ip-udp-oper";
    public String prefix() {
        return CiscoIOSXRIpUdpOper.prefix;
    }

    public CiscoIOSXRIpUdpOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _router_alert = 1327494832;
    public static final String _router_alert_ = "router-alert";
    public static final int    _ipv6_traffic = 318396971;
    public static final String _ipv6_traffic_ = "ipv6-traffic";
    public static final int    _vrf_id = 2037305089;
    public static final String _vrf_id_ = "vrf-id";
    public static final int    _is_interface = 802813641;
    public static final String _is_interface_ = "is-interface";
    public static final int    _is_remote_address = 199340652;
    public static final String _is_remote_address_ = "is-remote-address";
    public static final int    _recv_l2_header = 1147444942;
    public static final String _recv_l2_header_ = "recv-l2-header";
    public static final int    _received_drop_packets = 1189637623;
    public static final String _received_drop_packets_ = "received-drop-packets";
    public static final int    _is_paw_socket = 965998038;
    public static final String _is_paw_socket_ = "is-paw-socket";
    public static final int    _pcb_briefs = 2081810506;
    public static final String _pcb_briefs_ = "pcb-briefs";
    public static final int    _icmp_message_type = 1216914939;
    public static final String _icmp_message_type_ = "icmp-message-type";
    public static final int    _is_ignore_vrf_filter = 1951195875;
    public static final String _is_ignore_vrf_filter_ = "is-ignore-vrf-filter";
    public static final int    _client_name = 805960493;
    public static final String _client_name_ = "client-name";
    public static final int    _recv_dest_header = 723032213;
    public static final String _recv_dest_header_ = "recv-dest-header";
    public static final int    _ipv6_address = 731894850;
    public static final String _ipv6_address_ = "ipv6-address";
    public static final int    _receive = 716682309;
    public static final String _receive_ = "receive";
    public static final int    _conn_limit = 113470635;
    public static final String _conn_limit_ = "conn-limit";
    public static final int    _filter = 518848087;
    public static final String _filter_ = "filter";
    public static final int    _priority = 1346277862;
    public static final String _priority_ = "priority";
    public static final int    _query = 530427981;
    public static final String _query_ = "query";
    public static final int    _flow_types_info = 1533455987;
    public static final String _flow_types_info_ = "flow-types-info";
    public static final int    _received_application_bytes = 1738861762;
    public static final String _received_application_bytes_ = "received-application-bytes";
    public static final int    _lpts = 565852751;
    public static final String _lpts_ = "lpts";
    public static final int    _ipv6_sent_packets = 2066260306;
    public static final String _ipv6_sent_packets_ = "ipv6-sent-packets";
    public static final int    _common = 12796818;
    public static final String _common_ = "common";
    public static final int    _lpts_flags = 56380582;
    public static final String _lpts_flags_ = "lpts-flags";
    public static final int    _received_network_packets = 781180064;
    public static final String _received_network_packets_ = "received-network-packets";
    public static final int    _recv_hop_limit = 561985942;
    public static final String _recv_hop_limit_ = "recv-hop-limit";
    public static final int    _is_local_address = 1547904216;
    public static final String _is_local_address_ = "is-local-address";
    public static final int    _pcb_statistics = 1504369349;
    public static final String _pcb_statistics_ = "pcb-statistics";
    public static final int    _failed_queued_application_socket_packets = 1866704541;
    public static final String _failed_queued_application_socket_packets_ = "failed-queued-application-socket-packets";
    public static final int    _client = 2128680708;
    public static final String _client_ = "client";
    public static final int    _udp_output_packets = 165172074;
    public static final String _udp_output_packets_ = "udp-output-packets";
    public static final int    _ipv4_address = 400734928;
    public static final String _ipv4_address_ = "ipv4-address";
    public static final int    _udp_connection = 326960761;
    public static final String _udp_connection_ = "udp-connection";
    public static final int    _recv_packet_info = 335905815;
    public static final String _recv_packet_info_ = "recv-packet-info";
    public static final int    _sent_total_packets = 945520534;
    public static final String _sent_total_packets_ = "sent-total-packets";
    public static final int    _pcb_address = 73192365;
    public static final String _pcb_address_ = "pcb-address";
    public static final int    _udp_input_packets = 1318860868;
    public static final String _udp_input_packets_ = "udp-input-packets";
    public static final int    _cloned_packets = 77802948;
    public static final String _cloned_packets_ = "cloned-packets";
    public static final int    _is_pcb_bound = 2126763261;
    public static final String _is_pcb_bound_ = "is-pcb-bound";
    public static final int    _received_total_packets = 815708081;
    public static final String _received_total_packets_ = "received-total-packets";
    public static final int    _recv_ip_sec = 2060562166;
    public static final String _recv_ip_sec_ = "recv-ip-sec";
    public static final int    _ipv6_received_packets = 242258591;
    public static final String _ipv6_received_packets_ = "ipv6-received-packets";
    public static final int    _received_bad_checksum_packets = 1548099107;
    public static final String _received_bad_checksum_packets_ = "received-bad-checksum-packets";
    public static final int    _receive_queue = 669608667;
    public static final String _receive_queue_ = "receive-queue";
    public static final int    _af_name = 1810421312;
    public static final String _af_name_ = "af-name";
    public static final int    _recv_header = 256697368;
    public static final String _recv_header_ = "recv-header";
    public static final int    _packet_type = 1712646039;
    public static final String _packet_type_ = "packet-type";
    public static final int    _recv_tabel_id = 423611846;
    public static final String _recv_tabel_id_ = "recv-tabel-id";
    public static final int    _ipv4_traffic = 82397273;
    public static final String _ipv4_traffic_ = "ipv4-traffic";
    public static final int    _is_packet_type = 108408023;
    public static final String _is_packet_type_ = "is-packet-type";
    public static final int    _local_process_id = 383283956;
    public static final String _local_process_id_ = "local-process-id";
    public static final int    _udp_no_port_packets = 1896147546;
    public static final String _udp_no_port_packets_ = "udp-no-port-packets";
    public static final int    _interface_name = 1322899300;
    public static final String _interface_name_ = "interface-name";
    public static final int    _recv_opts = 781651554;
    public static final String _recv_opts_ = "recv-opts";
    public static final int    _pcb_flags = 736479610;
    public static final String _pcb_flags_ = "pcb-flags";
    public static final int    _udp_checksum_error_packets = 727481727;
    public static final String _udp_checksum_error_packets_ = "udp-checksum-error-packets";
    public static final int    _bind_local = 1536167961;
    public static final String _bind_local_ = "bind-local";
    public static final int    _received_no_port_packets = 95763515;
    public static final String _received_no_port_packets_ = "received-no-port-packets";
    public static final int    _pcb_detail = 697962733;
    public static final String _pcb_detail_ = "pcb-detail";
    public static final int    _is_local_port = 23460658;
    public static final String _is_local_port_ = "is-local-port";
    public static final int    _queued_application_socket_packets = 1480797157;
    public static final String _queued_application_socket_packets_ = "queued-application-socket-packets";
    public static final int    _failed_queued_net_io_packets = 1511408222;
    public static final String _failed_queued_net_io_packets_ = "failed-queued-net-io-packets";
    public static final int    _igmp_message_type = 1122524056;
    public static final String _igmp_message_type_ = "igmp-message-type";
    public static final int    _recv_intf = 1500178403;
    public static final String _recv_intf_ = "recv-intf";
    public static final int    _received_xipc_pulses = 1518794250;
    public static final String _received_xipc_pulses_ = "received-xipc-pulses";
    public static final int    _recv_traffic_class = 65380807;
    public static final String _recv_traffic_class_ = "recv-traffic-class";
    public static final int    _statistics = 1049034618;
    public static final String _statistics_ = "statistics";
    public static final int    _received_too_short_packets = 722401999;
    public static final String _received_too_short_packets_ = "received-too-short-packets";
    public static final int    _receive_local_port = 1487424407;
    public static final String _receive_local_port_ = "receive-local-port";
    public static final int    _sent_network_packets = 1720351468;
    public static final String _sent_network_packets_ = "sent-network-packets";
    public static final int    _recv_ret_opts = 1698114705;
    public static final String _recv_ret_opts_ = "recv-ret-opts";
    public static final int    _query_name = 1276879513;
    public static final String _query_name_ = "query-name";
    public static final int    _forward_broadcast_packets = 915244086;
    public static final String _forward_broadcast_packets_ = "forward-broadcast-packets";
    public static final int    _header_include = 1786454475;
    public static final String _header_include_ = "header-include";
    public static final int    _udp_bad_length_packets = 225082488;
    public static final String _udp_bad_length_packets_ = "udp-bad-length-packets";
    public static final int    _failed_queued_application_packets = 1504373037;
    public static final String _failed_queued_application_packets_ = "failed-queued-application-packets";
    public static final int    _receive_remote_port = 1679015908;
    public static final String _receive_remote_port_ = "receive-remote-port";
    public static final int    _accept_mask = 1588996477;
    public static final String _accept_mask_ = "accept-mask";
    public static final int    _nodes = 650955465;
    public static final String _nodes_ = "nodes";
    public static final int    _opt_handled = 1498406836;
    public static final String _opt_handled_ = "opt-handled";
    public static final int    _pcb_statistic = 1036684239;
    public static final String _pcb_statistic_ = "pcb-statistic";
    public static final int    _queued_application_packets = 1326102012;
    public static final String _queued_application_packets_ = "queued-application-packets";
    public static final int    _node_name = 122353445;
    public static final String _node_name_ = "node-name";
    public static final int    _pcb_details = 1119221694;
    public static final String _pcb_details_ = "pcb-details";
    public static final int    _client_jid = 921116653;
    public static final String _client_jid_ = "client-jid";
    public static final int    _l4_protocol = 1422888558;
    public static final String _l4_protocol_ = "l4-protocol";
    public static final int    _recv_hop_header = 1401932932;
    public static final String _recv_hop_header_ = "recv-hop-header";
    public static final int    _send_queue = 1296014712;
    public static final String _send_queue_ = "send-queue";
    public static final int    _failed_clone_packets = 1866595445;
    public static final String _failed_clone_packets_ = "failed-clone-packets";
    public static final int    _pcbs = 1384188822;
    public static final String _pcbs_ = "pcbs";
    public static final int    _mcast_loopback = 774307702;
    public static final String _mcast_loopback_ = "mcast-loopback";
    public static final int    _recv_pak_priority = 88992259;
    public static final String _recv_pak_priority_ = "recv-pak-priority";
    public static final int    _foreign_address = 823815258;
    public static final String _foreign_address_ = "foreign-address";
    public static final int    _summary = 738895761;
    public static final String _summary_ = "summary";
    public static final int    _message_id = 288248500;
    public static final String _message_id_ = "message-id";
    public static final int    _udp_dropped_packets = 1765500998;
    public static final String _udp_dropped_packets_ = "udp-dropped-packets";
    public static final int    _remote_length = 397128650;
    public static final String _remote_length_ = "remote-length";
    public static final int    _clients = 2113358574;
    public static final String _clients_ = "clients";
    public static final int    _local_length = 158107428;
    public static final String _local_length_ = "local-length";
    public static final int    _is_receive_filter = 1347731125;
    public static final String _is_receive_filter_ = "is-receive-filter";
    public static final int    _foreign_port = 723496896;
    public static final String _foreign_port_ = "foreign-port";
    public static final int    _pcb = 1397792187;
    public static final String _pcb_ = "pcb";
    public static final int    _local_address = 856636202;
    public static final String _local_address_ = "local-address";
    public static final int    _local_port = 560832355;
    public static final String _local_port_ = "local-port";
    public static final int    _sent_error_packets = 606887587;
    public static final String _sent_error_packets_ = "sent-error-packets";
    public static final int    _lpts_pcb = 1388879170;
    public static final String _lpts_pcb_ = "lpts-pcb";
    public static final int    _icm_pv6_message_type = 1496356618;
    public static final String _icm_pv6_message_type_ = "icm-pv6-message-type";
    public static final int    _udp = 613514645;
    public static final String _udp_ = "udp";
    public static final int    _ipv4_sent_packets = 962643252;
    public static final String _ipv4_sent_packets_ = "ipv4-sent-packets";
    public static final int    _is_ip_sla = 1970456183;
    public static final String _is_ip_sla_ = "is-ip-sla";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _sent_net_io_packets = 2021566984;
    public static final String _sent_net_io_packets_ = "sent-net-io-packets";
    public static final int    _is_remote_port = 267694106;
    public static final String _is_remote_port_ = "is-remote-port";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
    public static final int    _ttl = 774234709;
    public static final String _ttl_ = "ttl";
    public static final int    _client_id = 862765095;
    public static final String _client_id_ = "client-id";
    public static final int    _remote_address = 829475023;
    public static final String _remote_address_ = "remote-address";
    public static final int    _send = 1238787519;
    public static final String _send_ = "send";
    public static final int    _recv_dest_addr = 1496040606;
    public static final String _recv_dest_addr_ = "recv-dest-addr";
    public static final int    _failed_queued_network_packets = 1423437888;
    public static final String _failed_queued_network_packets_ = "failed-queued-network-packets";
    public static final int    _options = 268171404;
    public static final String _options_ = "options";
    public static final int    _queries = 2077794586;
    public static final String _queries_ = "queries";
    public static final int    _is_local_address_ignore = 2086484487;
    public static final String _is_local_address_ignore_ = "is-local-address-ignore";
    public static final int    _pcb_brief = 1266939577;
    public static final String _pcb_brief_ = "pcb-brief";
    public static final int    _ipv4_received_packets = 611576834;
    public static final String _ipv4_received_packets_ = "ipv4-received-packets";
    public static final int    _recv_routing_header = 455534883;
    public static final String _recv_routing_header_ = "recv-routing-header";
}
