/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-sysadmin-aaa-disaster-recovery.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-sysadmin-aaa-disaster-recovery.yang */
public class CiscoIOSXRSysadminAaaDisasterRecovery extends ConfNamespace {
    public static final int hash = 1949431563;
    public int hash() {
        return CiscoIOSXRSysadminAaaDisasterRecovery.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-aaa-disaster-recovery";
    public String id() {
        return CiscoIOSXRSysadminAaaDisasterRecovery.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-aaa-disaster-recovery";
    public String uri() {
        return CiscoIOSXRSysadminAaaDisasterRecovery.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRSysadminAaaDisasterRecovery.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-sysadmin-aaa-disaster-recovery";
    public String prefix() {
        return CiscoIOSXRSysadminAaaDisasterRecovery.prefix;
    }

    public CiscoIOSXRSysadminAaaDisasterRecovery() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _username = 870658415;
    public static final String _username_ = "username";
    public static final int    _disaster_recovery = 2089420129;
    public static final String _disaster_recovery_ = "disaster-recovery";
    public static final int    _password = 880727685;
    public static final String _password_ = "password";
}
