/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-infra-confcopymib-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-infra-confcopymib-cfg.yang */
public class CiscoIOSXRInfraConfcopymibCfg extends ConfNamespace {
    public static final int hash = 938784336;
    public int hash() {
        return CiscoIOSXRInfraConfcopymibCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-confcopymib-cfg";
    public String id() {
        return CiscoIOSXRInfraConfcopymibCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-confcopymib-cfg";
    public String uri() {
        return CiscoIOSXRInfraConfcopymibCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRInfraConfcopymibCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-infra-confcopymib-cfg";
    public String prefix() {
        return CiscoIOSXRInfraConfcopymibCfg.prefix;
    }

    public CiscoIOSXRInfraConfcopymibCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _completion = 1369481076;
    public static final String _completion_ = "completion";
    public static final int    _config_copy = 95041048;
    public static final String _config_copy_ = "config-copy";
}
