/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-crypto-act.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-crypto-act.yang */
public class CiscoIOSXRCryptoAct extends ConfNamespace {
    public static final int hash = 1533670067;
    public int hash() {
        return CiscoIOSXRCryptoAct.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-crypto-act";
    public String id() {
        return CiscoIOSXRCryptoAct.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-crypto-act";
    public String uri() {
        return CiscoIOSXRCryptoAct.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRCryptoAct.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-crypto-act";
    public String prefix() {
        return CiscoIOSXRCryptoAct.prefix;
    }

    public CiscoIOSXRCryptoAct() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _key_generate_rsa_usage_keys = 557951729;
    public static final String _key_generate_rsa_usage_keys_ = "key-generate-rsa-usage-keys";
    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _key_generate_ecdsa = 1303200634;
    public static final String _key_generate_ecdsa_ = "key-generate-ecdsa";
    public static final int    _rpc_key_import_authentication_rsa = 1779401070;
    public static final String _rpc_key_import_authentication_rsa_ = "rpc-key-import-authentication-rsa";
    public static final int    _ca_trustpool_import_url = 1267282735;
    public static final String _ca_trustpool_import_url_ = "ca-trustpool-import-url";
    public static final int    _ca_enroll = 1567840650;
    public static final String _ca_enroll_ = "ca-enroll";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _rpc_ca_authenticate = 1111078072;
    public static final String _rpc_ca_authenticate_ = "rpc-ca-authenticate";
    public static final int    _rpc_ca_trustpool_import_url = 1611079287;
    public static final String _rpc_ca_trustpool_import_url_ = "rpc-ca-trustpool-import-url";
    public static final int    _rpc_ca_import_certificate = 464131847;
    public static final String _rpc_ca_import_certificate_ = "rpc-ca-import-certificate";
    public static final int    _ca_trustpool_import_url_clean = 1115771205;
    public static final String _ca_trustpool_import_url_clean_ = "ca-trustpool-import-url-clean";
    public static final int    _key_generate_rsa_general_keys = 2086134677;
    public static final String _key_generate_rsa_general_keys_ = "key-generate-rsa-general-keys";
    public static final int    _server_name = 1912911616;
    public static final String _server_name_ = "server-name";
    public static final int    _rpc_key_zeroize_rsa = 1307007149;
    public static final String _rpc_key_zeroize_rsa_ = "rpc-key-zeroize-rsa";
    public static final int    _rpc_key_generate_dsa = 615566480;
    public static final String _rpc_key_generate_dsa_ = "rpc-key-generate-dsa";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _key_modulus = 21686476;
    public static final String _key_modulus_ = "key-modulus";
    public static final int    _ca_import_certificate = 41395568;
    public static final String _ca_import_certificate_ = "ca-import-certificate";
    public static final int    _rpc_key_zeroize_authentication_rsa = 879695243;
    public static final String _rpc_key_zeroize_authentication_rsa_ = "rpc-key-zeroize-authentication-rsa";
    public static final int    _key_label = 1475693758;
    public static final String _key_label_ = "key-label";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _key_generate_rsa = 591308909;
    public static final String _key_generate_rsa_ = "key-generate-rsa";
    public static final int    _url = 1560781157;
    public static final String _url_ = "url";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _rpc_ca_trustpool_import_url_clean = 97830509;
    public static final String _rpc_ca_trustpool_import_url_clean_ = "rpc-ca-trustpool-import-url-clean";
    public static final int    _ca_authenticate = 1005830483;
    public static final String _ca_authenticate_ = "ca-authenticate";
    public static final int    _rpc_key_generate_rsa_general_keys = 720103466;
    public static final String _rpc_key_generate_rsa_general_keys_ = "rpc-key-generate-rsa-general-keys";
    public static final int    _rpc_ca_enroll = 713410403;
    public static final String _rpc_ca_enroll_ = "rpc-ca-enroll";
    public static final int    _key_zeroize_rsa = 2049523248;
    public static final String _key_zeroize_rsa_ = "key-zeroize-rsa";
    public static final int    _rpc_ca_cancel_enroll = 1886717618;
    public static final String _rpc_ca_cancel_enroll_ = "rpc-ca-cancel-enroll";
    public static final int    _key_generate_dsa = 1375015948;
    public static final String _key_generate_dsa_ = "key-generate-dsa";
    public static final int    _uri = 1237918064;
    public static final String _uri_ = "uri";
    public static final int    _rpc_ca_crl_request = 861784944;
    public static final String _rpc_ca_crl_request_ = "rpc-ca-crl-request";
    public static final int    _certificate = 929395308;
    public static final String _certificate_ = "certificate";
    public static final int    _key_zeroize_ecdsa = 785221648;
    public static final String _key_zeroize_ecdsa_ = "key-zeroize-ecdsa";
    public static final int    _ca_crl_request = 542374571;
    public static final String _ca_crl_request_ = "ca-crl-request";
    public static final int    _rpc_key_generate_ecdsa = 1650408475;
    public static final String _rpc_key_generate_ecdsa_ = "rpc-key-generate-ecdsa";
    public static final int    _rpc_key_generate_rsa = 1897219148;
    public static final String _rpc_key_generate_rsa_ = "rpc-key-generate-rsa";
    public static final int    _ca_cancel_enroll = 663911162;
    public static final String _ca_cancel_enroll_ = "ca-cancel-enroll";
    public static final int    _rpc_key_zeroize_ecdsa = 822429278;
    public static final String _rpc_key_zeroize_ecdsa_ = "rpc-key-zeroize-ecdsa";
    public static final int    _rpc_key_generate_rsa_usage_keys = 1772593759;
    public static final String _rpc_key_generate_rsa_usage_keys_ = "rpc-key-generate-rsa-usage-keys";
    public static final int    _key_import_authentication_rsa = 804100618;
    public static final String _key_import_authentication_rsa_ = "key-import-authentication-rsa";
    public static final int    _key_zeroize_dsa = 1056648556;
    public static final String _key_zeroize_dsa_ = "key-zeroize-dsa";
    public static final int    _rpc_key_zeroize_dsa = 883238905;
    public static final String _rpc_key_zeroize_dsa_ = "rpc-key-zeroize-dsa";
    public static final int    _key_zeroize_authentication_rsa = 1788711478;
    public static final String _key_zeroize_authentication_rsa_ = "key-zeroize-authentication-rsa";
}
