/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-segment-routing-srv6-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-segment-routing-srv6-oper.yang */
public class CiscoIOSXRSegmentRoutingSrv6Oper extends ConfNamespace {
    public static final int hash = 808512733;
    public int hash() {
        return CiscoIOSXRSegmentRoutingSrv6Oper.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-segment-routing-srv6-oper";
    public String id() {
        return CiscoIOSXRSegmentRoutingSrv6Oper.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-segment-routing-srv6-oper";
    public String uri() {
        return CiscoIOSXRSegmentRoutingSrv6Oper.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRSegmentRoutingSrv6Oper.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-segment-routing-srv6-oper";
    public String prefix() {
        return CiscoIOSXRSegmentRoutingSrv6Oper.prefix;
    }

    public CiscoIOSXRSegmentRoutingSrv6Oper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _max_t_insert = 1092533200;
    public static final String _max_t_insert_ = "max-t-insert";
    public static final int    _locators_count = 35314367;
    public static final String _locators_count_ = "locators-count";
    public static final int    _prefix = 1408440115;
    public static final String _prefix_ = "prefix";
    public static final int    _oor_red_count = 1156981994;
    public static final String _oor_red_count_ = "oor-red-count";
    public static final int    _is_default = 1064074143;
    public static final String _is_default_ = "is-default";
    public static final int    _transit_func = 1114171361;
    public static final String _transit_func_ = "transit-func";
    public static final int    _security_rule = 1601326349;
    public static final String _security_rule_ = "security-rule";
    public static final int    _max_t_encap = 1133130679;
    public static final String _max_t_encap_ = "max-t-encap";
    public static final int    _locator_all_stale_sids = 133561354;
    public static final String _locator_all_stale_sids_ = "locator-all-stale-sids";
    public static final int    _locators = 428766852;
    public static final String _locators_ = "locators";
    public static final int    _platform_capabilities = 1682539001;
    public static final String _platform_capabilities_ = "platform-capabilities";
    public static final int    _dx4 = 514947819;
    public static final String _dx4_ = "dx4";
    public static final int    _do_propagate = 59351711;
    public static final String _do_propagate_ = "do-propagate";
    public static final int    _sid_opcode = 1564433854;
    public static final String _sid_opcode_ = "sid-opcode";
    public static final int    _sids_out_of_resource_summary = 572627178;
    public static final String _sids_out_of_resource_summary_ = "sids-out-of-resource-summary";
    public static final int    _max_end_pop_srh = 175487027;
    public static final String _max_end_pop_srh_ = "max-end-pop-srh";
    public static final int    _sids = 1159055095;
    public static final String _sids_ = "sids";
    public static final int    _configured_encap_source_address = 1122587123;
    public static final String _configured_encap_source_address_ = "configured-encap-source-address";
    public static final int    _locator_name = 248760057;
    public static final String _locator_name_ = "locator-name";
    public static final int    _tilfa = 1675407514;
    public static final String _tilfa_ = "tilfa";
    public static final int    _counter = 393786077;
    public static final String _counter_ = "counter";
    public static final int    _is_operational = 352715564;
    public static final String _is_operational_ = "is-operational";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _x = 1735967608;
    public static final String _x_ = "x";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _end_func = 136027539;
    public static final String _end_func_ = "end-func";
    public static final int    _default_encap_source_address = 1656956240;
    public static final String _default_encap_source_address_ = "default-encap-source-address";
    public static final int    _out_of_resources_state = 2108045088;
    public static final String _out_of_resources_state_ = "out-of-resources-state";
    public static final int    _sid_holdtime_mins_configured = 376697771;
    public static final String _sid_holdtime_mins_configured_ = "sid-holdtime-mins-configured";
    public static final int    _info = 2062105651;
    public static final String _info_ = "info";
    public static final int    _opaque_id = 804491636;
    public static final String _opaque_id_ = "opaque-id";
    public static final int    _locator_all_sids = 2126402790;
    public static final String _locator_all_sids_ = "locator-all-sids";
    public static final int    _locator_all_active_sids = 784817098;
    public static final String _locator_all_active_sids_ = "locator-all-active-sids";
    public static final int    _has_forwarding = 95934279;
    public static final String _has_forwarding_ = "has-forwarding";
    public static final int    _srv6 = 888264735;
    public static final String _srv6_ = "srv6";
    public static final int    _locator = 1707118576;
    public static final String _locator_ = "locator";
    public static final int    _support = 1748628145;
    public static final String _support_ = "support";
    public static final int    _encap_hop_limit = 384040824;
    public static final String _encap_hop_limit_ = "encap-hop-limit";
    public static final int    _max_sid = 1354119474;
    public static final String _max_sid_ = "max-sid";
    public static final int    _locator_all_active_sid = 999079176;
    public static final String _locator_all_active_sid_ = "locator-all-active-sid";
    public static final int    _next_hop_set_id = 130839251;
    public static final String _next_hop_set_id_ = "next-hop-set-id";
    public static final int    _sid = 1233827376;
    public static final String _sid_ = "sid";
    public static final int    _allocation_type = 1794499626;
    public static final String _allocation_type_ = "allocation-type";
    public static final int    _signaled_parameters = 305603277;
    public static final String _signaled_parameters_ = "signaled-parameters";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _e = 942517958;
    public static final String _e_ = "e";
    public static final int    _sid_holdtime_mins = 1249591216;
    public static final String _sid_holdtime_mins_ = "sid-holdtime-mins";
    public static final int    _sids_count = 2114145837;
    public static final String _sids_count_ = "sids-count";
    public static final int    _standby = 1180054629;
    public static final String _standby_ = "standby";
    public static final int    _programmed_prefix = 1051585003;
    public static final String _programmed_prefix_ = "programmed-prefix";
    public static final int    _if_handle = 1605443421;
    public static final String _if_handle_ = "if-handle";
    public static final int    _stale_sids_count = 676397339;
    public static final String _stale_sids_count_ = "stale-sids-count";
    public static final int    _sid_context_type = 1017700718;
    public static final String _sid_context_type_ = "sid-context-type";
    public static final int    _oor_green_count = 654870146;
    public static final String _oor_green_count_ = "oor-green-count";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _is_sid_holdtime_configured = 138769533;
    public static final String _is_sid_holdtime_configured_ = "is-sid-holdtime-configured";
    public static final int    _sid_context = 727532517;
    public static final String _sid_context_ = "sid-context";
    public static final int    _age_in_nano_seconds = 1984058762;
    public static final String _age_in_nano_seconds_ = "age-in-nano-seconds";
    public static final int    _function_type = 1492127628;
    public static final String _function_type_ = "function-type";
    public static final int    _sid_mgr_summary = 2116717590;
    public static final String _sid_mgr_summary_ = "sid-mgr-summary";
    public static final int    _is_protected = 408341140;
    public static final String _is_protected_ = "is-protected";
    public static final int    _maximum_sids_count = 1360090221;
    public static final String _maximum_sids_count_ = "maximum-sids-count";
    public static final int    _encap_ttl_propagate = 1643077779;
    public static final String _encap_ttl_propagate_ = "encap-ttl-propagate";
    public static final int    _string = 777087657;
    public static final String _string_ = "string";
    public static final int    _sid_mgr_params = 475938344;
    public static final String _sid_mgr_params_ = "sid-mgr-params";
    public static final int    _use_default = 233565453;
    public static final String _use_default_ = "use-default";
    public static final int    _locator_all_sid = 443752781;
    public static final String _locator_all_sid_ = "locator-all-sid";
    public static final int    _create_timestamp = 73303722;
    public static final String _create_timestamp_ = "create-timestamp";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _dt4 = 660259470;
    public static final String _dt4_ = "dt4";
    public static final int    _oor_yellow_free_sid_threshold = 1317894920;
    public static final String _oor_yellow_free_sid_threshold_ = "oor-yellow-free-sid-threshold";
    public static final int    _application_data = 1122074421;
    public static final String _application_data_ = "application-data";
    public static final int    _srv6_enabled = 889320293;
    public static final String _srv6_enabled_ = "srv6-enabled";
    public static final int    _oor_yellow_count = 888894715;
    public static final String _oor_yellow_count_ = "oor-yellow-count";
    public static final int    _nexthop_address = 1007389772;
    public static final String _nexthop_address_ = "nexthop-address";
    public static final int    _manager = 1171954147;
    public static final String _manager_ = "manager";
    public static final int    _max_sl = 274049369;
    public static final String _max_sl_ = "max-sl";
    public static final int    _oor_green_free_sid_threshold = 1449329267;
    public static final String _oor_green_free_sid_threshold_ = "oor-green-free-sid-threshold";
    public static final int    _oper_locators_count = 1545386836;
    public static final String _oper_locators_count_ = "oper-locators-count";
    public static final int    _max_end_d = 1826992902;
    public static final String _max_end_d_ = "max-end-d";
    public static final int    _owner = 206925960;
    public static final String _owner_ = "owner";
    public static final int    _key = 1348858669;
    public static final String _key_ = "key";
    public static final int    _locator_all_stale_sid = 1641072747;
    public static final String _locator_all_stale_sid_ = "locator-all-stale-sid";
    public static final int    _time_in_nano_seconds = 535772027;
    public static final String _time_in_nano_seconds_ = "time-in-nano-seconds";
    public static final int    _table_id = 1778037522;
    public static final String _table_id_ = "table-id";
    public static final int    _microloop_avoidance = 735844775;
    public static final String _microloop_avoidance_ = "microloop-avoidance";
    public static final int    _active = 124277386;
    public static final String _active_ = "active";
}
