/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-aaa-diameter-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-aaa-diameter-cfg.yang */
public class CiscoIOSXRAaaDiameterCfg extends ConfNamespace {
    public static final int hash = 1423672148;
    public int hash() {
        return CiscoIOSXRAaaDiameterCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-diameter-cfg";
    public String id() {
        return CiscoIOSXRAaaDiameterCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-diameter-cfg";
    public String uri() {
        return CiscoIOSXRAaaDiameterCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRAaaDiameterCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-aaa-diameter-cfg";
    public String prefix() {
        return CiscoIOSXRAaaDiameterCfg.prefix;
    }

    public CiscoIOSXRAaaDiameterCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _services = 284312249;
    public static final String _services_ = "services";
    public static final int    _tls_transport = 1817515484;
    public static final String _tls_transport_ = "tls-transport";
    public static final int    _vodafone = 930750933;
    public static final String _vodafone_ = "vodafone";
    public static final int    _diam = 386010231;
    public static final String _diam_ = "diam";
    public static final int    _transaction = 343661117;
    public static final String _transaction_ = "transaction";
    public static final int    _ipv6_address = 731894850;
    public static final String _ipv6_address_ = "ipv6-address";
    public static final int    _gy = 411336549;
    public static final String _gy_ = "gy";
    public static final int    _list_id = 1924007994;
    public static final String _list_id_ = "list-id";
    public static final int    _server_group_name = 179688880;
    public static final String _server_group_name_ = "server-group-name";
    public static final int    _origin = 2002579816;
    public static final String _origin_ = "origin";
    public static final int    _service = 855380710;
    public static final String _service_ = "service";
    public static final int    _peers = 958391453;
    public static final String _peers_ = "peers";
    public static final int    _peer_name = 1574148750;
    public static final String _peer_name_ = "peer-name";
    public static final int    _realm = 1974128942;
    public static final String _realm_ = "realm";
    public static final int    _supported = 138078235;
    public static final String _supported_ = "supported";
    public static final int    _etsi = 2138759341;
    public static final String _etsi_ = "etsi";
    public static final int    _type_ipv4_address = 1378204206;
    public static final String _type_ipv4_address_ = "type-ipv4-address";
    public static final int    _monitoring_key = 731418339;
    public static final String _monitoring_key_ = "monitoring-key";
    public static final int    _diameter_tls = 1068299576;
    public static final String _diameter_tls_ = "diameter-tls";
    public static final int    _threegpp = 1188507552;
    public static final String _threegpp_ = "threegpp";
    public static final int    _retransmit = 2032283843;
    public static final String _retransmit_ = "retransmit";
    public static final int    _mandatory = 1842133828;
    public static final String _mandatory_ = "mandatory";
    public static final int    _diameter_timer = 111910449;
    public static final String _diameter_timer_ = "diameter-timer";
    public static final int    _ipv4_address = 400734928;
    public static final String _ipv4_address_ = "ipv4-address";
    public static final int    _diameter_server_groups = 1694165621;
    public static final String _diameter_server_groups_ = "diameter-server-groups";
    public static final int    _cisco = 1531121168;
    public static final String _cisco_ = "cisco";
    public static final int    _attribute_id = 87080267;
    public static final String _attribute_id_ = "attribute-id";
    public static final int    _vrf_ip = 568075891;
    public static final String _vrf_ip_ = "vrf-ip";
    public static final int    _type_grouped = 1436503150;
    public static final String _type_grouped_ = "type-grouped";
    public static final int    _type_enum = 205664486;
    public static final String _type_enum_ = "type-enum";
    public static final int    _peer = 1450174230;
    public static final String _peer_ = "peer";
    public static final int    _ordering_index = 1251256028;
    public static final String _ordering_index_ = "ordering-index";
    public static final int    _type_identity = 386755050;
    public static final String _type_identity_ = "type-identity";
    public static final int    _tcp_transport = 1147399327;
    public static final String _tcp_transport_ = "tcp-transport";
    public static final int    _dest_host = 314673953;
    public static final String _dest_host_ = "dest-host";
    public static final int    _watchdog = 1352410101;
    public static final String _watchdog_ = "watchdog";
    public static final int    _service_name = 916440695;
    public static final String _service_name_ = "service-name";
    public static final int    _type_boolean = 461065117;
    public static final String _type_boolean_ = "type-boolean";
    public static final int    _diam_attr_value = 833016690;
    public static final String _diam_attr_value_ = "diam-attr-value";
    public static final int    _host_destination = 207626585;
    public static final String _host_destination_ = "host-destination";
    public static final int    _host = 1711485895;
    public static final String _host_ = "host";
    public static final int    _diam_attr_defs = 629244361;
    public static final String _diam_attr_defs_ = "diam-attr-defs";
    public static final int    _gx = 1913081508;
    public static final String _gx_ = "gx";
    public static final int    _vendor_id = 1357446;
    public static final String _vendor_id_ = "vendor-id";
    public static final int    _trustpoint = 565575895;
    public static final String _trustpoint_ = "trustpoint";
    public static final int    _type_string = 749921523;
    public static final String _type_string_ = "type-string";
    public static final int    _type_binary = 67488163;
    public static final String _type_binary_ = "type-binary";
    public static final int    _peer_timer = 81428283;
    public static final String _peer_timer_ = "peer-timer";
    public static final int    _type_ulong = 958154593;
    public static final String _type_ulong_ = "type-ulong";
    public static final int    _type_utc = 991951159;
    public static final String _type_utc_ = "type-utc";
    public static final int    _data_type = 1483232353;
    public static final String _data_type_ = "data-type";
    public static final int    _servers = 1403078918;
    public static final String _servers_ = "servers";
    public static final int    _connection = 1134114300;
    public static final String _connection_ = "connection";
    public static final int    _diameter = 1652729834;
    public static final String _diameter_ = "diameter";
    public static final int    _nas = 371020630;
    public static final String _nas_ = "nas";
    public static final int    _type_ulonglong = 1876812602;
    public static final String _type_ulonglong_ = "type-ulonglong";
    public static final int    _realm_destination = 1350696754;
    public static final String _realm_destination_ = "realm-destination";
    public static final int    _diam_attr_def = 426829057;
    public static final String _diam_attr_def_ = "diam-attr-def";
    public static final int    _vendor = 1639541835;
    public static final String _vendor_ = "vendor";
    public static final int    _tx_timer = 1075177754;
    public static final String _tx_timer_ = "tx-timer";
    public static final int    _diams = 981069317;
    public static final String _diams_ = "diams";
    public static final int    _peer_type = 1801912036;
    public static final String _peer_type_ = "peer-type";
    public static final int    _server = 163548884;
    public static final String _server_ = "server";
    public static final int    _diameter_server_group = 1038897940;
    public static final String _diameter_server_group_ = "diameter-server-group";
    public static final int    _source_interface = 1180772123;
    public static final String _source_interface_ = "source-interface";
}
