/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-segment-routing-ms-common-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-segment-routing-ms-common-cfg.yang */
public class CiscoIOSXRSegmentRoutingMsCommonCfg extends ConfNamespace {
    public static final int hash = 1736963465;
    public int hash() {
        return CiscoIOSXRSegmentRoutingMsCommonCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-segment-routing-ms-common-cfg";
    public String id() {
        return CiscoIOSXRSegmentRoutingMsCommonCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-segment-routing-ms-common-cfg";
    public String uri() {
        return CiscoIOSXRSegmentRoutingMsCommonCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRSegmentRoutingMsCommonCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-segment-routing-ms-common-cfg";
    public String prefix() {
        return CiscoIOSXRSegmentRoutingMsCommonCfg.prefix;
    }

    public CiscoIOSXRSegmentRoutingMsCommonCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _sr = 68535015;
    public static final String _sr_ = "sr";
}
