/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-ipv4-mfwd-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-ipv4-mfwd-cfg.yang */
public class CiscoIOSXRIpv4MfwdCfg extends ConfNamespace {
    public static final int hash = 1882365920;
    public int hash() {
        return CiscoIOSXRIpv4MfwdCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-mfwd-cfg";
    public String id() {
        return CiscoIOSXRIpv4MfwdCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-mfwd-cfg";
    public String uri() {
        return CiscoIOSXRIpv4MfwdCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRIpv4MfwdCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-ipv4-mfwd-cfg";
    public String prefix() {
        return CiscoIOSXRIpv4MfwdCfg.prefix;
    }

    public CiscoIOSXRIpv4MfwdCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _log_traps = 691469040;
    public static final String _log_traps_ = "log-traps";
    public static final int    _static_rpf_rules = 412595821;
    public static final String _static_rpf_rules_ = "static-rpf-rules";
    public static final int    _default_context = 1713376183;
    public static final String _default_context_ = "default-context";
    public static final int    _forwarding_latency = 1696994218;
    public static final String _forwarding_latency_ = "forwarding-latency";
    public static final int    _prefix_mask = 884595077;
    public static final String _prefix_mask_ = "prefix-mask";
    public static final int    _mfwd = 1687169949;
    public static final String _mfwd_ = "mfwd";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _mofrr_lockout_timer_config = 710995723;
    public static final String _mofrr_lockout_timer_config_ = "mofrr-lockout-timer-config";
    public static final int    _out_of_memory_handling = 1784459568;
    public static final String _out_of_memory_handling_ = "out-of-memory-handling";
    public static final int    _vrf = 1281310328;
    public static final String _vrf_ = "vrf";
    public static final int    _maximum_checking_disable = 1962483785;
    public static final String _maximum_checking_disable_ = "maximum-checking-disable";
    public static final int    _enable_on_all_interfaces = 1000865253;
    public static final String _enable_on_all_interfaces_ = "enable-on-all-interfaces";
    public static final int    _rate_per_route = 908290223;
    public static final String _rate_per_route_ = "rate-per-route";
    public static final int    _interface_name = 1322899300;
    public static final String _interface_name_ = "interface-name";
    public static final int    _vrf_name = 2140916904;
    public static final String _vrf_name_ = "vrf-name";
    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _multicast_forwarding = 1486470667;
    public static final String _multicast_forwarding_ = "multicast-forwarding";
    public static final int    _ipv6 = 1228132394;
    public static final String _ipv6_ = "ipv6";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _static_rpf_rule = 1054300156;
    public static final String _static_rpf_rule_ = "static-rpf-rule";
    public static final int    _ttl_threshold = 1121497846;
    public static final String _ttl_threshold_ = "ttl-threshold";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _boundary = 216476823;
    public static final String _boundary_ = "boundary";
    public static final int    _interface_inheritance_disable = 135556960;
    public static final String _interface_inheritance_disable_ = "interface-inheritance-disable";
    public static final int    _neighbor_address = 1654322417;
    public static final String _neighbor_address_ = "neighbor-address";
    public static final int    _enable_on_interface = 1427912919;
    public static final String _enable_on_interface_ = "enable-on-interface";
    public static final int    _vrfs = 777611836;
    public static final String _vrfs_ = "vrfs";
    public static final int    _mofrr_loss_detection_timer_config = 447276737;
    public static final String _mofrr_loss_detection_timer_config_ = "mofrr-loss-detection-timer-config";
    public static final int    _accounting = 803748480;
    public static final String _accounting_ = "accounting";
}
