/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-shellutil-filesystem-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-shellutil-filesystem-oper.yang */
public class CiscoIOSXRShellutilFilesystemOper extends ConfNamespace {
    public static final int hash = 1900974887;
    public int hash() {
        return CiscoIOSXRShellutilFilesystemOper.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-shellutil-filesystem-oper";
    public String id() {
        return CiscoIOSXRShellutilFilesystemOper.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-shellutil-filesystem-oper";
    public String uri() {
        return CiscoIOSXRShellutilFilesystemOper.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRShellutilFilesystemOper.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-shellutil-filesystem-oper";
    public String prefix() {
        return CiscoIOSXRShellutilFilesystemOper.prefix;
    }

    public CiscoIOSXRShellutilFilesystemOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _size = 1649058097;
    public static final String _size_ = "size";
    public static final int    _free = 274122866;
    public static final String _free_ = "free";
    public static final int    _node_name = 122353445;
    public static final String _node_name_ = "node-name";
    public static final int    _file_system = 545013653;
    public static final String _file_system_ = "file-system";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _prefixes = 1405994391;
    public static final String _prefixes_ = "prefixes";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
    public static final int    _flags = 1646628167;
    public static final String _flags_ = "flags";
}
