/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-pbr-bng-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-pbr-bng-cfg.yang */
public class CiscoIOSXRPbrBngCfg extends ConfNamespace {
    public static final int hash = 2054755380;
    public int hash() {
        return CiscoIOSXRPbrBngCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-pbr-bng-cfg";
    public String id() {
        return CiscoIOSXRPbrBngCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-pbr-bng-cfg";
    public String uri() {
        return CiscoIOSXRPbrBngCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRPbrBngCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-pbr-bng-cfg";
    public String prefix() {
        return CiscoIOSXRPbrBngCfg.prefix;
    }

    public CiscoIOSXRPbrBngCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _http_enrichment = 1047290942;
    public static final String _http_enrichment_ = "http-enrichment";
    public static final int    _arg1 = 79740565;
    public static final String _arg1_ = "arg1";
    public static final int    _arg3 = 498974064;
    public static final String _arg3_ = "arg3";
    public static final int    _bng_pbr = 284320092;
    public static final String _bng_pbr_ = "bng-pbr";
    public static final int    _parameters = 716273249;
    public static final String _parameters_ = "parameters";
    public static final int    _arg2 = 1721732759;
    public static final String _arg2_ = "arg2";
    public static final int    _arg4 = 252968179;
    public static final String _arg4_ = "arg4";
    public static final int    _bng_interface = 1140141348;
    public static final String _bng_interface_ = "bng-interface";
}
