/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-ethernet-cfm-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-ethernet-cfm-cfg.yang */
public class CiscoIOSXREthernetCfmCfg extends ConfNamespace {
    public static final int hash = 1134485895;
    public int hash() {
        return CiscoIOSXREthernetCfmCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ethernet-cfm-cfg";
    public String id() {
        return CiscoIOSXREthernetCfmCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ethernet-cfm-cfg";
    public String uri() {
        return CiscoIOSXREthernetCfmCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXREthernetCfmCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-ethernet-cfm-cfg";
    public String prefix() {
        return CiscoIOSXREthernetCfmCfg.prefix;
    }

    public CiscoIOSXREthernetCfmCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _services = 284312249;
    public static final String _services_ = "services";
    public static final int    _profiles = 1374722363;
    public static final String _profiles_ = "profiles";
    public static final int    _probe_duration_unit = 1421946184;
    public static final String _probe_duration_unit_ = "probe-duration-unit";
    public static final int    _ethernet = 766975154;
    public static final String _ethernet_ = "ethernet";
    public static final int    _mdid_mac_address = 408723394;
    public static final String _mdid_mac_address_ = "mdid-mac-address";
    public static final int    _log_ais = 20644475;
    public static final String _log_ais_ = "log-ais";
    public static final int    _protection_switching_enable = 1357963646;
    public static final String _protection_switching_enable_ = "protection-switching-enable";
    public static final int    _statistic = 1274844247;
    public static final String _statistic_ = "statistic";
    public static final int    _ais = 1481128129;
    public static final String _ais_ = "ais";
    public static final int    _start_time_hour = 48773702;
    public static final String _start_time_hour_ = "start-time-hour";
    public static final int    _probe_interval = 2021872257;
    public static final String _probe_interval_ = "probe-interval";
    public static final int    _mdid_format = 1880315378;
    public static final String _mdid_format_ = "mdid-format";
    public static final int    _bins_width_tenths = 1941309226;
    public static final String _bins_width_tenths_ = "bins-width-tenths";
    public static final int    _target_mac_address = 903086577;
    public static final String _target_mac_address_ = "target-mac-address";
    public static final int    _log_cross_check_errors = 826803409;
    public static final String _log_cross_check_errors_ = "log-cross-check-errors";
    public static final int    _log_continuity_check_errors = 2095010588;
    public static final String _log_continuity_check_errors_ = "log-continuity-check-errors";
    public static final int    _threshold_value = 1520366978;
    public static final String _threshold_value_ = "threshold-value";
    public static final int    _priority = 1346277862;
    public static final String _priority_ = "priority";
    public static final int    _service_type = 1145594576;
    public static final String _service_type_ = "service-type";
    public static final int    _short_ma_name_format = 430741721;
    public static final String _short_ma_name_format_ = "short-ma-name-format";
    public static final int    _cos7 = 311832713;
    public static final String _cos7_ = "cos7";
    public static final int    _service = 855380710;
    public static final String _service_ = "service";
    public static final int    _service_properties = 489330835;
    public static final String _service_properties_ = "service-properties";
    public static final int    _padding_value = 2130069200;
    public static final String _padding_value_ = "padding-value";
    public static final int    _sla_profile_target_mep_ids = 1468306156;
    public static final String _sla_profile_target_mep_ids_ = "sla-profile-target-mep-ids";
    public static final int    _mip_policy = 2099565269;
    public static final String _mip_policy_ = "mip-policy";
    public static final int    _threshold_type = 1049344081;
    public static final String _threshold_type_ = "threshold-type";
    public static final int    _cross_check = 1057155983;
    public static final String _cross_check_ = "cross-check";
    public static final int    _synthetic_loss_calculation_packets = 287684405;
    public static final String _synthetic_loss_calculation_packets_ = "synthetic-loss-calculation-packets";
    public static final int    _switching_name = 82144387;
    public static final String _switching_name_ = "switching-name";
    public static final int    _ccm_interval = 1826152211;
    public static final String _ccm_interval_ = "ccm-interval";
    public static final int    _cos4 = 624645456;
    public static final String _cos4_ = "cos4";
    public static final int    _packet_interval_unit = 545989869;
    public static final String _packet_interval_unit_ = "packet-interval-unit";
    public static final int    _action = 571883887;
    public static final String _action_ = "action";
    public static final int    _enable_mac_address = 878933106;
    public static final String _enable_mac_address_ = "enable-mac-address";
    public static final int    _profile = 1538168517;
    public static final String _profile_ = "profile";
    public static final int    _loss_measurement_counters = 537534646;
    public static final String _loss_measurement_counters_ = "loss-measurement-counters";
    public static final int    _mep = 723575678;
    public static final String _mep_ = "mep";
    public static final int    _mep_id = 1263886304;
    public static final String _mep_id_ = "mep-id";
    public static final int    _action_type = 731500332;
    public static final String _action_type_ = "action-type";
    public static final int    _short_ma_name_vpn_index = 2095590438;
    public static final String _short_ma_name_vpn_index_ = "short-ma-name-vpn-index";
    public static final int    _evi = 13525485;
    public static final String _evi_ = "evi";
    public static final int    _packet_size_and_padding = 2135352252;
    public static final String _packet_size_and_padding_ = "packet-size-and-padding";
    public static final int    _mdid_number = 1665887373;
    public static final String _mdid_number_ = "mdid-number";
    public static final int    _mac_address = 2110689796;
    public static final String _mac_address_ = "mac-address";
    public static final int    _sla_profile_target_mep_id = 363220143;
    public static final String _sla_profile_target_mep_id_ = "sla-profile-target-mep-id";
    public static final int    _cross_check_mep = 982303302;
    public static final String _cross_check_mep_ = "cross-check-mep";
    public static final int    _enable = 448570367;
    public static final String _enable_ = "enable";
    public static final int    _mep_properties = 1865920489;
    public static final String _mep_properties_ = "mep-properties";
    public static final int    _packet_type = 1712646039;
    public static final String _packet_type_ = "packet-type";
    public static final int    _buckets_size = 907457776;
    public static final String _buckets_size_ = "buckets-size";
    public static final int    _tags = 1477116560;
    public static final String _tags_ = "tags";
    public static final int    _packet_interval = 800907816;
    public static final String _packet_interval_ = "packet-interval";
    public static final int    _size = 1649058097;
    public static final String _size_ = "size";
    public static final int    _condition = 1305639641;
    public static final String _condition_ = "condition";
    public static final int    _mdid_string = 1848639385;
    public static final String _mdid_string_ = "mdid-string";
    public static final int    _schedule = 1642863984;
    public static final String _schedule_ = "schedule";
    public static final int    _cos = 762246620;
    public static final String _cos_ = "cos";
    public static final int    _burst_interval = 618209564;
    public static final String _burst_interval_ = "burst-interval";
    public static final int    _probe_duration = 1055229922;
    public static final String _probe_duration_ = "probe-duration";
    public static final int    _cos1 = 584655999;
    public static final String _cos1_ = "cos1";
    public static final int    _level = 2112619197;
    public static final String _level_ = "level";
    public static final int    _start_time_second = 1839873496;
    public static final String _start_time_second_ = "start-time-second";
    public static final int    _cache_size = 441658549;
    public static final String _cache_size_ = "cache-size";
    public static final int    _short_ma_name_oui = 2140533210;
    public static final String _short_ma_name_oui_ = "short-ma-name-oui";
    public static final int    _cos3 = 1626852221;
    public static final String _cos3_ = "cos3";
    public static final int    _burst_interval_unit = 95625240;
    public static final String _burst_interval_unit_ = "burst-interval-unit";
    public static final int    _continuity_check_interval = 2088276712;
    public static final String _continuity_check_interval_ = "continuity-check-interval";
    public static final int    _bins_width = 1017837885;
    public static final String _bins_width_ = "bins-width";
    public static final int    _statistics = 1049034618;
    public static final String _statistics_ = "statistics";
    public static final int    _packet_count = 1421200306;
    public static final String _packet_count_ = "packet-count";
    public static final int    _domain_properties = 182448490;
    public static final String _domain_properties_ = "domain-properties";
    public static final int    _continuity_check_auto_traceroute = 89207183;
    public static final String _continuity_check_auto_traceroute_ = "continuity-check-auto-traceroute";
    public static final int    _bins_count = 566494277;
    public static final String _bins_count_ = "bins-count";
    public static final int    _maximum_meps = 714334038;
    public static final String _maximum_meps_ = "maximum-meps";
    public static final int    _cos0 = 1864263392;
    public static final String _cos0_ = "cos0";
    public static final int    _buckets_archive = 640996605;
    public static final String _buckets_archive_ = "buckets-archive";
    public static final int    _cfm = 1069899056;
    public static final String _cfm_ = "cfm";
    public static final int    _cos2 = 739232254;
    public static final String _cos2_ = "cos2";
    public static final int    _domain = 2003714718;
    public static final String _domain_ = "domain";
    public static final int    _auto = 1146214388;
    public static final String _auto_ = "auto";
    public static final int    _log_continuity_check_state_changes = 1738669488;
    public static final String _log_continuity_check_state_changes_ = "log-continuity-check-state-changes";
    public static final int    _hold_time = 204730640;
    public static final String _hold_time_ = "hold-time";
    public static final int    _cross_check_meps = 551690044;
    public static final String _cross_check_meps_ = "cross-check-meps";
    public static final int    _mip_auto_creation = 2043149005;
    public static final String _mip_auto_creation_ = "mip-auto-creation";
    public static final int    _ais_interval = 1360529252;
    public static final String _ais_interval_ = "ais-interval";
    public static final int    _transmission = 1309153612;
    public static final String _transmission_ = "transmission";
    public static final int    _ccm_learning_enable = 899029529;
    public static final String _ccm_learning_enable_ = "ccm-learning-enable";
    public static final int    _domains = 1371013494;
    public static final String _domains_ = "domains";
    public static final int    _padding_type = 1199917325;
    public static final String _padding_type_ = "padding-type";
    public static final int    _short_ma_name_umc = 1340095922;
    public static final String _short_ma_name_umc_ = "short-ma-name-umc";
    public static final int    _cfg_type = 1613233402;
    public static final String _cfg_type_ = "cfg-type";
    public static final int    _traceroute_cache = 1877709330;
    public static final String _traceroute_cache_ = "traceroute-cache";
    public static final int    _target_mep_id = 1925703778;
    public static final String _target_mep_id_ = "target-mep-id";
    public static final int    _remote_ce_id = 687376290;
    public static final String _remote_ce_id_ = "remote-ce-id";
    public static final int    _send_type = 1758090573;
    public static final String _send_type_ = "send-type";
    public static final int    _buckets_size_unit = 628382302;
    public static final String _buckets_size_unit_ = "buckets-size-unit";
    public static final int    _cos6 = 1876894153;
    public static final String _cos6_ = "cos6";
    public static final int    _ais_up = 1497948382;
    public static final String _ais_up_ = "ais-up";
    public static final int    _probe_interval_day = 1468398877;
    public static final String _probe_interval_day_ = "probe-interval-day";
    public static final int    _probe = 1118433712;
    public static final String _probe_ = "probe";
    public static final int    _probe_interval_unit = 1141095705;
    public static final String _probe_interval_unit_ = "probe-interval-unit";
    public static final int    _cos5 = 2084727040;
    public static final String _cos5_ = "cos5";
    public static final int    _group_name = 331590344;
    public static final String _group_name_ = "group-name";
    public static final int    _log_efd = 1961603682;
    public static final String _log_efd_ = "log-efd";
    public static final int    _sla_profile_target_mac_address = 628587772;
    public static final String _sla_profile_target_mac_address_ = "sla-profile-target-mac-address";
    public static final int    _nv_satellite_sla_processing_disable = 139819594;
    public static final String _nv_satellite_sla_processing_disable_ = "nv-satellite-sla-processing-disable";
    public static final int    _efd2 = 1367003681;
    public static final String _efd2_ = "efd2";
    public static final int    _profile_name = 1763461054;
    public static final String _profile_name_ = "profile-name";
    public static final int    _short_ma_name_number = 1227881197;
    public static final String _short_ma_name_number_ = "short-ma-name-number";
    public static final int    _send = 1238787519;
    public static final String _send_ = "send";
    public static final int    _short_ma_name_string = 668168029;
    public static final String _short_ma_name_string_ = "short-ma-name-string";
    public static final int    _continuity_check_archive_hold_time = 34110883;
    public static final String _continuity_check_archive_hold_time_ = "continuity-check-archive-hold-time";
    public static final int    _short_ma_name_icc = 1499087661;
    public static final String _short_ma_name_icc_ = "short-ma-name-icc";
    public static final int    _bin_number = 1310663157;
    public static final String _bin_number_ = "bin-number";
    public static final int    _ce_id = 172699787;
    public static final String _ce_id_ = "ce-id";
    public static final int    _start_time_minute = 1943979479;
    public static final String _start_time_minute_ = "start-time-minute";
    public static final int    _actions = 2034878685;
    public static final String _actions_ = "actions";
    public static final int    _aggregation = 640445680;
    public static final String _aggregation_ = "aggregation";
    public static final int    _statistic_name = 707859328;
    public static final String _statistic_name_ = "statistic-name";
    public static final int    _loss_threshold = 1781721081;
    public static final String _loss_threshold_ = "loss-threshold";
}
