/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-ip-iarm-datatypes.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-ip-iarm-datatypes.yang */
public class CiscoIOSXRIpIarmDatatypes extends ConfNamespace {
    public static final int hash = 1224115198;
    public int hash() {
        return CiscoIOSXRIpIarmDatatypes.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-iarm-datatypes";
    public String id() {
        return CiscoIOSXRIpIarmDatatypes.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-iarm-datatypes";
    public String uri() {
        return CiscoIOSXRIpIarmDatatypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRIpIarmDatatypes.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-ip-iarm-datatypes";
    public String prefix() {
        return CiscoIOSXRIpIarmDatatypes.prefix;
    }

    public CiscoIOSXRIpIarmDatatypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
