/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-otnifmib-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-otnifmib-cfg.yang */
public class CiscoIOSXROtnifmibCfg extends ConfNamespace {
    public static final int hash = 2129824095;
    public int hash() {
        return CiscoIOSXROtnifmibCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-otnifmib-cfg";
    public String id() {
        return CiscoIOSXROtnifmibCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-otnifmib-cfg";
    public String uri() {
        return CiscoIOSXROtnifmibCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXROtnifmibCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-otnifmib-cfg";
    public String prefix() {
        return CiscoIOSXROtnifmibCfg.prefix;
    }

    public CiscoIOSXROtnifmibCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _enable = 448570367;
    public static final String _enable_ = "enable";
    public static final int    _otn = 432742433;
    public static final String _otn_ = "otn";
}
