/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-ipv4-msdp-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-ipv4-msdp-cfg.yang */
public class CiscoIOSXRIpv4MsdpCfg extends ConfNamespace {
    public static final int hash = 1992949279;
    public int hash() {
        return CiscoIOSXRIpv4MsdpCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-msdp-cfg";
    public String id() {
        return CiscoIOSXRIpv4MsdpCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-msdp-cfg";
    public String uri() {
        return CiscoIOSXRIpv4MsdpCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRIpv4MsdpCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-ipv4-msdp-cfg";
    public String prefix() {
        return CiscoIOSXRIpv4MsdpCfg.prefix;
    }

    public CiscoIOSXRIpv4MsdpCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _connect_source = 1186441322;
    public static final String _connect_source_ = "connect-source";
    public static final int    _sa_filters = 1826079598;
    public static final String _sa_filters_ = "sa-filters";
    public static final int    _max_sa = 2030125102;
    public static final String _max_sa_ = "max-sa";
    public static final int    _global_max_sa = 986572725;
    public static final String _global_max_sa_ = "global-max-sa";
    public static final int    _default_context = 1713376183;
    public static final String _default_context_ = "default-context";
    public static final int    _keep_alive = 649483949;
    public static final String _keep_alive_ = "keep-alive";
    public static final int    _peer_timeout_period = 546514025;
    public static final String _peer_timeout_period_ = "peer-timeout-period";
    public static final int    _nsr_delay = 667143722;
    public static final String _nsr_delay_ = "nsr-delay";
    public static final int    _sa_holdtime = 2074676998;
    public static final String _sa_holdtime_ = "sa-holdtime";
    public static final int    _peers = 958391453;
    public static final String _peers_ = "peers";
    public static final int    _msdp = 56807041;
    public static final String _msdp_ = "msdp";
    public static final int    _sa_filter = 513282117;
    public static final String _sa_filter_ = "sa-filter";
    public static final int    _vrf = 1281310328;
    public static final String _vrf_ = "vrf";
    public static final int    _enable = 448570367;
    public static final String _enable_ = "enable";
    public static final int    _shutdown = 460723287;
    public static final String _shutdown_ = "shutdown";
    public static final int    _as_yy = 800638899;
    public static final String _as_yy_ = "as-yy";
    public static final int    _peer = 1450174230;
    public static final String _peer_ = "peer";
    public static final int    _peer_address = 2130238605;
    public static final String _peer_address_ = "peer-address";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _vrf_name = 2140916904;
    public static final String _vrf_name_ = "vrf-name";
    public static final int    _default_peer = 38723936;
    public static final String _default_peer_ = "default-peer";
    public static final int    _max_peer_sa = 1851104943;
    public static final String _max_peer_sa_ = "max-peer-sa";
    public static final int    _keep_alive_period = 2131067317;
    public static final String _keep_alive_period_ = "keep-alive-period";
    public static final int    _filter_type = 820859681;
    public static final String _filter_type_ = "filter-type";
    public static final int    _list = 1015076401;
    public static final String _list_ = "list";
    public static final int    _rp_list = 2021510911;
    public static final String _rp_list_ = "rp-list";
    public static final int    _mesh_group = 33444955;
    public static final String _mesh_group_ = "mesh-group";
    public static final int    _remote_as = 81986873;
    public static final String _remote_as_ = "remote-as";
    public static final int    _ttl_threshold = 1121497846;
    public static final String _ttl_threshold_ = "ttl-threshold";
    public static final int    _access_list_name = 337693690;
    public static final String _access_list_name_ = "access-list-name";
    public static final int    _peer_password = 308343504;
    public static final String _peer_password_ = "peer-password";
    public static final int    _vrfs = 777611836;
    public static final String _vrfs_ = "vrfs";
    public static final int    _as_xx = 340094348;
    public static final String _as_xx_ = "as-xx";
    public static final int    _cache_state = 84105238;
    public static final String _cache_state_ = "cache-state";
    public static final int    _nsr_down = 857993819;
    public static final String _nsr_down_ = "nsr-down";
    public static final int    _originator_id = 919533201;
    public static final String _originator_id_ = "originator-id";
}
