/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-ip-rsvp-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-ip-rsvp-cfg.yang */
public class CiscoIOSXRIpRsvpCfg extends ConfNamespace {
    public static final int hash = 213570386;
    public int hash() {
        return CiscoIOSXRIpRsvpCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-rsvp-cfg";
    public String id() {
        return CiscoIOSXRIpRsvpCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-rsvp-cfg";
    public String uri() {
        return CiscoIOSXRIpRsvpCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRIpRsvpCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-ip-rsvp-cfg";
    public String prefix() {
        return CiscoIOSXRIpRsvpCfg.prefix;
    }

    public CiscoIOSXRIpRsvpCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _refresh_reduction = 2126949630;
    public static final String _refresh_reduction_ = "refresh-reduction";
    public static final int    _global_bandwidth = 657660094;
    public static final String _global_bandwidth_ = "global-bandwidth";
    public static final int    _reliable_s_refresh = 326082658;
    public static final String _reliable_s_refresh_ = "reliable-s-refresh";
    public static final int    _drop = 414370175;
    public static final String _drop_ = "drop";
    public static final int    _prefix_filtering = 1970487489;
    public static final String _prefix_filtering_ = "prefix-filtering";
    public static final int    _neighbors = 1478644450;
    public static final String _neighbors_ = "neighbors";
    public static final int    _rdm_keyword = 327741511;
    public static final String _rdm_keyword_ = "rdm-keyword";
    public static final int    _messages_per_interval = 1738266381;
    public static final String _messages_per_interval_ = "messages-per-interval";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _controller = 1295630195;
    public static final String _controller_ = "controller";
    public static final int    _lsp_class_type = 2140557346;
    public static final String _lsp_class_type_ = "lsp-class-type";
    public static final int    _summary_max_size = 2101492505;
    public static final String _summary_max_size_ = "summary-max-size";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _reliable_ack_hold_time = 2129465405;
    public static final String _reliable_ack_hold_time_ = "reliable-ack-hold-time";
    public static final int    _reliable_retransmit_time = 1489535202;
    public static final String _reliable_retransmit_time_ = "reliable-retransmit-time";
    public static final int    _bundle_message_max_size = 629657708;
    public static final String _bundle_message_max_size_ = "bundle-message-max-size";
    public static final int    _max_resv_bandwidth = 1787772797;
    public static final String _max_resv_bandwidth_ = "max-resv-bandwidth";
    public static final int    _bc1_percent = 1920667023;
    public static final String _bc1_percent_ = "bc1-percent";
    public static final int    _vrf = 1281310328;
    public static final String _vrf_ = "vrf";
    public static final int    _interval_size = 1378561694;
    public static final String _interval_size_ = "interval-size";
    public static final int    _default_deny_action = 553393516;
    public static final String _default_deny_action_ = "default-deny-action";
    public static final int    _rsvp = 236944791;
    public static final String _rsvp_ = "rsvp";
    public static final int    _global_out_of_band = 418519475;
    public static final String _global_out_of_band_ = "global-out-of-band";
    public static final int    _enable = 448570367;
    public static final String _enable_ = "enable";
    public static final int    _refresh_interval = 1650191759;
    public static final String _refresh_interval_ = "refresh-interval";
    public static final int    _recovery_time = 1853262293;
    public static final String _recovery_time_ = "recovery-time";
    public static final int    _controllers = 1302107053;
    public static final String _controllers_ = "controllers";
    public static final int    _out_of_band = 1476073179;
    public static final String _out_of_band_ = "out-of-band";
    public static final int    _acl = 994927724;
    public static final String _acl_ = "acl";
    public static final int    _pesr = 823573092;
    public static final String _pesr_ = "pesr";
    public static final int    _max_resv_flow = 17765076;
    public static final String _max_resv_flow_ = "max-resv-flow";
    public static final int    _new_flow = 908674727;
    public static final String _new_flow_ = "new-flow";
    public static final int    _default_interface_percent = 1746422034;
    public static final String _default_interface_percent_ = "default-interface-percent";
    public static final int    _neighbor = 81789621;
    public static final String _neighbor_ = "neighbor";
    public static final int    _authentication = 838318934;
    public static final String _authentication_ = "authentication";
    public static final int    _hello_graceful_restart_if_based = 1399472921;
    public static final String _hello_graceful_restart_if_based_ = "hello-graceful-restart-if-based";
    public static final int    _window_size = 1923856794;
    public static final String _window_size_ = "window-size";
    public static final int    _missed_messages = 766821777;
    public static final String _missed_messages_ = "missed-messages";
    public static final int    _max_res_percent = 448813786;
    public static final String _max_res_percent_ = "max-res-percent";
    public static final int    _checksum = 522825528;
    public static final String _checksum_ = "checksum";
    public static final int    _bc1_bandwidth = 745833859;
    public static final String _bc1_bandwidth_ = "bc1-bandwidth";
    public static final int    _bc1_keyword = 292988782;
    public static final String _bc1_keyword_ = "bc1-keyword";
    public static final int    _graceful_restart = 298735851;
    public static final String _graceful_restart_ = "graceful-restart";
    public static final int    _signalling = 1462136096;
    public static final String _signalling_ = "signalling";
    public static final int    _hello_graceful_restart_interval = 1218379463;
    public static final String _hello_graceful_restart_interval_ = "hello-graceful-restart-interval";
    public static final int    _life_time = 779042068;
    public static final String _life_time_ = "life-time";
    public static final int    _global_logging = 680587748;
    public static final String _global_logging_ = "global-logging";
    public static final int    _reliable_ack_max_size = 1990008288;
    public static final String _reliable_ack_max_size_ = "reliable-ack-max-size";
    public static final int    _dscp = 1118112132;
    public static final String _dscp_ = "dscp";
    public static final int    _pacing = 33425422;
    public static final String _pacing_ = "pacing";
    public static final int    _disable = 330763859;
    public static final String _disable_ = "disable";
    public static final int    _controller_name = 2147097453;
    public static final String _controller_name_ = "controller-name";
    public static final int    _rdm = 1042085990;
    public static final String _rdm_ = "rdm";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _bandwidth = 82191353;
    public static final String _bandwidth_ = "bandwidth";
    public static final int    _bandwidth_mode = 1284741132;
    public static final String _bandwidth_mode_ = "bandwidth-mode";
    public static final int    _mam = 1857134695;
    public static final String _mam_ = "mam";
    public static final int    _cntl_signalling = 396853614;
    public static final String _cntl_signalling_ = "cntl-signalling";
    public static final int    _lost_flow = 1478241171;
    public static final String _lost_flow_ = "lost-flow";
    public static final int    _bc0_keyword = 422734684;
    public static final String _bc0_keyword_ = "bc0-keyword";
    public static final int    _log_issu_status = 1945780890;
    public static final String _log_issu_status_ = "log-issu-status";
    public static final int    _hello_graceful_restart_misses = 681505581;
    public static final String _hello_graceful_restart_misses_ = "hello-graceful-restart-misses";
    public static final int    _if_signalling = 1330672839;
    public static final String _if_signalling_ = "if-signalling";
    public static final int    _key_chain = 1359335192;
    public static final String _key_chain_ = "key-chain";
    public static final int    _restart_time = 493265707;
    public static final String _restart_time_ = "restart-time";
    public static final int    _log_nsr_status = 1907224194;
    public static final String _log_nsr_status_ = "log-nsr-status";
    public static final int    _bc0_bandwidth = 786670088;
    public static final String _bc0_bandwidth_ = "bc0-bandwidth";
    public static final int    _bc0_percent = 1302648870;
    public static final String _bc0_percent_ = "bc0-percent";
    public static final int    _interval_rate = 134115707;
    public static final String _interval_rate_ = "interval-rate";
}
