/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-lpts-pre-ifib-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-lpts-pre-ifib-cfg.yang */
public class CiscoIOSXRLptsPreIfibCfg extends ConfNamespace {
    public static final int hash = 1248745835;
    public int hash() {
        return CiscoIOSXRLptsPreIfibCfg.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-lpts-pre-ifib-cfg";
    public String id() {
        return CiscoIOSXRLptsPreIfibCfg.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-lpts-pre-ifib-cfg";
    public String uri() {
        return CiscoIOSXRLptsPreIfibCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRLptsPreIfibCfg.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-lpts-pre-ifib-cfg";
    public String prefix() {
        return CiscoIOSXRLptsPreIfibCfg.prefix;
    }

    public CiscoIOSXRLptsPreIfibCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _precedence = 387047676;
    public static final String _precedence_ = "precedence";
    public static final int    _id1 = 483547059;
    public static final String _id1_ = "id1";
    public static final int    _afi_family_type = 1749303434;
    public static final String _afi_family_type_ = "afi-family-type";
    public static final int    _ipolicer_local_tables = 19385701;
    public static final String _ipolicer_local_tables_ = "ipolicer-local-tables";
    public static final int    _vrf_names = 285816383;
    public static final String _vrf_names_ = "vrf-names";
    public static final int    _afi_types = 2009001238;
    public static final String _afi_types_ = "afi-types";
    public static final int    _lpts_local = 1797626295;
    public static final String _lpts_local_ = "lpts-local";
    public static final int    _np_flows = 1418870123;
    public static final String _np_flows_ = "np-flows";
    public static final int    _ipolicer = 1880241447;
    public static final String _ipolicer_ = "ipolicer";
    public static final int    _table_type = 477529893;
    public static final String _table_type_ = "table-type";
    public static final int    _afi_type = 1172082095;
    public static final String _afi_type_ = "afi-type";
    public static final int    _flows = 1866960985;
    public static final String _flows_ = "flows";
    public static final int    _max = 2088175689;
    public static final String _max_ = "max";
    public static final int    _precedences = 1341430008;
    public static final String _precedences_ = "precedences";
    public static final int    _enable = 448570367;
    public static final String _enable_ = "enable";
    public static final int    _np_flow = 298533847;
    public static final String _np_flow_ = "np-flow";
    public static final int    _ipolicer_local_table = 1621379382;
    public static final String _ipolicer_local_table_ = "ipolicer-local-table";
    public static final int    _acl = 994927724;
    public static final String _acl_ = "acl";
    public static final int    _ipolicer_local = 1672375803;
    public static final String _ipolicer_local_ = "ipolicer-local";
    public static final int    _np_rate = 956631097;
    public static final String _np_rate_ = "np-rate";
    public static final int    _acl_rate = 185493653;
    public static final String _acl_rate_ = "acl-rate";
    public static final int    _vrf_name = 2140916904;
    public static final String _vrf_name_ = "vrf-name";
    public static final int    _acls = 1901716470;
    public static final String _acls_ = "acls";
    public static final int    _dynamic_flows_table = 1651360605;
    public static final String _dynamic_flows_table_ = "dynamic-flows-table";
    public static final int    _dynamic_flows_tables = 719240225;
    public static final String _dynamic_flows_tables_ = "dynamic-flows-tables";
    public static final int    _flow_type = 157184229;
    public static final String _flow_type_ = "flow-type";
    public static final int    _flow = 2144387363;
    public static final String _flow_ = "flow";
    public static final int    _rate = 834972967;
    public static final String _rate_ = "rate";
    public static final int    _acl_name = 377722430;
    public static final String _acl_name_ = "acl-name";
}
