/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-sysadmin-show-trace.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-sysadmin-show-trace.yang */
public class CiscoIOSXRSysadminShowTrace extends ConfNamespace {
    public static final int hash = 481317864;
    public int hash() {
        return CiscoIOSXRSysadminShowTrace.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-show-trace";
    public String id() {
        return CiscoIOSXRSysadminShowTrace.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-show-trace";
    public String uri() {
        return CiscoIOSXRSysadminShowTrace.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRSysadminShowTrace.uri);
    }

    public static final String prefix = "Cisco-IOS-XR-sysadmin-show-trace";
    public String prefix() {
        return CiscoIOSXRSysadminShowTrace.prefix;
    }

    public CiscoIOSXRSysadminShowTrace() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
