/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/notifications.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module notifications.yang */
public class notifications extends ConfNamespace {
    public static final int hash = 235501857;
    public int hash() {
        return notifications.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#urn:ietf:params:xml:ns:netconf:notification:1.0";
    public String id() {
        return notifications.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#urn:ietf:params:xml:ns:netconf:notification:1.0";
    public String uri() {
        return notifications.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(notifications.uri);
    }

    public static final String prefix = "notifications";
    public String prefix() {
        return notifications.prefix;
    }

    public notifications() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _stream = 1561687317;
    public static final String _stream_ = "stream";
    public static final int    _startTime = 1171093796;
    public static final String _startTime_ = "startTime";
    public static final int    _filter = 518848087;
    public static final String _filter_ = "filter";
    public static final int    _create_subscription = 568965842;
    public static final String _create_subscription_ = "create-subscription";
    public static final int    _stopTime = 1619644201;
    public static final String _stopTime_ = "stopTime";
    public static final int    _rpc_create_subscription = 1729875037;
    public static final String _rpc_create_subscription_ = "rpc-create-subscription";
}
