/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/opertest1.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.f5500.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module opertest1.yang */
public class opertest1 extends ConfNamespace {
    public static final int hash = 1589500356;
    public int hash() {
        return opertest1.hash;
    }

    public static final String id = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/panini/calvados/opertest1";
    public String id() {
        return opertest1.id;
    }

    public static final String uri = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/panini/calvados/opertest1";
    public String uri() {
        return opertest1.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(opertest1.uri);
    }

    public static final String prefix = "opertest1";
    public String prefix() {
        return opertest1.prefix;
    }

    public opertest1() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _wilma = 1547717117;
    public static final String _wilma_ = "wilma";
    public static final int    _loadavg1min = 1206213463;
    public static final String _loadavg1min_ = "loadavg1min";
    public static final int    _idle = 647299899;
    public static final String _idle_ = "idle";
    public static final int    _betty = 1010605478;
    public static final String _betty_ = "betty";
    public static final int    _BamBam = 1284821510;
    public static final String _BamBam_ = "BamBam";
    public static final int    _release = 1325681236;
    public static final String _release_ = "release";
    public static final int    _curtime = 1178658297;
    public static final String _curtime_ = "curtime";
    public static final int    _fred = 2090886062;
    public static final String _fred_ = "fred";
    public static final int    _barney = 1703220295;
    public static final String _barney_ = "barney";
    public static final int    _location = 1827424758;
    public static final String _location_ = "location";
    public static final int    _when = 60139460;
    public static final String _when_ = "when";
    public static final int    _graceful = 498026961;
    public static final String _graceful_ = "graceful";
    public static final int    _version = 1714291735;
    public static final String _version_ = "version";
    public static final int    _chatty = 1008285660;
    public static final String _chatty_ = "chatty";
    public static final int    _loadavg15min = 389680078;
    public static final String _loadavg15min_ = "loadavg15min";
    public static final int    _pcpu = 973665704;
    public static final String _pcpu_ = "pcpu";
    public static final int    _uname = 915327512;
    public static final String _uname_ = "uname";
    public static final int    _all = 2031982792;
    public static final String _all_ = "all";
    public static final int    _mrslate = 370859245;
    public static final String _mrslate_ = "mrslate";
    public static final int    _machine = 1472449276;
    public static final String _machine_ = "machine";
    public static final int    _users = 987101583;
    public static final String _users_ = "users";
    public static final int    _tty = 2034439888;
    public static final String _tty_ = "tty";
    public static final int    _login_at = 318274984;
    public static final String _login_at_ = "login-at";
    public static final int    _nodename = 896115764;
    public static final String _nodename_ = "nodename";
    public static final int    _slates = 1809522774;
    public static final String _slates_ = "slates";
    public static final int    _from = 261037251;
    public static final String _from_ = "from";
    public static final int    _user = 1529217067;
    public static final String _user_ = "user";
    public static final int    _uptime = 1268395647;
    public static final String _uptime_ = "uptime";
    public static final int    _system = 1534086422;
    public static final String _system_ = "system";
    public static final int    _loadavg5min = 656080007;
    public static final String _loadavg5min_ = "loadavg5min";
    public static final int    _what = 1988393839;
    public static final String _what_ = "what";
    public static final int    _oper = 1313484953;
    public static final String _oper_ = "oper";
    public static final int    _jcpu = 998015271;
    public static final String _jcpu_ = "jcpu";
    public static final int    _w = 483213922;
    public static final String _w_ = "w";
    public static final int    _header_info = 1636755273;
    public static final String _header_info_ = "header-info";
    public static final int    _slatenum = 1376864976;
    public static final String _slatenum_ = "slatenum";
    public static final int    _actions = 2034878685;
    public static final String _actions_ = "actions";
}
