#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-ipv4-dc-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-ipv4-dc-cfg.yang


class ns(object):
    hash = 1255579715

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-dc-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-dc-cfg"

    prefix = "Cisco-IOS-XR-ipv4-dc-cfg"

    Cisco_IOS_XR_ipv4_dc_cfg_option60 = 60
    Cisco_IOS_XR_ipv4_dc_cfg_option60_ = "option60"
    Cisco_IOS_XR_ipv4_dc_cfg_option61_config = 625340496
    Cisco_IOS_XR_ipv4_dc_cfg_option61_config_ = "option61-config"
    Cisco_IOS_XR_ipv4_dc_cfg_opt61 = 276047272
    Cisco_IOS_XR_ipv4_dc_cfg_opt61_ = "opt61"
    Cisco_IOS_XR_ipv4_dc_cfg_enable = 448570367
    Cisco_IOS_XR_ipv4_dc_cfg_enable_ = "enable"
    Cisco_IOS_XR_ipv4_dc_cfg_subtype = 1955371587
    Cisco_IOS_XR_ipv4_dc_cfg_subtype_ = "subtype"
    Cisco_IOS_XR_ipv4_dc_cfg_ipv4_dhcp_client = 1227974516
    Cisco_IOS_XR_ipv4_dc_cfg_ipv4_dhcp_client_ = "ipv4-dhcp-client"
    Cisco_IOS_XR_ipv4_dc_cfg_ascii_string = 2147086265
    Cisco_IOS_XR_ipv4_dc_cfg_ascii_string_ = "ascii-string"
    Cisco_IOS_XR_ipv4_dc_cfg_ipv4_dhcp_client_config = 1533795582
    Cisco_IOS_XR_ipv4_dc_cfg_ipv4_dhcp_client_config_ = "ipv4-dhcp-client-config"
    Cisco_IOS_XR_ipv4_dc_cfg_option60_config = 1528949968
    Cisco_IOS_XR_ipv4_dc_cfg_option60_config_ = "option60-config"
    Cisco_IOS_XR_ipv4_dc_cfg_opt60 = 1969682637
    Cisco_IOS_XR_ipv4_dc_cfg_opt60_ = "opt60"
    Cisco_IOS_XR_ipv4_dc_cfg_opt77 = 979244493
    Cisco_IOS_XR_ipv4_dc_cfg_opt77_ = "opt77"
    Cisco_IOS_XR_ipv4_dc_cfg_option61 = 61
    Cisco_IOS_XR_ipv4_dc_cfg_option61_ = "option61"
    Cisco_IOS_XR_ipv4_dc_cfg_option77_config = 1471871633
    Cisco_IOS_XR_ipv4_dc_cfg_option77_config_ = "option77-config"
    Cisco_IOS_XR_ipv4_dc_cfg_option77 = 77
    Cisco_IOS_XR_ipv4_dc_cfg_option77_ = "option77"
    Cisco_IOS_XR_ipv4_dc_cfg_sn_chassis = 3
    Cisco_IOS_XR_ipv4_dc_cfg_sn_chassis_ = "sn-chassis"
    Cisco_IOS_XR_ipv4_dc_cfg_ascii = 1
    Cisco_IOS_XR_ipv4_dc_cfg_ascii_ = "ascii"
