#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-aaa-locald-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-aaa-locald-oper.yang


class ns(object):
    hash = 48578797

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-locald-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-locald-oper"

    prefix = "Cisco-IOS-XR-aaa-locald-oper"

    Cisco_IOS_XR_aaa_locald_oper_debug = 189210324
    Cisco_IOS_XR_aaa_locald_oper_debug_ = "debug"
    Cisco_IOS_XR_aaa_locald_oper_lock_out_count = 1164378723
    Cisco_IOS_XR_aaa_locald_oper_lock_out_count_ = "lock-out-count"
    Cisco_IOS_XR_aaa_locald_oper_secs = 1492743858
    Cisco_IOS_XR_aaa_locald_oper_secs_ = "secs"
    Cisco_IOS_XR_aaa_locald_oper_task_map = 175692104
    Cisco_IOS_XR_aaa_locald_oper_task_map_ = "task-map"
    Cisco_IOS_XR_aaa_locald_oper_all_tasks = 1070651511
    Cisco_IOS_XR_aaa_locald_oper_all_tasks_ = "all-tasks"
    Cisco_IOS_XR_aaa_locald_oper_currentuser_detail = 1468090842
    Cisco_IOS_XR_aaa_locald_oper_currentuser_detail_ = "currentuser-detail"
    Cisco_IOS_XR_aaa_locald_oper_write = 1725969642
    Cisco_IOS_XR_aaa_locald_oper_write_ = "write"
    Cisco_IOS_XR_aaa_locald_oper_taskmap = 2012461823
    Cisco_IOS_XR_aaa_locald_oper_taskmap_ = "taskmap"
    Cisco_IOS_XR_aaa_locald_oper_name = 1998270519
    Cisco_IOS_XR_aaa_locald_oper_name_ = "name"
    Cisco_IOS_XR_aaa_locald_oper_lower_case = 2067965431
    Cisco_IOS_XR_aaa_locald_oper_lower_case_ = "lower-case"
    Cisco_IOS_XR_aaa_locald_oper_min_char_change = 179262887
    Cisco_IOS_XR_aaa_locald_oper_min_char_change_ = "min-char-change"
    Cisco_IOS_XR_aaa_locald_oper_shelltype = 988129188
    Cisco_IOS_XR_aaa_locald_oper_shelltype_ = "shelltype"
    Cisco_IOS_XR_aaa_locald_oper_aaa = 2073600231
    Cisco_IOS_XR_aaa_locald_oper_aaa_ = "aaa"
    Cisco_IOS_XR_aaa_locald_oper_years = 370194567
    Cisco_IOS_XR_aaa_locald_oper_years_ = "years"
    Cisco_IOS_XR_aaa_locald_oper_current_usergroup = 1165461832
    Cisco_IOS_XR_aaa_locald_oper_current_usergroup_ = "current-usergroup"
    Cisco_IOS_XR_aaa_locald_oper_task_id = 728396339
    Cisco_IOS_XR_aaa_locald_oper_task_id_ = "task-id"
    Cisco_IOS_XR_aaa_locald_oper_months = 1049422562
    Cisco_IOS_XR_aaa_locald_oper_months_ = "months"
    Cisco_IOS_XR_aaa_locald_oper_authen_method = 701537855
    Cisco_IOS_XR_aaa_locald_oper_authen_method_ = "authen-method"
    Cisco_IOS_XR_aaa_locald_oper_min_len = 920321301
    Cisco_IOS_XR_aaa_locald_oper_min_len_ = "min-len"
    Cisco_IOS_XR_aaa_locald_oper_included_task_ids = 77528494
    Cisco_IOS_XR_aaa_locald_oper_included_task_ids_ = "included-task-ids"
    Cisco_IOS_XR_aaa_locald_oper_password_policies = 566857062
    Cisco_IOS_XR_aaa_locald_oper_password_policies_ = "password-policies"
    Cisco_IOS_XR_aaa_locald_oper_read = 726939083
    Cisco_IOS_XR_aaa_locald_oper_read_ = "read"
    Cisco_IOS_XR_aaa_locald_oper_lock_out_time = 987896326
    Cisco_IOS_XR_aaa_locald_oper_lock_out_time_ = "lock-out-time"
    Cisco_IOS_XR_aaa_locald_oper_directory = 702978347
    Cisco_IOS_XR_aaa_locald_oper_directory_ = "directory"
    Cisco_IOS_XR_aaa_locald_oper_execute = 688425184
    Cisco_IOS_XR_aaa_locald_oper_execute_ = "execute"
    Cisco_IOS_XR_aaa_locald_oper_usergroup = 21302503
    Cisco_IOS_XR_aaa_locald_oper_usergroup_ = "usergroup"
    Cisco_IOS_XR_aaa_locald_oper_users = 987101583
    Cisco_IOS_XR_aaa_locald_oper_users_ = "users"
    Cisco_IOS_XR_aaa_locald_oper_numeric = 1901932170
    Cisco_IOS_XR_aaa_locald_oper_numeric_ = "numeric"
    Cisco_IOS_XR_aaa_locald_oper_usergroups = 1395730825
    Cisco_IOS_XR_aaa_locald_oper_usergroups_ = "usergroups"
    Cisco_IOS_XR_aaa_locald_oper_upper_case = 1346203255
    Cisco_IOS_XR_aaa_locald_oper_upper_case_ = "upper-case"
    Cisco_IOS_XR_aaa_locald_oper_taskgroup = 188540953
    Cisco_IOS_XR_aaa_locald_oper_taskgroup_ = "taskgroup"
    Cisco_IOS_XR_aaa_locald_oper_usr_count = 1119627033
    Cisco_IOS_XR_aaa_locald_oper_usr_count_ = "usr-count"
    Cisco_IOS_XR_aaa_locald_oper_max_fail_attempts = 1198790611
    Cisco_IOS_XR_aaa_locald_oper_max_fail_attempts_ = "max-fail-attempts"
    Cisco_IOS_XR_aaa_locald_oper_days = 723976734
    Cisco_IOS_XR_aaa_locald_oper_days_ = "days"
    Cisco_IOS_XR_aaa_locald_oper_password_policy = 1514027161
    Cisco_IOS_XR_aaa_locald_oper_password_policy_ = "password-policy"
    Cisco_IOS_XR_aaa_locald_oper_life_time = 779042068
    Cisco_IOS_XR_aaa_locald_oper_life_time_ = "life-time"
    Cisco_IOS_XR_aaa_locald_oper_taskgroups = 1099527357
    Cisco_IOS_XR_aaa_locald_oper_taskgroups_ = "taskgroups"
    Cisco_IOS_XR_aaa_locald_oper_max_len = 303565139
    Cisco_IOS_XR_aaa_locald_oper_max_len_ = "max-len"
    Cisco_IOS_XR_aaa_locald_oper_num_of_users = 2135473183
    Cisco_IOS_XR_aaa_locald_oper_num_of_users_ = "num-of-users"
    Cisco_IOS_XR_aaa_locald_oper_user = 1529217067
    Cisco_IOS_XR_aaa_locald_oper_user_ = "user"
    Cisco_IOS_XR_aaa_locald_oper_authenmethod = 1666923749
    Cisco_IOS_XR_aaa_locald_oper_authenmethod_ = "authenmethod"
    Cisco_IOS_XR_aaa_locald_oper_err_count = 815145739
    Cisco_IOS_XR_aaa_locald_oper_err_count_ = "err-count"
    Cisco_IOS_XR_aaa_locald_oper_spl_char = 1649713105
    Cisco_IOS_XR_aaa_locald_oper_spl_char_ = "spl-char"
    Cisco_IOS_XR_aaa_locald_oper_tasks = 1116697604
    Cisco_IOS_XR_aaa_locald_oper_tasks_ = "tasks"
    Cisco_IOS_XR_aaa_locald_oper_mins = 851180712
    Cisco_IOS_XR_aaa_locald_oper_mins_ = "mins"
    Cisco_IOS_XR_aaa_locald_oper_hours = 1625129637
    Cisco_IOS_XR_aaa_locald_oper_hours_ = "hours"
    Cisco_IOS_XR_aaa_locald_oper_admin_user = 1426207300
    Cisco_IOS_XR_aaa_locald_oper_admin_user_ = "admin-user"
    Cisco_IOS_XR_aaa_locald_oper_first_user = 156942528
    Cisco_IOS_XR_aaa_locald_oper_first_user_ = "first-user"
