#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-pbr-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-pbr-oper.yang


class ns(object):
    hash = 636011992

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-pbr-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-pbr-oper"

    prefix = "Cisco-IOS-XR-pbr-oper"

    Cisco_IOS_XR_pbr_oper_drop_bytes = 1204285872
    Cisco_IOS_XR_pbr_oper_drop_bytes_ = "drop-bytes"
    Cisco_IOS_XR_pbr_oper_tcp_sent_packets = 2140836904
    Cisco_IOS_XR_pbr_oper_tcp_sent_packets_ = "tcp-sent-packets"
    Cisco_IOS_XR_pbr_oper_pbr = 117061436
    Cisco_IOS_XR_pbr_oper_pbr_ = "pbr"
    Cisco_IOS_XR_pbr_oper_class_id = 2024237442
    Cisco_IOS_XR_pbr_oper_class_id_ = "class-id"
    Cisco_IOS_XR_pbr_oper_http_enrich_stats = 345813922
    Cisco_IOS_XR_pbr_oper_http_enrich_stats_ = "http-enrich-stats"
    Cisco_IOS_XR_pbr_oper_total_transmit_rate = 1707412986
    Cisco_IOS_XR_pbr_oper_total_transmit_rate_ = "total-transmit-rate"
    Cisco_IOS_XR_pbr_oper_interface = 221572658
    Cisco_IOS_XR_pbr_oper_interface_ = "interface"
    Cisco_IOS_XR_pbr_oper_policy_map = 5517311
    Cisco_IOS_XR_pbr_oper_policy_map_ = "policy-map"
    Cisco_IOS_XR_pbr_oper_req_sent_packets = 1777408019
    Cisco_IOS_XR_pbr_oper_req_sent_packets_ = "req-sent-packets"
    Cisco_IOS_XR_pbr_oper_rqst_rcvd_bytes = 298676728
    Cisco_IOS_XR_pbr_oper_rqst_rcvd_bytes_ = "rqst-rcvd-bytes"
    Cisco_IOS_XR_pbr_oper_suspended = 1
    Cisco_IOS_XR_pbr_oper_suspended_ = "suspended"
    Cisco_IOS_XR_pbr_oper_state_description = 944865688
    Cisco_IOS_XR_pbr_oper_state_description_ = "state-description"
    Cisco_IOS_XR_pbr_oper_class_name = 1124630539
    Cisco_IOS_XR_pbr_oper_class_name_ = "class-name"
    Cisco_IOS_XR_pbr_oper_interface_name = 1322899300
    Cisco_IOS_XR_pbr_oper_interface_name_ = "interface-name"
    Cisco_IOS_XR_pbr_oper_rqst_rcvd_packets = 37037740
    Cisco_IOS_XR_pbr_oper_rqst_rcvd_packets_ = "rqst-rcvd-packets"
    Cisco_IOS_XR_pbr_oper_general_stats = 1433569072
    Cisco_IOS_XR_pbr_oper_general_stats_ = "general-stats"
    Cisco_IOS_XR_pbr_oper_state = 630973766
    Cisco_IOS_XR_pbr_oper_state_ = "state"
    Cisco_IOS_XR_pbr_oper_direction = 1468062370
    Cisco_IOS_XR_pbr_oper_direction_ = "direction"
    Cisco_IOS_XR_pbr_oper_nodes = 650955465
    Cisco_IOS_XR_pbr_oper_nodes_ = "nodes"
    Cisco_IOS_XR_pbr_oper_total_drop_bytes = 685713791
    Cisco_IOS_XR_pbr_oper_total_drop_bytes_ = "total-drop-bytes"
    Cisco_IOS_XR_pbr_oper_match_data_rate = 501439230
    Cisco_IOS_XR_pbr_oper_match_data_rate_ = "match-data-rate"
    Cisco_IOS_XR_pbr_oper_transmit_packets = 1049032631
    Cisco_IOS_XR_pbr_oper_transmit_packets_ = "transmit-packets"
    Cisco_IOS_XR_pbr_oper_node_name = 122353445
    Cisco_IOS_XR_pbr_oper_node_name_ = "node-name"
    Cisco_IOS_XR_pbr_oper_drop_packets = 877513791
    Cisco_IOS_XR_pbr_oper_drop_packets_ = "drop-packets"
    Cisco_IOS_XR_pbr_oper_total_drop_packets = 820703119
    Cisco_IOS_XR_pbr_oper_total_drop_packets_ = "total-drop-packets"
    Cisco_IOS_XR_pbr_oper_class_stat = 933468346
    Cisco_IOS_XR_pbr_oper_class_stat_ = "class-stat"
    Cisco_IOS_XR_pbr_oper_interfaces = 321503962
    Cisco_IOS_XR_pbr_oper_interfaces_ = "interfaces"
    Cisco_IOS_XR_pbr_oper_resp_sent_bytes = 1611638997
    Cisco_IOS_XR_pbr_oper_resp_sent_bytes_ = "resp-sent-bytes"
    Cisco_IOS_XR_pbr_oper_policy_name = 248830179
    Cisco_IOS_XR_pbr_oper_policy_name_ = "policy-name"
    Cisco_IOS_XR_pbr_oper_transmit_bytes = 546745369
    Cisco_IOS_XR_pbr_oper_transmit_bytes_ = "transmit-bytes"
    Cisco_IOS_XR_pbr_oper_input = 1427240772
    Cisco_IOS_XR_pbr_oper_input_ = "input"
    Cisco_IOS_XR_pbr_oper_httpr_stats = 1306671167
    Cisco_IOS_XR_pbr_oper_httpr_stats_ = "httpr-stats"
    Cisco_IOS_XR_pbr_oper_node = 2084421367
    Cisco_IOS_XR_pbr_oper_node_ = "node"
    Cisco_IOS_XR_pbr_oper_pre_policy_matched_packets = 1737683263
    Cisco_IOS_XR_pbr_oper_pre_policy_matched_packets_ = "pre-policy-matched-packets"
    Cisco_IOS_XR_pbr_oper_total_drop_rate = 866424944
    Cisco_IOS_XR_pbr_oper_total_drop_rate_ = "total-drop-rate"
    Cisco_IOS_XR_pbr_oper_counter_validity_bitmask = 1215384494
    Cisco_IOS_XR_pbr_oper_counter_validity_bitmask_ = "counter-validity-bitmask"
    Cisco_IOS_XR_pbr_oper_resp_sent_packets = 1993312392
    Cisco_IOS_XR_pbr_oper_resp_sent_packets_ = "resp-sent-packets"
    Cisco_IOS_XR_pbr_oper_active = 0
    Cisco_IOS_XR_pbr_oper_active_ = "active"
    Cisco_IOS_XR_pbr_oper_pre_policy_matched_bytes = 924551949
    Cisco_IOS_XR_pbr_oper_pre_policy_matched_bytes_ = "pre-policy-matched-bytes"
