#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-infra-sla-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-infra-sla-cfg.yang


class ns(object):
    hash = 468036985

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-sla-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-sla-cfg"

    prefix = "Cisco-IOS-XR-infra-sla-cfg"

    Cisco_IOS_XR_infra_sla_cfg_protocols = 1217680707
    Cisco_IOS_XR_infra_sla_cfg_protocols_ = "protocols"
    Cisco_IOS_XR_infra_sla_cfg_sla = 674160373
    Cisco_IOS_XR_infra_sla_cfg_sla_ = "sla"
