#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-ip-iarm-vrf-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-ip-iarm-vrf-cfg.yang


class ns(object):
    hash = 892202657

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-iarm-vrf-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-iarm-vrf-cfg"

    prefix = "Cisco-IOS-XR-ip-iarm-vrf-cfg"

    Cisco_IOS_XR_ip_iarm_vrf_cfg_interface = 221572658
    Cisco_IOS_XR_ip_iarm_vrf_cfg_interface_ = "interface"
    Cisco_IOS_XR_ip_iarm_vrf_cfg_ipv4 = 268057062
    Cisco_IOS_XR_ip_iarm_vrf_cfg_ipv4_ = "ipv4"
    Cisco_IOS_XR_ip_iarm_vrf_cfg_ipv6 = 1228132394
    Cisco_IOS_XR_ip_iarm_vrf_cfg_ipv6_ = "ipv6"
    Cisco_IOS_XR_ip_iarm_vrf_cfg_multicast_host = 1487634749
    Cisco_IOS_XR_ip_iarm_vrf_cfg_multicast_host_ = "multicast-host"
