#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-Ethernet-SPAN-datatypes.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-Ethernet-SPAN-datatypes.yang


class ns(object):
    hash = 1814350352

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-Ethernet-SPAN-datatypes"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-Ethernet-SPAN-datatypes"

    prefix = "Cisco-IOS-XR-Ethernet-SPAN-datatypes"

    Cisco_IOS_XR_Ethernet_SPAN_datatypes_ethernet = 0
    Cisco_IOS_XR_Ethernet_SPAN_datatypes_ethernet_ = "ethernet"
    Cisco_IOS_XR_Ethernet_SPAN_datatypes_mpls_ipv6 = 4
    Cisco_IOS_XR_Ethernet_SPAN_datatypes_mpls_ipv6_ = "mpls-ipv6"
    Cisco_IOS_XR_Ethernet_SPAN_datatypes_true = 0
    Cisco_IOS_XR_Ethernet_SPAN_datatypes_true_ = "true"
    Cisco_IOS_XR_Ethernet_SPAN_datatypes_ipv4 = 1
    Cisco_IOS_XR_Ethernet_SPAN_datatypes_ipv4_ = "ipv4"
    Cisco_IOS_XR_Ethernet_SPAN_datatypes_ipv6 = 2
    Cisco_IOS_XR_Ethernet_SPAN_datatypes_ipv6_ = "ipv6"
    Cisco_IOS_XR_Ethernet_SPAN_datatypes_mpls_ipv4 = 3
    Cisco_IOS_XR_Ethernet_SPAN_datatypes_mpls_ipv4_ = "mpls-ipv4"
