#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-rptiming-dti-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-rptiming-dti-oper.yang


class ns(object):
    hash = 1986456897

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-rptiming-dti-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-rptiming-dti-oper"

    prefix = "Cisco-IOS-XR-rptiming-dti-oper"

    Cisco_IOS_XR_rptiming_dti_oper_port1_calendar_time_valid = 716578045
    Cisco_IOS_XR_rptiming_dti_oper_port1_calendar_time_valid_ = "port1-calendar-time-valid"
    Cisco_IOS_XR_rptiming_dti_oper_port2_time_zone_offset = 759814898
    Cisco_IOS_XR_rptiming_dti_oper_port2_time_zone_offset_ = "port2-time-zone-offset"
    Cisco_IOS_XR_rptiming_dti_oper_port1_time_zone_offset = 811570854
    Cisco_IOS_XR_rptiming_dti_oper_port1_time_zone_offset_ = "port1-time-zone-offset"
    Cisco_IOS_XR_rptiming_dti_oper_port1_leap_seconds = 1068474208
    Cisco_IOS_XR_rptiming_dti_oper_port1_leap_seconds_ = "port1-leap-seconds"
    Cisco_IOS_XR_rptiming_dti_oper_dti_controller = 1153308708
    Cisco_IOS_XR_rptiming_dti_oper_dti_controller_ = "dti-controller"
    Cisco_IOS_XR_rptiming_dti_oper_port1_tod_time_setting_mode = 2071081584
    Cisco_IOS_XR_rptiming_dti_oper_port1_tod_time_setting_mode_ = "port1-tod-time-setting-mode"
    Cisco_IOS_XR_rptiming_dti_oper_port = 10387472
    Cisco_IOS_XR_rptiming_dti_oper_port_ = "port"
    Cisco_IOS_XR_rptiming_dti_oper_register_write_enable = 1804278323
    Cisco_IOS_XR_rptiming_dti_oper_register_write_enable_ = "register-write-enable"
    Cisco_IOS_XR_rptiming_dti_oper_time_of_day = 2133624728
    Cisco_IOS_XR_rptiming_dti_oper_time_of_day_ = "time-of-day"
    Cisco_IOS_XR_rptiming_dti_oper_port2_modified_julian_date = 63850021
    Cisco_IOS_XR_rptiming_dti_oper_port2_modified_julian_date_ = "port2-modified-julian-date"
    Cisco_IOS_XR_rptiming_dti_oper_port2_server_timing_source = 1529215502
    Cisco_IOS_XR_rptiming_dti_oper_port2_server_timing_source_ = "port2-server-timing-source"
    Cisco_IOS_XR_rptiming_dti_oper_timestamp_sync_detected = 1576802988
    Cisco_IOS_XR_rptiming_dti_oper_timestamp_sync_detected_ = "timestamp-sync-detected"
    Cisco_IOS_XR_rptiming_dti_oper_port2_dti_signal_detected = 144650679
    Cisco_IOS_XR_rptiming_dti_oper_port2_dti_signal_detected_ = "port2-dti-signal-detected"
    Cisco_IOS_XR_rptiming_dti_oper_port2_calendar_time_valid = 1681085126
    Cisco_IOS_XR_rptiming_dti_oper_port2_calendar_time_valid_ = "port2-calendar-time-valid"
    Cisco_IOS_XR_rptiming_dti_oper_port2_leap_second_indicator = 1858692656
    Cisco_IOS_XR_rptiming_dti_oper_port2_leap_second_indicator_ = "port2-leap-second-indicator"
    Cisco_IOS_XR_rptiming_dti_oper_client = 2128680708
    Cisco_IOS_XR_rptiming_dti_oper_client_ = "client"
    Cisco_IOS_XR_rptiming_dti_oper_port2_time = 344394077
    Cisco_IOS_XR_rptiming_dti_oper_port2_time_ = "port2-time"
    Cisco_IOS_XR_rptiming_dti_oper_reference10mhz_detected = 508477605
    Cisco_IOS_XR_rptiming_dti_oper_reference10mhz_detected_ = "reference10mhz-detected"
    Cisco_IOS_XR_rptiming_dti_oper_port2_fr_err_rate_greater2_per = 225044382
    Cisco_IOS_XR_rptiming_dti_oper_port2_fr_err_rate_greater2_per_ = "port2-fr-err-rate-greater2-per"
    Cisco_IOS_XR_rptiming_dti_oper_port2_tod_time_setting_mode = 1490999486
    Cisco_IOS_XR_rptiming_dti_oper_port2_tod_time_setting_mode_ = "port2-tod-time-setting-mode"
    Cisco_IOS_XR_rptiming_dti_oper_timestamp_comparator_enable = 1830107943
    Cisco_IOS_XR_rptiming_dti_oper_timestamp_comparator_enable_ = "timestamp-comparator-enable"
    Cisco_IOS_XR_rptiming_dti_oper_port1_gps_seconds = 578540406
    Cisco_IOS_XR_rptiming_dti_oper_port1_gps_seconds_ = "port1-gps-seconds"
    Cisco_IOS_XR_rptiming_dti_oper_port2_tod_message_mode = 272895122
    Cisco_IOS_XR_rptiming_dti_oper_port2_tod_message_mode_ = "port2-tod-message-mode"
    Cisco_IOS_XR_rptiming_dti_oper_port2_leap_seconds = 1139956127
    Cisco_IOS_XR_rptiming_dti_oper_port2_leap_seconds_ = "port2-leap-seconds"
    Cisco_IOS_XR_rptiming_dti_oper_revertive_mode_enable = 381252808
    Cisco_IOS_XR_rptiming_dti_oper_revertive_mode_enable_ = "revertive-mode-enable"
    Cisco_IOS_XR_rptiming_dti_oper_port2_date = 1249519272
    Cisco_IOS_XR_rptiming_dti_oper_port2_date_ = "port2-date"
    Cisco_IOS_XR_rptiming_dti_oper_port_mode_select = 1770956517
    Cisco_IOS_XR_rptiming_dti_oper_port_mode_select_ = "port-mode-select"
    Cisco_IOS_XR_rptiming_dti_oper_port1_server_type = 142398741
    Cisco_IOS_XR_rptiming_dti_oper_port1_server_type_ = "port1-server-type"
    Cisco_IOS_XR_rptiming_dti_oper_force_freerun = 1260741336
    Cisco_IOS_XR_rptiming_dti_oper_force_freerun_ = "force-freerun"
    Cisco_IOS_XR_rptiming_dti_oper_port1_server_state = 1620952969
    Cisco_IOS_XR_rptiming_dti_oper_port1_server_state_ = "port1-server-state"
    Cisco_IOS_XR_rptiming_dti_oper_port1_modified_julian_date = 504340751
    Cisco_IOS_XR_rptiming_dti_oper_port1_modified_julian_date_ = "port1-modified-julian-date"
    Cisco_IOS_XR_rptiming_dti_oper_port1_cable_advance_valid = 599415754
    Cisco_IOS_XR_rptiming_dti_oper_port1_cable_advance_valid_ = "port1-cable-advance-valid"
    Cisco_IOS_XR_rptiming_dti_oper_port2_gps_seconds = 2010986890
    Cisco_IOS_XR_rptiming_dti_oper_port2_gps_seconds_ = "port2-gps-seconds"
    Cisco_IOS_XR_rptiming_dti_oper_port2_tod_state = 1930501688
    Cisco_IOS_XR_rptiming_dti_oper_port2_tod_state_ = "port2-tod-state"
    Cisco_IOS_XR_rptiming_dti_oper_port2_server_state = 588840979
    Cisco_IOS_XR_rptiming_dti_oper_port2_server_state_ = "port2-server-state"
    Cisco_IOS_XR_rptiming_dti_oper_port1_client_perf_stable = 506572155
    Cisco_IOS_XR_rptiming_dti_oper_port1_client_perf_stable_ = "port1-client-perf-stable"
    Cisco_IOS_XR_rptiming_dti_oper_port1_server_clock_type = 1407832737
    Cisco_IOS_XR_rptiming_dti_oper_port1_server_clock_type_ = "port1-server-clock-type"
    Cisco_IOS_XR_rptiming_dti_oper_nodes = 650955465
    Cisco_IOS_XR_rptiming_dti_oper_nodes_ = "nodes"
    Cisco_IOS_XR_rptiming_dti_oper_reference_select_port = 158289625
    Cisco_IOS_XR_rptiming_dti_oper_reference_select_port_ = "reference-select-port"
    Cisco_IOS_XR_rptiming_dti_oper_node_name = 122353445
    Cisco_IOS_XR_rptiming_dti_oper_node_name_ = "node-name"
    Cisco_IOS_XR_rptiming_dti_oper_port1_tod_message_mode = 1943359191
    Cisco_IOS_XR_rptiming_dti_oper_port1_tod_message_mode_ = "port1-tod-message-mode"
    Cisco_IOS_XR_rptiming_dti_oper_port2_server_type = 459473733
    Cisco_IOS_XR_rptiming_dti_oper_port2_server_type_ = "port2-server-type"
    Cisco_IOS_XR_rptiming_dti_oper_port1_time = 759326778
    Cisco_IOS_XR_rptiming_dti_oper_port1_time_ = "port1-time"
    Cisco_IOS_XR_rptiming_dti_oper_port1_fr_err_rate_greater5_per = 1163333557
    Cisco_IOS_XR_rptiming_dti_oper_port1_fr_err_rate_greater5_per_ = "port1-fr-err-rate-greater5-per"
    Cisco_IOS_XR_rptiming_dti_oper_active_input_port = 290145502
    Cisco_IOS_XR_rptiming_dti_oper_active_input_port_ = "active-input-port"
    Cisco_IOS_XR_rptiming_dti_oper_port2_cable_advance_valid = 686608036
    Cisco_IOS_XR_rptiming_dti_oper_port2_cable_advance_valid_ = "port2-cable-advance-valid"
    Cisco_IOS_XR_rptiming_dti_oper_port1_leap_second_indicator = 102927992
    Cisco_IOS_XR_rptiming_dti_oper_port1_leap_second_indicator_ = "port1-leap-second-indicator"
    Cisco_IOS_XR_rptiming_dti_oper_node = 2084421367
    Cisco_IOS_XR_rptiming_dti_oper_node_ = "node"
    Cisco_IOS_XR_rptiming_dti_oper_port1_fr_err_rate_greater2_per = 743105759
    Cisco_IOS_XR_rptiming_dti_oper_port1_fr_err_rate_greater2_per_ = "port1-fr-err-rate-greater2-per"
    Cisco_IOS_XR_rptiming_dti_oper_port2_fr_err_rate_greater5_per = 944551786
    Cisco_IOS_XR_rptiming_dti_oper_port2_fr_err_rate_greater5_per_ = "port2-fr-err-rate-greater5-per"
    Cisco_IOS_XR_rptiming_dti_oper_port1_date = 1711281081
    Cisco_IOS_XR_rptiming_dti_oper_port1_date_ = "port1-date"
    Cisco_IOS_XR_rptiming_dti_oper_port1_server_timing_source = 863745722
    Cisco_IOS_XR_rptiming_dti_oper_port1_server_timing_source_ = "port1-server-timing-source"
    Cisco_IOS_XR_rptiming_dti_oper_port1_dti_signal_detected = 798891110
    Cisco_IOS_XR_rptiming_dti_oper_port1_dti_signal_detected_ = "port1-dti-signal-detected"
    Cisco_IOS_XR_rptiming_dti_oper_client_state = 1309680291
    Cisco_IOS_XR_rptiming_dti_oper_client_state_ = "client-state"
    Cisco_IOS_XR_rptiming_dti_oper_port2_client_perf_stable = 852306468
    Cisco_IOS_XR_rptiming_dti_oper_port2_client_perf_stable_ = "port2-client-perf-stable"
    Cisco_IOS_XR_rptiming_dti_oper_port2_server_clock_type = 1025183035
    Cisco_IOS_XR_rptiming_dti_oper_port2_server_clock_type_ = "port2-server-clock-type"
    Cisco_IOS_XR_rptiming_dti_oper_port1_tod_state = 355545220
    Cisco_IOS_XR_rptiming_dti_oper_port1_tod_state_ = "port1-tod-state"
