#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-drivers-media-eth-act.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-drivers-media-eth-act.yang


class ns(object):
    hash = 1165792764

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-drivers-media-eth-act"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-drivers-media-eth-act"

    prefix = "Cisco-IOS-XR-drivers-media-eth-act"

    Cisco_IOS_XR_drivers_media_eth_act_clear_controller_counters = 514647742
    Cisco_IOS_XR_drivers_media_eth_act_clear_controller_counters_ = "clear-controller-counters"
    Cisco_IOS_XR_drivers_media_eth_act_rpc_clear_controller_counters = 1864428989
    Cisco_IOS_XR_drivers_media_eth_act_rpc_clear_controller_counters_ = "rpc-clear-controller-counters"
    Cisco_IOS_XR_drivers_media_eth_act_controller_name = 2147097453
    Cisco_IOS_XR_drivers_media_eth_act_controller_name_ = "controller-name"
