#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-lpts-pa-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-lpts-pa-oper.yang


class ns(object):
    hash = 478886136

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-lpts-pa-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-lpts-pa-oper"

    prefix = "Cisco-IOS-XR-lpts-pa-oper"

    Cisco_IOS_XR_lpts_pa_oper_tv_nsec = 990837293
    Cisco_IOS_XR_lpts_pa_oper_tv_nsec_ = "tv-nsec"
    Cisco_IOS_XR_lpts_pa_oper_entries = 1782358652
    Cisco_IOS_XR_lpts_pa_oper_entries_ = "entries"
    Cisco_IOS_XR_lpts_pa_oper_cookie = 1162178752
    Cisco_IOS_XR_lpts_pa_oper_cookie_ = "cookie"
    Cisco_IOS_XR_lpts_pa_oper_ptype = 190468188
    Cisco_IOS_XR_lpts_pa_oper_ptype_ = "ptype"
    Cisco_IOS_XR_lpts_pa_oper_lpts_pa = 626094918
    Cisco_IOS_XR_lpts_pa_oper_lpts_pa_ = "lpts-pa"
    Cisco_IOS_XR_lpts_pa_oper_location = 1827424758
    Cisco_IOS_XR_lpts_pa_oper_location_ = "location"
    Cisco_IOS_XR_lpts_pa_oper_remote_ip = 72199264
    Cisco_IOS_XR_lpts_pa_oper_remote_ip_ = "remote-ip"
    Cisco_IOS_XR_lpts_pa_oper_entry_xr = 382001488
    Cisco_IOS_XR_lpts_pa_oper_entry_xr_ = "entry-xr"
    Cisco_IOS_XR_lpts_pa_oper_ifs = 1748416598
    Cisco_IOS_XR_lpts_pa_oper_ifs_ = "ifs"
    Cisco_IOS_XR_lpts_pa_oper_remote_port = 1738088052
    Cisco_IOS_XR_lpts_pa_oper_remote_port_ = "remote-port"
    Cisco_IOS_XR_lpts_pa_oper_tv_sec = 2018156947
    Cisco_IOS_XR_lpts_pa_oper_tv_sec_ = "tv-sec"
    Cisco_IOS_XR_lpts_pa_oper_vid = 1545846517
    Cisco_IOS_XR_lpts_pa_oper_vid_ = "vid"
    Cisco_IOS_XR_lpts_pa_oper_local_ip = 218038149
    Cisco_IOS_XR_lpts_pa_oper_local_ip_ = "local-ip"
    Cisco_IOS_XR_lpts_pa_oper_scope = 2046414572
    Cisco_IOS_XR_lpts_pa_oper_scope_ = "scope"
    Cisco_IOS_XR_lpts_pa_oper_times = 41825777
    Cisco_IOS_XR_lpts_pa_oper_times_ = "times"
    Cisco_IOS_XR_lpts_pa_oper_l3protocol = 1649680430
    Cisco_IOS_XR_lpts_pa_oper_l3protocol_ = "l3protocol"
    Cisco_IOS_XR_lpts_pa_oper_ptq_delay = 1177281441
    Cisco_IOS_XR_lpts_pa_oper_ptq_delay_ = "ptq-delay"
    Cisco_IOS_XR_lpts_pa_oper_min_ttl = 857432635
    Cisco_IOS_XR_lpts_pa_oper_min_ttl_ = "min-ttl"
    Cisco_IOS_XR_lpts_pa_oper_local_len = 142173267
    Cisco_IOS_XR_lpts_pa_oper_local_len_ = "local-len"
    Cisco_IOS_XR_lpts_pa_oper_utime = 1046311718
    Cisco_IOS_XR_lpts_pa_oper_utime_ = "utime"
    Cisco_IOS_XR_lpts_pa_oper_open_flags = 191859748
    Cisco_IOS_XR_lpts_pa_oper_open_flags_ = "open-flags"
    Cisco_IOS_XR_lpts_pa_oper_l4protocol = 1302889205
    Cisco_IOS_XR_lpts_pa_oper_l4protocol_ = "l4protocol"
    Cisco_IOS_XR_lpts_pa_oper_remote_len = 725623781
    Cisco_IOS_XR_lpts_pa_oper_remote_len_ = "remote-len"
    Cisco_IOS_XR_lpts_pa_oper_lazy_bindq_delay = 1758100364
    Cisco_IOS_XR_lpts_pa_oper_lazy_bindq_delay_ = "lazy-bindq-delay"
    Cisco_IOS_XR_lpts_pa_oper_local_port = 560832355
    Cisco_IOS_XR_lpts_pa_oper_local_port_ = "local-port"
    Cisco_IOS_XR_lpts_pa_oper_packet_misc = 718278935
    Cisco_IOS_XR_lpts_pa_oper_packet_misc_ = "packet-misc"
    Cisco_IOS_XR_lpts_pa_oper_client_id = 862765095
    Cisco_IOS_XR_lpts_pa_oper_client_id_ = "client-id"
    Cisco_IOS_XR_lpts_pa_oper_entry = 1974505388
    Cisco_IOS_XR_lpts_pa_oper_entry_ = "entry"
    Cisco_IOS_XR_lpts_pa_oper_client_flags = 417479674
    Cisco_IOS_XR_lpts_pa_oper_client_flags_ = "client-flags"
    Cisco_IOS_XR_lpts_pa_oper_flags = 1646628167
    Cisco_IOS_XR_lpts_pa_oper_flags_ = "flags"
    Cisco_IOS_XR_lpts_pa_oper_smask = 244521107
    Cisco_IOS_XR_lpts_pa_oper_smask_ = "smask"
    Cisco_IOS_XR_lpts_pa_oper_ctime = 2006569158
    Cisco_IOS_XR_lpts_pa_oper_ctime_ = "ctime"
