#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-ptp-datatypes.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-ptp-datatypes.yang


class ns(object):
    hash = 1481523688

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ptp-datatypes"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ptp-datatypes"

    prefix = "Cisco-IOS-XR-ptp-datatypes"

    Cisco_IOS_XR_ptp_datatypes_g82751 = 2
    Cisco_IOS_XR_ptp_datatypes_g82751_ = "g82751"
    Cisco_IOS_XR_ptp_datatypes_ethernet = 1
    Cisco_IOS_XR_ptp_datatypes_ethernet_ = "ethernet"
    Cisco_IOS_XR_ptp_datatypes_frequency = 1
    Cisco_IOS_XR_ptp_datatypes_frequency_ = "frequency"
    Cisco_IOS_XR_ptp_datatypes_any = 0
    Cisco_IOS_XR_ptp_datatypes_any_ = "any"
    Cisco_IOS_XR_ptp_datatypes_ntp = 80
    Cisco_IOS_XR_ptp_datatypes_ntp_ = "ntp"
    Cisco_IOS_XR_ptp_datatypes_gps = 32
    Cisco_IOS_XR_ptp_datatypes_gps_ = "gps"
    Cisco_IOS_XR_ptp_datatypes_hand_set = 96
    Cisco_IOS_XR_ptp_datatypes_hand_set_ = "hand-set"
    Cisco_IOS_XR_ptp_datatypes_nanoseconds = 0
    Cisco_IOS_XR_ptp_datatypes_nanoseconds_ = "nanoseconds"
    Cisco_IOS_XR_ptp_datatypes_1588v2 = 0
    Cisco_IOS_XR_ptp_datatypes_1588v2_ = "1588v2"
    Cisco_IOS_XR_ptp_datatypes_mixed_mode = 1
    Cisco_IOS_XR_ptp_datatypes_mixed_mode_ = "mixed-mode"
    Cisco_IOS_XR_ptp_datatypes_2 = 1
    Cisco_IOS_XR_ptp_datatypes_2_ = "2"
    Cisco_IOS_XR_ptp_datatypes_g82651 = 1
    Cisco_IOS_XR_ptp_datatypes_g82651_ = "g82651"
    Cisco_IOS_XR_ptp_datatypes_router_mac = 0
    Cisco_IOS_XR_ptp_datatypes_router_mac_ = "router-mac"
    Cisco_IOS_XR_ptp_datatypes_unicast = 0
    Cisco_IOS_XR_ptp_datatypes_unicast_ = "unicast"
    Cisco_IOS_XR_ptp_datatypes_default = 0
    Cisco_IOS_XR_ptp_datatypes_default_ = "default"
    Cisco_IOS_XR_ptp_datatypes_milliseconds = 2
    Cisco_IOS_XR_ptp_datatypes_milliseconds_ = "milliseconds"
    Cisco_IOS_XR_ptp_datatypes_128 = 7
    Cisco_IOS_XR_ptp_datatypes_128_ = "128"
    Cisco_IOS_XR_ptp_datatypes_one_step = 1
    Cisco_IOS_XR_ptp_datatypes_one_step_ = "one-step"
    Cisco_IOS_XR_ptp_datatypes_atomic_clock = 16
    Cisco_IOS_XR_ptp_datatypes_atomic_clock_ = "atomic-clock"
    Cisco_IOS_XR_ptp_datatypes_eui = 2
    Cisco_IOS_XR_ptp_datatypes_eui_ = "eui"
    Cisco_IOS_XR_ptp_datatypes_8 = 3
    Cisco_IOS_XR_ptp_datatypes_8_ = "8"
    Cisco_IOS_XR_ptp_datatypes_ipv4 = 2
    Cisco_IOS_XR_ptp_datatypes_ipv4_ = "ipv4"
    Cisco_IOS_XR_ptp_datatypes_multicast = 2
    Cisco_IOS_XR_ptp_datatypes_multicast_ = "multicast"
    Cisco_IOS_XR_ptp_datatypes_telecom_grandmaster = 0
    Cisco_IOS_XR_ptp_datatypes_telecom_grandmaster_ = "telecom-grandmaster"
    Cisco_IOS_XR_ptp_datatypes_interval = 0
    Cisco_IOS_XR_ptp_datatypes_interval_ = "interval"
    Cisco_IOS_XR_ptp_datatypes_telecom_slave = 2
    Cisco_IOS_XR_ptp_datatypes_telecom_slave_ = "telecom-slave"
    Cisco_IOS_XR_ptp_datatypes_32 = 5
    Cisco_IOS_XR_ptp_datatypes_32_ = "32"
    Cisco_IOS_XR_ptp_datatypes_user_mac = 1
    Cisco_IOS_XR_ptp_datatypes_user_mac_ = "user-mac"
    Cisco_IOS_XR_ptp_datatypes_64 = 6
    Cisco_IOS_XR_ptp_datatypes_64_ = "64"
    Cisco_IOS_XR_ptp_datatypes_ipv6 = 3
    Cisco_IOS_XR_ptp_datatypes_ipv6_ = "ipv6"
    Cisco_IOS_XR_ptp_datatypes_internal_oscillator = 160
    Cisco_IOS_XR_ptp_datatypes_internal_oscillator_ = "internal-oscillator"
    Cisco_IOS_XR_ptp_datatypes_microseconds = 1
    Cisco_IOS_XR_ptp_datatypes_microseconds_ = "microseconds"
    Cisco_IOS_XR_ptp_datatypes_slave_only = 1
    Cisco_IOS_XR_ptp_datatypes_slave_only_ = "slave-only"
    Cisco_IOS_XR_ptp_datatypes_4 = 2
    Cisco_IOS_XR_ptp_datatypes_4_ = "4"
    Cisco_IOS_XR_ptp_datatypes_arb = 1
    Cisco_IOS_XR_ptp_datatypes_arb_ = "arb"
    Cisco_IOS_XR_ptp_datatypes_other = 144
    Cisco_IOS_XR_ptp_datatypes_other_ = "other"
    Cisco_IOS_XR_ptp_datatypes_deny = 1
    Cisco_IOS_XR_ptp_datatypes_deny_ = "deny"
    Cisco_IOS_XR_ptp_datatypes_reduce = 0
    Cisco_IOS_XR_ptp_datatypes_reduce_ = "reduce"
    Cisco_IOS_XR_ptp_datatypes_master_only = 2
    Cisco_IOS_XR_ptp_datatypes_master_only_ = "master-only"
    Cisco_IOS_XR_ptp_datatypes_telecom_profile = 1
    Cisco_IOS_XR_ptp_datatypes_telecom_profile_ = "telecom-profile"
    Cisco_IOS_XR_ptp_datatypes_telecom_boundary = 1
    Cisco_IOS_XR_ptp_datatypes_telecom_boundary_ = "telecom-boundary"
    Cisco_IOS_XR_ptp_datatypes_16 = 4
    Cisco_IOS_XR_ptp_datatypes_16_ = "16"
    Cisco_IOS_XR_ptp_datatypes_g82752 = 3
    Cisco_IOS_XR_ptp_datatypes_g82752_ = "g82752"
    Cisco_IOS_XR_ptp_datatypes_unknown = 0
    Cisco_IOS_XR_ptp_datatypes_unknown_ = "unknown"
    Cisco_IOS_XR_ptp_datatypes_1 = 0
    Cisco_IOS_XR_ptp_datatypes_1_ = "1"
    Cisco_IOS_XR_ptp_datatypes_terrestrial_radio = 48
    Cisco_IOS_XR_ptp_datatypes_terrestrial_radio_ = "terrestrial-radio"
    Cisco_IOS_XR_ptp_datatypes_two_step = 0
    Cisco_IOS_XR_ptp_datatypes_two_step_ = "two-step"
