#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-config-mda-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-config-mda-cfg.yang


class ns(object):
    hash = 629998235

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-config-mda-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-config-mda-cfg"

    prefix = "Cisco-IOS-XR-config-mda-cfg"

    Cisco_IOS_XR_config_mda_cfg_preconfigured_node = 1634445668
    Cisco_IOS_XR_config_mda_cfg_preconfigured_node_ = "preconfigured-node"
    Cisco_IOS_XR_config_mda_cfg_active_node = 1866616408
    Cisco_IOS_XR_config_mda_cfg_active_node_ = "active-node"
    Cisco_IOS_XR_config_mda_cfg_node_name = 122353445
    Cisco_IOS_XR_config_mda_cfg_node_name_ = "node-name"
    Cisco_IOS_XR_config_mda_cfg_active_nodes = 244580728
    Cisco_IOS_XR_config_mda_cfg_active_nodes_ = "active-nodes"
    Cisco_IOS_XR_config_mda_cfg_preconfigured_nodes = 422512595
    Cisco_IOS_XR_config_mda_cfg_preconfigured_nodes_ = "preconfigured-nodes"
