#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-infra-notification-log-mib-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-infra-notification-log-mib-cfg.yang


class ns(object):
    hash = 1755379740

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-notification-log-mib-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-notification-log-mib-cfg"

    prefix = "Cisco-IOS-XR-infra-notification-log-mib-cfg"

    Cisco_IOS_XR_infra_notification_log_mib_cfg_default = 515137925
    Cisco_IOS_XR_infra_notification_log_mib_cfg_default_ = "default"
    Cisco_IOS_XR_infra_notification_log_mib_cfg_notification_log_mib = 387596580
    Cisco_IOS_XR_infra_notification_log_mib_cfg_notification_log_mib_ = "notification-log-mib"
    Cisco_IOS_XR_infra_notification_log_mib_cfg_default_size = 1958907370
    Cisco_IOS_XR_infra_notification_log_mib_cfg_default_size_ = "default-size"
    Cisco_IOS_XR_infra_notification_log_mib_cfg_global_age_out = 229699981
    Cisco_IOS_XR_infra_notification_log_mib_cfg_global_age_out_ = "global-age-out"
    Cisco_IOS_XR_infra_notification_log_mib_cfg_disable = 330763859
    Cisco_IOS_XR_infra_notification_log_mib_cfg_disable_ = "disable"
    Cisco_IOS_XR_infra_notification_log_mib_cfg_global_size = 329325093
    Cisco_IOS_XR_infra_notification_log_mib_cfg_global_size_ = "global-size"
