#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-fia-internal-tcam-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-fia-internal-tcam-oper.yang


class ns(object):
    hash = 941643785

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-fia-internal-tcam-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-fia-internal-tcam-oper"

    prefix = "Cisco-IOS-XR-fia-internal-tcam-oper"

    Cisco_IOS_XR_fia_internal_tcam_oper_db_prefix = 399663071
    Cisco_IOS_XR_fia_internal_tcam_oper_db_prefix_ = "db-prefix"
    Cisco_IOS_XR_fia_internal_tcam_oper_bank_free_entries = 572280133
    Cisco_IOS_XR_fia_internal_tcam_oper_bank_free_entries_ = "bank-free-entries"
    Cisco_IOS_XR_fia_internal_tcam_oper_bank_id = 1357322631
    Cisco_IOS_XR_fia_internal_tcam_oper_bank_id_ = "bank-id"
    Cisco_IOS_XR_fia_internal_tcam_oper_tcam_bank = 1188363271
    Cisco_IOS_XR_fia_internal_tcam_oper_tcam_bank_ = "tcam-bank"
    Cisco_IOS_XR_fia_internal_tcam_oper_controller = 1295630195
    Cisco_IOS_XR_fia_internal_tcam_oper_controller_ = "controller"
    Cisco_IOS_XR_fia_internal_tcam_oper_db_inuse_entries = 805922790
    Cisco_IOS_XR_fia_internal_tcam_oper_db_inuse_entries_ = "db-inuse-entries"
    Cisco_IOS_XR_fia_internal_tcam_oper_internal_tcam_resources = 541095670
    Cisco_IOS_XR_fia_internal_tcam_oper_internal_tcam_resources_ = "internal-tcam-resources"
    Cisco_IOS_XR_fia_internal_tcam_oper_npu_id = 1045918085
    Cisco_IOS_XR_fia_internal_tcam_oper_npu_id_ = "npu-id"
    Cisco_IOS_XR_fia_internal_tcam_oper_db_id = 1737875206
    Cisco_IOS_XR_fia_internal_tcam_oper_db_id_ = "db-id"
    Cisco_IOS_XR_fia_internal_tcam_oper_dpa = 544895716
    Cisco_IOS_XR_fia_internal_tcam_oper_dpa_ = "dpa"
    Cisco_IOS_XR_fia_internal_tcam_oper_bank_db = 656577768
    Cisco_IOS_XR_fia_internal_tcam_oper_bank_db_ = "bank-db"
    Cisco_IOS_XR_fia_internal_tcam_oper_bank_inuse_entries = 1931312659
    Cisco_IOS_XR_fia_internal_tcam_oper_bank_inuse_entries_ = "bank-inuse-entries"
    Cisco_IOS_XR_fia_internal_tcam_oper_npu_tcam = 2028463276
    Cisco_IOS_XR_fia_internal_tcam_oper_npu_tcam_ = "npu-tcam"
    Cisco_IOS_XR_fia_internal_tcam_oper_nodes = 650955465
    Cisco_IOS_XR_fia_internal_tcam_oper_nodes_ = "nodes"
    Cisco_IOS_XR_fia_internal_tcam_oper_node_name = 122353445
    Cisco_IOS_XR_fia_internal_tcam_oper_node_name_ = "node-name"
    Cisco_IOS_XR_fia_internal_tcam_oper_bank_key_size = 1337590197
    Cisco_IOS_XR_fia_internal_tcam_oper_bank_key_size_ = "bank-key-size"
    Cisco_IOS_XR_fia_internal_tcam_oper_nof_dbs = 1629624656
    Cisco_IOS_XR_fia_internal_tcam_oper_nof_dbs_ = "nof-dbs"
    Cisco_IOS_XR_fia_internal_tcam_oper_node = 2084421367
    Cisco_IOS_XR_fia_internal_tcam_oper_node_ = "node"
    Cisco_IOS_XR_fia_internal_tcam_oper_owner = 206925960
    Cisco_IOS_XR_fia_internal_tcam_oper_owner_ = "owner"
    Cisco_IOS_XR_fia_internal_tcam_oper_external_tcam_resources = 174838566
    Cisco_IOS_XR_fia_internal_tcam_oper_external_tcam_resources_ = "external-tcam-resources"
