#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-infra-tc-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-infra-tc-oper.yang


class ns(object):
    hash = 1496063358

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-tc-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-tc-oper"

    prefix = "Cisco-IOS-XR-infra-tc-oper"

    Cisco_IOS_XR_infra_tc_oper_collection_timer_is_running = 1226265293
    Cisco_IOS_XR_infra_tc_oper_collection_timer_is_running_ = "collection-timer-is-running"
    Cisco_IOS_XR_infra_tc_oper_count_history = 721813276
    Cisco_IOS_XR_infra_tc_oper_count_history_ = "count-history"
    Cisco_IOS_XR_infra_tc_oper_prefix = 1408440115
    Cisco_IOS_XR_infra_tc_oper_prefix_ = "prefix"
    Cisco_IOS_XR_infra_tc_oper_interface_handle = 1919201419
    Cisco_IOS_XR_infra_tc_oper_interface_handle_ = "interface-handle"
    Cisco_IOS_XR_infra_tc_oper_byte_received = 300912674
    Cisco_IOS_XR_infra_tc_oper_byte_received_ = "byte-received"
    Cisco_IOS_XR_infra_tc_oper_history_size = 1520089433
    Cisco_IOS_XR_infra_tc_oper_history_size_ = "history-size"
    Cisco_IOS_XR_infra_tc_oper_number_of_entries = 1689529105
    Cisco_IOS_XR_infra_tc_oper_number_of_entries_ = "number-of-entries"
    Cisco_IOS_XR_infra_tc_oper_default_vrf = 1381354774
    Cisco_IOS_XR_infra_tc_oper_default_vrf_ = "default-vrf"
    Cisco_IOS_XR_infra_tc_oper_label_xr = 639348213
    Cisco_IOS_XR_infra_tc_oper_label_xr_ = "label-xr"
    Cisco_IOS_XR_infra_tc_oper_vrf_table = 549872234
    Cisco_IOS_XR_infra_tc_oper_vrf_table_ = "vrf-table"
    Cisco_IOS_XR_infra_tc_oper_traffic_matrix_counter_statistics = 136042339
    Cisco_IOS_XR_infra_tc_oper_traffic_matrix_counter_statistics_ = "traffic-matrix-counter-statistics"
    Cisco_IOS_XR_infra_tc_oper_event_start_timestamp = 1347018738
    Cisco_IOS_XR_infra_tc_oper_event_start_timestamp_ = "event-start-timestamp"
    Cisco_IOS_XR_infra_tc_oper_base_counter_statistics = 388332697
    Cisco_IOS_XR_infra_tc_oper_base_counter_statistics_ = "base-counter-statistics"
    Cisco_IOS_XR_infra_tc_oper_is_interface_enabled = 2137398070
    Cisco_IOS_XR_infra_tc_oper_is_interface_enabled_ = "is-interface-enabled"
    Cisco_IOS_XR_infra_tc_oper_ipaddr = 779225502
    Cisco_IOS_XR_infra_tc_oper_ipaddr_ = "ipaddr"
    Cisco_IOS_XR_infra_tc_oper_event_end_timestamp = 1049772582
    Cisco_IOS_XR_infra_tc_oper_event_end_timestamp_ = "event-end-timestamp"
    Cisco_IOS_XR_infra_tc_oper_external_interface = 1493494641
    Cisco_IOS_XR_infra_tc_oper_external_interface_ = "external-interface"
    Cisco_IOS_XR_infra_tc_oper_is_valid = 1842996374
    Cisco_IOS_XR_infra_tc_oper_is_valid_ = "is-valid"
    Cisco_IOS_XR_infra_tc_oper_maximum_roundtrip_latency = 1583381105
    Cisco_IOS_XR_infra_tc_oper_maximum_roundtrip_latency_ = "maximum-roundtrip-latency"
    Cisco_IOS_XR_infra_tc_oper_number_of_stale_entries = 1664813463
    Cisco_IOS_XR_infra_tc_oper_number_of_stale_entries_ = "number-of-stale-entries"
    Cisco_IOS_XR_infra_tc_oper_packet_received = 1204874092
    Cisco_IOS_XR_infra_tc_oper_packet_received_ = "packet-received"
    Cisco_IOS_XR_infra_tc_oper_tunnel = 1120006729
    Cisco_IOS_XR_infra_tc_oper_tunnel_ = "tunnel"
    Cisco_IOS_XR_infra_tc_oper_traffic_collector = 95612725
    Cisco_IOS_XR_infra_tc_oper_traffic_collector_ = "traffic-collector"
    Cisco_IOS_XR_infra_tc_oper_af_name = 1810421312
    Cisco_IOS_XR_infra_tc_oper_af_name_ = "af-name"
    Cisco_IOS_XR_infra_tc_oper_database_statistics_tunnel = 25955876
    Cisco_IOS_XR_infra_tc_oper_database_statistics_tunnel_ = "database-statistics-tunnel"
    Cisco_IOS_XR_infra_tc_oper_transmit_number_of_bytes_switched = 472936440
    Cisco_IOS_XR_infra_tc_oper_transmit_number_of_bytes_switched_ = "transmit-number-of-bytes-switched"
    Cisco_IOS_XR_infra_tc_oper_mask = 1167181041
    Cisco_IOS_XR_infra_tc_oper_mask_ = "mask"
    Cisco_IOS_XR_infra_tc_oper_interface_name = 1322899300
    Cisco_IOS_XR_infra_tc_oper_interface_name_ = "interface-name"
    Cisco_IOS_XR_infra_tc_oper_byte_sent = 685554666
    Cisco_IOS_XR_infra_tc_oper_byte_sent_ = "byte-sent"
    Cisco_IOS_XR_infra_tc_oper_timeout_timer_is_running = 1802627074
    Cisco_IOS_XR_infra_tc_oper_timeout_timer_is_running_ = "timeout-timer-is-running"
    Cisco_IOS_XR_infra_tc_oper_vrfid = 713344343
    Cisco_IOS_XR_infra_tc_oper_vrfid_ = "vrfid"
    Cisco_IOS_XR_infra_tc_oper_vrf_name = 2140916904
    Cisco_IOS_XR_infra_tc_oper_vrf_name_ = "vrf-name"
    Cisco_IOS_XR_infra_tc_oper_ipv4 = 0
    Cisco_IOS_XR_infra_tc_oper_ipv4_ = "ipv4"
    Cisco_IOS_XR_infra_tc_oper_number_of_add_o_perations = 1505034365
    Cisco_IOS_XR_infra_tc_oper_number_of_add_o_perations_ = "number-of-add-o-perations"
    Cisco_IOS_XR_infra_tc_oper_timeout_interval = 450971736
    Cisco_IOS_XR_infra_tc_oper_timeout_interval_ = "timeout-interval"
    Cisco_IOS_XR_infra_tc_oper_is_active = 1857111231
    Cisco_IOS_XR_infra_tc_oper_is_active_ = "is-active"
    Cisco_IOS_XR_infra_tc_oper_ldp_label = 1462070606
    Cisco_IOS_XR_infra_tc_oper_ldp_label_ = "ldp-label"
    Cisco_IOS_XR_infra_tc_oper_afs = 1706819009
    Cisco_IOS_XR_infra_tc_oper_afs_ = "afs"
    Cisco_IOS_XR_infra_tc_oper_maimum_latency_timestamp = 1602655158
    Cisco_IOS_XR_infra_tc_oper_maimum_latency_timestamp_ = "maimum-latency-timestamp"
    Cisco_IOS_XR_infra_tc_oper_tunnels = 1096015513
    Cisco_IOS_XR_infra_tc_oper_tunnels_ = "tunnels"
    Cisco_IOS_XR_infra_tc_oper_af = 1716690570
    Cisco_IOS_XR_infra_tc_oper_af_ = "af"
    Cisco_IOS_XR_infra_tc_oper_ipv6 = 1
    Cisco_IOS_XR_infra_tc_oper_ipv6_ = "ipv6"
    Cisco_IOS_XR_infra_tc_oper_collection_interval = 880323978
    Cisco_IOS_XR_infra_tc_oper_collection_interval_ = "collection-interval"
    Cisco_IOS_XR_infra_tc_oper_counters = 1327053922
    Cisco_IOS_XR_infra_tc_oper_counters_ = "counters"
    Cisco_IOS_XR_infra_tc_oper_collection_message_statistic = 1971243149
    Cisco_IOS_XR_infra_tc_oper_collection_message_statistic_ = "collection-message-statistic"
    Cisco_IOS_XR_infra_tc_oper_external_interfaces = 411029749
    Cisco_IOS_XR_infra_tc_oper_external_interfaces_ = "external-interfaces"
    Cisco_IOS_XR_infra_tc_oper_vrf_statistic = 1803324873
    Cisco_IOS_XR_infra_tc_oper_vrf_statistic_ = "vrf-statistic"
    Cisco_IOS_XR_infra_tc_oper_label = 1570796500
    Cisco_IOS_XR_infra_tc_oper_label_ = "label"
    Cisco_IOS_XR_infra_tc_oper_interface_name_xr = 1507773435
    Cisco_IOS_XR_infra_tc_oper_interface_name_xr_ = "interface-name-xr"
    Cisco_IOS_XR_infra_tc_oper_checkpoint_message_statistic = 1903544097
    Cisco_IOS_XR_infra_tc_oper_checkpoint_message_statistic_ = "checkpoint-message-statistic"
    Cisco_IOS_XR_infra_tc_oper_summary = 738895761
    Cisco_IOS_XR_infra_tc_oper_summary_ = "summary"
    Cisco_IOS_XR_infra_tc_oper_transmit_number_of_packets_switched = 1884913757
    Cisco_IOS_XR_infra_tc_oper_transmit_number_of_packets_switched_ = "transmit-number-of-packets-switched"
    Cisco_IOS_XR_infra_tc_oper_database_statistics_external_interface = 1482752521
    Cisco_IOS_XR_infra_tc_oper_database_statistics_external_interface_ = "database-statistics-external-interface"
    Cisco_IOS_XR_infra_tc_oper_number_of_delete_o_perations = 608041609
    Cisco_IOS_XR_infra_tc_oper_number_of_delete_o_perations_ = "number-of-delete-o-perations"
    Cisco_IOS_XR_infra_tc_oper_database_statistics_ipv4 = 1664769869
    Cisco_IOS_XR_infra_tc_oper_database_statistics_ipv4_ = "database-statistics-ipv4"
    Cisco_IOS_XR_infra_tc_oper_prefixes = 1405994391
    Cisco_IOS_XR_infra_tc_oper_prefixes_ = "prefixes"
    Cisco_IOS_XR_infra_tc_oper_transmit_bytes_per_second_switched = 1107634132
    Cisco_IOS_XR_infra_tc_oper_transmit_bytes_per_second_switched_ = "transmit-bytes-per-second-switched"
    Cisco_IOS_XR_infra_tc_oper_transmit_packets_per_second_switched = 143674761
    Cisco_IOS_XR_infra_tc_oper_transmit_packets_per_second_switched_ = "transmit-packets-per-second-switched"
    Cisco_IOS_XR_infra_tc_oper_packet_sent = 1990034274
    Cisco_IOS_XR_infra_tc_oper_packet_sent_ = "packet-sent"
