#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-infra-ceredundancymib-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-infra-ceredundancymib-cfg.yang


class ns(object):
    hash = 1555505900

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-ceredundancymib-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-ceredundancymib-cfg"

    prefix = "Cisco-IOS-XR-infra-ceredundancymib-cfg"

    Cisco_IOS_XR_infra_ceredundancymib_cfg_enable = 448570367
    Cisco_IOS_XR_infra_ceredundancymib_cfg_enable_ = "enable"
    Cisco_IOS_XR_infra_ceredundancymib_cfg_entity_redundancy = 408639166
    Cisco_IOS_XR_infra_ceredundancymib_cfg_entity_redundancy_ = "entity-redundancy"
    Cisco_IOS_XR_infra_ceredundancymib_cfg_status = 1950810920
    Cisco_IOS_XR_infra_ceredundancymib_cfg_status_ = "status"
    Cisco_IOS_XR_infra_ceredundancymib_cfg_switchover = 1885880734
    Cisco_IOS_XR_infra_ceredundancymib_cfg_switchover_ = "switchover"
