#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-lib-keychain-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-lib-keychain-oper.yang


class ns(object):
    hash = 1799726419

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-lib-keychain-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-lib-keychain-oper"

    prefix = "Cisco-IOS-XR-lib-keychain-oper"

    Cisco_IOS_XR_lib_keychain_oper_cryptographic_algorithm = 892302419
    Cisco_IOS_XR_lib_keychain_oper_cryptographic_algorithm_ = "cryptographic-algorithm"
    Cisco_IOS_XR_lib_keychain_oper_aes_256_cmac = 8
    Cisco_IOS_XR_lib_keychain_oper_aes_256_cmac_ = "aes-256-cmac"
    Cisco_IOS_XR_lib_keychain_oper_is_always_valid = 978060787
    Cisco_IOS_XR_lib_keychain_oper_is_always_valid_ = "is-always-valid"
    Cisco_IOS_XR_lib_keychain_oper_key_name = 1745432225
    Cisco_IOS_XR_lib_keychain_oper_key_name_ = "key-name"
    Cisco_IOS_XR_lib_keychain_oper_hmac_sha1_20 = 6
    Cisco_IOS_XR_lib_keychain_oper_hmac_sha1_20_ = "hmac-sha1-20"
    Cisco_IOS_XR_lib_keychain_oper_key_id = 1459848464
    Cisco_IOS_XR_lib_keychain_oper_key_id_ = "key-id"
    Cisco_IOS_XR_lib_keychain_oper_is_macsec_key = 2011729373
    Cisco_IOS_XR_lib_keychain_oper_is_macsec_key_ = "is-macsec-key"
    Cisco_IOS_XR_lib_keychain_oper_accept_tolerance = 1202063805
    Cisco_IOS_XR_lib_keychain_oper_accept_tolerance_ = "accept-tolerance"
    Cisco_IOS_XR_lib_keychain_oper_duration = 686902226
    Cisco_IOS_XR_lib_keychain_oper_duration_ = "duration"
    Cisco_IOS_XR_lib_keychain_oper_end = 1510734141
    Cisco_IOS_XR_lib_keychain_oper_end_ = "end"
    Cisco_IOS_XR_lib_keychain_oper_keys = 305539744
    Cisco_IOS_XR_lib_keychain_oper_keys_ = "keys"
    Cisco_IOS_XR_lib_keychain_oper_hmac_sha1_12 = 2
    Cisco_IOS_XR_lib_keychain_oper_hmac_sha1_12_ = "hmac-sha1-12"
    Cisco_IOS_XR_lib_keychain_oper_key_string = 287976500
    Cisco_IOS_XR_lib_keychain_oper_key_string_ = "key-string"
    Cisco_IOS_XR_lib_keychain_oper_is_valid_now = 975836887
    Cisco_IOS_XR_lib_keychain_oper_is_valid_now_ = "is-valid-now"
    Cisco_IOS_XR_lib_keychain_oper_accept_lifetime = 339371350
    Cisco_IOS_XR_lib_keychain_oper_accept_lifetime_ = "accept-lifetime"
    Cisco_IOS_XR_lib_keychain_oper_aes_128_cmac_96 = 1
    Cisco_IOS_XR_lib_keychain_oper_aes_128_cmac_96_ = "aes-128-cmac-96"
    Cisco_IOS_XR_lib_keychain_oper_hmac_sha_256 = 10
    Cisco_IOS_XR_lib_keychain_oper_hmac_sha_256_ = "hmac-sha-256"
    Cisco_IOS_XR_lib_keychain_oper_send_lifetime = 84392676
    Cisco_IOS_XR_lib_keychain_oper_send_lifetime_ = "send-lifetime"
    Cisco_IOS_XR_lib_keychain_oper_aes_128_cmac = 7
    Cisco_IOS_XR_lib_keychain_oper_aes_128_cmac_ = "aes-128-cmac"
    Cisco_IOS_XR_lib_keychain_oper_keychain = 233700939
    Cisco_IOS_XR_lib_keychain_oper_keychain_ = "keychain"
    Cisco_IOS_XR_lib_keychain_oper_sha1 = 4
    Cisco_IOS_XR_lib_keychain_oper_sha1_ = "sha1"
    Cisco_IOS_XR_lib_keychain_oper_hmac_md5 = 5
    Cisco_IOS_XR_lib_keychain_oper_hmac_md5_ = "hmac-md5"
    Cisco_IOS_XR_lib_keychain_oper_md5 = 3
    Cisco_IOS_XR_lib_keychain_oper_md5_ = "md5"
    Cisco_IOS_XR_lib_keychain_oper_password_type6 = 2
    Cisco_IOS_XR_lib_keychain_oper_password_type6_ = "password-type6"
    Cisco_IOS_XR_lib_keychain_oper_password_type7 = 0
    Cisco_IOS_XR_lib_keychain_oper_password_type7_ = "password-type7"
    Cisco_IOS_XR_lib_keychain_oper_not_configured = 0
    Cisco_IOS_XR_lib_keychain_oper_not_configured_ = "not-configured"
    Cisco_IOS_XR_lib_keychain_oper_macsec = 1063323203
    Cisco_IOS_XR_lib_keychain_oper_macsec_ = "macsec"
    Cisco_IOS_XR_lib_keychain_oper_type = 2040883914
    Cisco_IOS_XR_lib_keychain_oper_type_ = "type"
    Cisco_IOS_XR_lib_keychain_oper_key = 1348858669
    Cisco_IOS_XR_lib_keychain_oper_key_ = "key"
    Cisco_IOS_XR_lib_keychain_oper_hmac_sha1_96 = 9
    Cisco_IOS_XR_lib_keychain_oper_hmac_sha1_96_ = "hmac-sha1-96"
    Cisco_IOS_XR_lib_keychain_oper_start = 1011022838
    Cisco_IOS_XR_lib_keychain_oper_start_ = "start"
