#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-qos-ma-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-qos-ma-cfg.yang


class ns(object):
    hash = 206670871

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-qos-ma-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-qos-ma-cfg"

    prefix = "Cisco-IOS-XR-qos-ma-cfg"

    Cisco_IOS_XR_qos_ma_cfg_fabric_service_policy = 832396082
    Cisco_IOS_XR_qos_ma_cfg_fabric_service_policy_ = "fabric-service-policy"
    Cisco_IOS_XR_qos_ma_cfg_service_policy_qos = 1926793903
    Cisco_IOS_XR_qos_ma_cfg_service_policy_qos_ = "service-policy-qos"
    Cisco_IOS_XR_qos_ma_cfg_resource_id = 1483437234
    Cisco_IOS_XR_qos_ma_cfg_resource_id_ = "resource-id"
    Cisco_IOS_XR_qos_ma_cfg_service_fragment_parent_policy = 1136267411
    Cisco_IOS_XR_qos_ma_cfg_service_fragment_parent_policy_ = "service-fragment-parent-policy"
    Cisco_IOS_XR_qos_ma_cfg_user_defined = 4
    Cisco_IOS_XR_qos_ma_cfg_user_defined_ = "user-defined"
    Cisco_IOS_XR_qos_ma_cfg_subscriber_group_name = 1185747361
    Cisco_IOS_XR_qos_ma_cfg_subscriber_group_name_ = "subscriber-group-name"
    Cisco_IOS_XR_qos_ma_cfg_pac = 1207144057
    Cisco_IOS_XR_qos_ma_cfg_pac_ = "pac"
    Cisco_IOS_XR_qos_ma_cfg_not_supported = 0
    Cisco_IOS_XR_qos_ma_cfg_not_supported_ = "not-supported"
    Cisco_IOS_XR_qos_ma_cfg_spi_name = 677743111
    Cisco_IOS_XR_qos_ma_cfg_spi_name_ = "spi-name"
    Cisco_IOS_XR_qos_ma_cfg_layer2 = 1
    Cisco_IOS_XR_qos_ma_cfg_layer2_ = "layer2"
    Cisco_IOS_XR_qos_ma_cfg_cac = 2021997852
    Cisco_IOS_XR_qos_ma_cfg_cac_ = "cac"
    Cisco_IOS_XR_qos_ma_cfg_layer1 = 8
    Cisco_IOS_XR_qos_ma_cfg_layer1_ = "layer1"
    Cisco_IOS_XR_qos_ma_cfg_policy_merge = 2010433750
    Cisco_IOS_XR_qos_ma_cfg_policy_merge_ = "policy-merge"
    Cisco_IOS_XR_qos_ma_cfg_service_policy_name = 2029956236
    Cisco_IOS_XR_qos_ma_cfg_service_policy_name_ = "service-policy-name"
    Cisco_IOS_XR_qos_ma_cfg_subscriber_parent_policy = 32891036
    Cisco_IOS_XR_qos_ma_cfg_subscriber_parent_policy_ = "subscriber-parent-policy"
    Cisco_IOS_XR_qos_ma_cfg_account_type = 1779800702
    Cisco_IOS_XR_qos_ma_cfg_account_type_ = "account-type"
    Cisco_IOS_XR_qos_ma_cfg_subscriber_group_names = 1083259955
    Cisco_IOS_XR_qos_ma_cfg_subscriber_group_names_ = "subscriber-group-names"
    Cisco_IOS_XR_qos_ma_cfg_subscriber_parent = 1246314376
    Cisco_IOS_XR_qos_ma_cfg_subscriber_parent_ = "subscriber-parent"
    Cisco_IOS_XR_qos_ma_cfg_service_policy = 472004407
    Cisco_IOS_XR_qos_ma_cfg_service_policy_ = "service-policy"
    Cisco_IOS_XR_qos_ma_cfg_nolayer2 = 2
    Cisco_IOS_XR_qos_ma_cfg_nolayer2_ = "nolayer2"
    Cisco_IOS_XR_qos_ma_cfg_input = 1427240772
    Cisco_IOS_XR_qos_ma_cfg_input_ = "input"
    Cisco_IOS_XR_qos_ma_cfg_qos = 2021583496
    Cisco_IOS_XR_qos_ma_cfg_qos_ = "qos"
    Cisco_IOS_XR_qos_ma_cfg_output = 171341581
    Cisco_IOS_XR_qos_ma_cfg_output_ = "output"
    Cisco_IOS_XR_qos_ma_cfg_l1_user_defined = 163739894
    Cisco_IOS_XR_qos_ma_cfg_l1_user_defined_ = "l1-user-defined"
    Cisco_IOS_XR_qos_ma_cfg_subscriber_group_string = 928220775
    Cisco_IOS_XR_qos_ma_cfg_subscriber_group_string_ = "subscriber-group-string"
