#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-opticalotsmib-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-opticalotsmib-cfg.yang


class ns(object):
    hash = 683676811

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-opticalotsmib-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-opticalotsmib-cfg"

    prefix = "Cisco-IOS-XR-opticalotsmib-cfg"

    Cisco_IOS_XR_opticalotsmib_cfg_enable = 448570367
    Cisco_IOS_XR_opticalotsmib_cfg_enable_ = "enable"
    Cisco_IOS_XR_opticalotsmib_cfg_optical_ots = 94925026
    Cisco_IOS_XR_opticalotsmib_cfg_optical_ots_ = "optical-ots"
