#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-ip-pfilter-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-ip-pfilter-cfg.yang


class ns(object):
    hash = 713344180

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-pfilter-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-pfilter-cfg"

    prefix = "Cisco-IOS-XR-ip-pfilter-cfg"

    Cisco_IOS_XR_ip_pfilter_cfg_outbound = 1680805655
    Cisco_IOS_XR_ip_pfilter_cfg_outbound_ = "outbound"
    Cisco_IOS_XR_ip_pfilter_cfg_acl_name_array = 2042179304
    Cisco_IOS_XR_ip_pfilter_cfg_acl_name_array_ = "acl-name-array"
    Cisco_IOS_XR_ip_pfilter_cfg_name = 1998270519
    Cisco_IOS_XR_ip_pfilter_cfg_name_ = "name"
    Cisco_IOS_XR_ip_pfilter_cfg_hardware_count = 2095700049
    Cisco_IOS_XR_ip_pfilter_cfg_hardware_count_ = "hardware-count"
    Cisco_IOS_XR_ip_pfilter_cfg_inbound = 1227481211
    Cisco_IOS_XR_ip_pfilter_cfg_inbound_ = "inbound"
    Cisco_IOS_XR_ip_pfilter_cfg_es_packet_filter = 2141425191
    Cisco_IOS_XR_ip_pfilter_cfg_es_packet_filter_ = "es-packet-filter"
    Cisco_IOS_XR_ip_pfilter_cfg_is_common_array = 48995736
    Cisco_IOS_XR_ip_pfilter_cfg_is_common_array_ = "is-common-array"
    Cisco_IOS_XR_ip_pfilter_cfg_common_acl_name = 1037223637
    Cisco_IOS_XR_ip_pfilter_cfg_common_acl_name_ = "common-acl-name"
    Cisco_IOS_XR_ip_pfilter_cfg_ipv4_packet_filter = 1795623773
    Cisco_IOS_XR_ip_pfilter_cfg_ipv4_packet_filter_ = "ipv4-packet-filter"
    Cisco_IOS_XR_ip_pfilter_cfg_interface_statistics = 1870816912
    Cisco_IOS_XR_ip_pfilter_cfg_interface_statistics_ = "interface-statistics"
    Cisco_IOS_XR_ip_pfilter_cfg_do_not_use = 1852389738
    Cisco_IOS_XR_ip_pfilter_cfg_do_not_use_ = "do-not-use"
    Cisco_IOS_XR_ip_pfilter_cfg_ipv6_packet_filter = 434455398
    Cisco_IOS_XR_ip_pfilter_cfg_ipv6_packet_filter_ = "ipv6-packet-filter"
    Cisco_IOS_XR_ip_pfilter_cfg_compression_level = 1185651479
    Cisco_IOS_XR_ip_pfilter_cfg_compression_level_ = "compression-level"
