#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-crypto-act.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-crypto-act.yang


class ns(object):
    hash = 1533670067

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-crypto-act"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-crypto-act"

    prefix = "Cisco-IOS-XR-crypto-act"

    Cisco_IOS_XR_crypto_act_key_generate_rsa_usage_keys = 557951729
    Cisco_IOS_XR_crypto_act_key_generate_rsa_usage_keys_ = "key-generate-rsa-usage-keys"
    Cisco_IOS_XR_crypto_act_path = 1002915403
    Cisco_IOS_XR_crypto_act_path_ = "path"
    Cisco_IOS_XR_crypto_act_key_generate_ecdsa = 1303200634
    Cisco_IOS_XR_crypto_act_key_generate_ecdsa_ = "key-generate-ecdsa"
    Cisco_IOS_XR_crypto_act_rpc_key_import_authentication_rsa = 1779401070
    Cisco_IOS_XR_crypto_act_rpc_key_import_authentication_rsa_ = "rpc-key-import-authentication-rsa"
    Cisco_IOS_XR_crypto_act_ca_trustpool_import_url = 1267282735
    Cisco_IOS_XR_crypto_act_ca_trustpool_import_url_ = "ca-trustpool-import-url"
    Cisco_IOS_XR_crypto_act_ca_enroll = 1567840650
    Cisco_IOS_XR_crypto_act_ca_enroll_ = "ca-enroll"
    Cisco_IOS_XR_crypto_act_result = 401396173
    Cisco_IOS_XR_crypto_act_result_ = "result"
    Cisco_IOS_XR_crypto_act_nistp521 = 2
    Cisco_IOS_XR_crypto_act_nistp521_ = "nistp521"
    Cisco_IOS_XR_crypto_act_rpc_ca_authenticate = 1111078072
    Cisco_IOS_XR_crypto_act_rpc_ca_authenticate_ = "rpc-ca-authenticate"
    Cisco_IOS_XR_crypto_act_rpc_ca_trustpool_import_url = 1611079287
    Cisco_IOS_XR_crypto_act_rpc_ca_trustpool_import_url_ = "rpc-ca-trustpool-import-url"
    Cisco_IOS_XR_crypto_act_rpc_ca_import_certificate = 464131847
    Cisco_IOS_XR_crypto_act_rpc_ca_import_certificate_ = "rpc-ca-import-certificate"
    Cisco_IOS_XR_crypto_act_ca_trustpool_import_url_clean = 1115771205
    Cisco_IOS_XR_crypto_act_ca_trustpool_import_url_clean_ = "ca-trustpool-import-url-clean"
    Cisco_IOS_XR_crypto_act_key_generate_rsa_general_keys = 2086134677
    Cisco_IOS_XR_crypto_act_key_generate_rsa_general_keys_ = "key-generate-rsa-general-keys"
    Cisco_IOS_XR_crypto_act_server_name = 1912911616
    Cisco_IOS_XR_crypto_act_server_name_ = "server-name"
    Cisco_IOS_XR_crypto_act_rpc_key_zeroize_rsa = 1307007149
    Cisco_IOS_XR_crypto_act_rpc_key_zeroize_rsa_ = "rpc-key-zeroize-rsa"
    Cisco_IOS_XR_crypto_act_rpc_key_generate_dsa = 615566480
    Cisco_IOS_XR_crypto_act_rpc_key_generate_dsa_ = "rpc-key-generate-dsa"
    Cisco_IOS_XR_crypto_act_name = 1998270519
    Cisco_IOS_XR_crypto_act_name_ = "name"
    Cisco_IOS_XR_crypto_act_key_modulus = 21686476
    Cisco_IOS_XR_crypto_act_key_modulus_ = "key-modulus"
    Cisco_IOS_XR_crypto_act_ca_import_certificate = 41395568
    Cisco_IOS_XR_crypto_act_ca_import_certificate_ = "ca-import-certificate"
    Cisco_IOS_XR_crypto_act_rpc_key_zeroize_authentication_rsa = 879695243
    Cisco_IOS_XR_crypto_act_rpc_key_zeroize_authentication_rsa_ = "rpc-key-zeroize-authentication-rsa"
    Cisco_IOS_XR_crypto_act_key_label = 1475693758
    Cisco_IOS_XR_crypto_act_key_label_ = "key-label"
    Cisco_IOS_XR_crypto_act_info = 2062105651
    Cisco_IOS_XR_crypto_act_info_ = "info"
    Cisco_IOS_XR_crypto_act_key_generate_rsa = 591308909
    Cisco_IOS_XR_crypto_act_key_generate_rsa_ = "key-generate-rsa"
    Cisco_IOS_XR_crypto_act_url = 1560781157
    Cisco_IOS_XR_crypto_act_url_ = "url"
    Cisco_IOS_XR_crypto_act_device = 617911018
    Cisco_IOS_XR_crypto_act_device_ = "device"
    Cisco_IOS_XR_crypto_act_rpc_ca_trustpool_import_url_clean = 97830509
    Cisco_IOS_XR_crypto_act_rpc_ca_trustpool_import_url_clean_ = "rpc-ca-trustpool-import-url-clean"
    Cisco_IOS_XR_crypto_act_ca_authenticate = 1005830483
    Cisco_IOS_XR_crypto_act_ca_authenticate_ = "ca-authenticate"
    Cisco_IOS_XR_crypto_act_rpc_key_generate_rsa_general_keys = 720103466
    Cisco_IOS_XR_crypto_act_rpc_key_generate_rsa_general_keys_ = "rpc-key-generate-rsa-general-keys"
    Cisco_IOS_XR_crypto_act_rpc_ca_enroll = 713410403
    Cisco_IOS_XR_crypto_act_rpc_ca_enroll_ = "rpc-ca-enroll"
    Cisco_IOS_XR_crypto_act_key_zeroize_rsa = 2049523248
    Cisco_IOS_XR_crypto_act_key_zeroize_rsa_ = "key-zeroize-rsa"
    Cisco_IOS_XR_crypto_act_rpc_ca_cancel_enroll = 1886717618
    Cisco_IOS_XR_crypto_act_rpc_ca_cancel_enroll_ = "rpc-ca-cancel-enroll"
    Cisco_IOS_XR_crypto_act_key_generate_dsa = 1375015948
    Cisco_IOS_XR_crypto_act_key_generate_dsa_ = "key-generate-dsa"
    Cisco_IOS_XR_crypto_act_uri = 1237918064
    Cisco_IOS_XR_crypto_act_uri_ = "uri"
    Cisco_IOS_XR_crypto_act_rpc_ca_crl_request = 861784944
    Cisco_IOS_XR_crypto_act_rpc_ca_crl_request_ = "rpc-ca-crl-request"
    Cisco_IOS_XR_crypto_act_certificate = 929395308
    Cisco_IOS_XR_crypto_act_certificate_ = "certificate"
    Cisco_IOS_XR_crypto_act_key_zeroize_ecdsa = 785221648
    Cisco_IOS_XR_crypto_act_key_zeroize_ecdsa_ = "key-zeroize-ecdsa"
    Cisco_IOS_XR_crypto_act_ca_crl_request = 542374571
    Cisco_IOS_XR_crypto_act_ca_crl_request_ = "ca-crl-request"
    Cisco_IOS_XR_crypto_act_rpc_key_generate_ecdsa = 1650408475
    Cisco_IOS_XR_crypto_act_rpc_key_generate_ecdsa_ = "rpc-key-generate-ecdsa"
    Cisco_IOS_XR_crypto_act_nistp384 = 1
    Cisco_IOS_XR_crypto_act_nistp384_ = "nistp384"
    Cisco_IOS_XR_crypto_act_rpc_key_generate_rsa = 1897219148
    Cisco_IOS_XR_crypto_act_rpc_key_generate_rsa_ = "rpc-key-generate-rsa"
    Cisco_IOS_XR_crypto_act_ca_cancel_enroll = 663911162
    Cisco_IOS_XR_crypto_act_ca_cancel_enroll_ = "ca-cancel-enroll"
    Cisco_IOS_XR_crypto_act_rpc_key_zeroize_ecdsa = 822429278
    Cisco_IOS_XR_crypto_act_rpc_key_zeroize_ecdsa_ = "rpc-key-zeroize-ecdsa"
    Cisco_IOS_XR_crypto_act_rpc_key_generate_rsa_usage_keys = 1772593759
    Cisco_IOS_XR_crypto_act_rpc_key_generate_rsa_usage_keys_ = "rpc-key-generate-rsa-usage-keys"
    Cisco_IOS_XR_crypto_act_key_import_authentication_rsa = 804100618
    Cisco_IOS_XR_crypto_act_key_import_authentication_rsa_ = "key-import-authentication-rsa"
    Cisco_IOS_XR_crypto_act_key_zeroize_dsa = 1056648556
    Cisco_IOS_XR_crypto_act_key_zeroize_dsa_ = "key-zeroize-dsa"
    Cisco_IOS_XR_crypto_act_rpc_key_zeroize_dsa = 883238905
    Cisco_IOS_XR_crypto_act_rpc_key_zeroize_dsa_ = "rpc-key-zeroize-dsa"
    Cisco_IOS_XR_crypto_act_nistp256 = 0
    Cisco_IOS_XR_crypto_act_nistp256_ = "nistp256"
    Cisco_IOS_XR_crypto_act_key_zeroize_authentication_rsa = 1788711478
    Cisco_IOS_XR_crypto_act_key_zeroize_authentication_rsa_ = "key-zeroize-authentication-rsa"
