#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-sysadmin-show-trace-instagt.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-sysadmin-show-trace-instagt.yang


class ns(object):
    hash = 1202154136

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-show-trace-instagt"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-show-trace-instagt"

    prefix = "Cisco-IOS-XR-sysadmin-show-trace-instagt"

    Cisco_IOS_XR_sysadmin_show_trace_instagt_location_name = 1667135771
    Cisco_IOS_XR_sysadmin_show_trace_instagt_location_name_ = "location_name"
    Cisco_IOS_XR_sysadmin_show_trace_instagt_location = 1827424758
    Cisco_IOS_XR_sysadmin_show_trace_instagt_location_ = "location"
    Cisco_IOS_XR_sysadmin_show_trace_instagt_trace = 1896625767
    Cisco_IOS_XR_sysadmin_show_trace_instagt_trace_ = "trace"
    Cisco_IOS_XR_sysadmin_show_trace_instagt_instagt = 1878163195
    Cisco_IOS_XR_sysadmin_show_trace_instagt_instagt_ = "instagt"
    Cisco_IOS_XR_sysadmin_show_trace_instagt_trace_blocks = 1645607271
    Cisco_IOS_XR_sysadmin_show_trace_instagt_trace_blocks_ = "trace-blocks"
    Cisco_IOS_XR_sysadmin_show_trace_instagt_all_options = 436979003
    Cisco_IOS_XR_sysadmin_show_trace_instagt_all_options_ = "all-options"
    Cisco_IOS_XR_sysadmin_show_trace_instagt_option = 265226539
    Cisco_IOS_XR_sysadmin_show_trace_instagt_option_ = "option"
    Cisco_IOS_XR_sysadmin_show_trace_instagt_buffer = 1428421018
    Cisco_IOS_XR_sysadmin_show_trace_instagt_buffer_ = "buffer"
    Cisco_IOS_XR_sysadmin_show_trace_instagt_data = 535242711
    Cisco_IOS_XR_sysadmin_show_trace_instagt_data_ = "data"
