#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-ipv4-hsrp-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-ipv4-hsrp-cfg.yang


class ns(object):
    hash = 2063269333

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-hsrp-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-hsrp-cfg"

    prefix = "Cisco-IOS-XR-ipv4-hsrp-cfg"

    Cisco_IOS_XR_ipv4_hsrp_cfg_slave_groups = 1326145645
    Cisco_IOS_XR_ipv4_hsrp_cfg_slave_groups_ = "slave-groups"
    Cisco_IOS_XR_ipv4_hsrp_cfg_version2 = 443825587
    Cisco_IOS_XR_ipv4_hsrp_cfg_version2_ = "version2"
    Cisco_IOS_XR_ipv4_hsrp_cfg_session_name = 948578491
    Cisco_IOS_XR_ipv4_hsrp_cfg_session_name_ = "session-name"
    Cisco_IOS_XR_ipv4_hsrp_cfg_secondary_ipv4_address = 1950605244
    Cisco_IOS_XR_ipv4_hsrp_cfg_secondary_ipv4_address_ = "secondary-ipv4-address"
    Cisco_IOS_XR_ipv4_hsrp_cfg_auto_configure = 2111796603
    Cisco_IOS_XR_ipv4_hsrp_cfg_auto_configure_ = "auto-configure"
    Cisco_IOS_XR_ipv4_hsrp_cfg_group = 1540685982
    Cisco_IOS_XR_ipv4_hsrp_cfg_group_ = "group"
    Cisco_IOS_XR_ipv4_hsrp_cfg_priority = 1346277862
    Cisco_IOS_XR_ipv4_hsrp_cfg_priority_ = "priority"
    Cisco_IOS_XR_ipv4_hsrp_cfg_global_ipv6_addresses = 1221658221
    Cisco_IOS_XR_ipv4_hsrp_cfg_global_ipv6_addresses_ = "global-ipv6-addresses"
    Cisco_IOS_XR_ipv4_hsrp_cfg_detection_multiplier = 1584191488
    Cisco_IOS_XR_ipv4_hsrp_cfg_detection_multiplier_ = "detection-multiplier"
    Cisco_IOS_XR_ipv4_hsrp_cfg_hsrp = 1071348515
    Cisco_IOS_XR_ipv4_hsrp_cfg_hsrp_ = "hsrp"
    Cisco_IOS_XR_ipv4_hsrp_cfg_hello_msec_flag = 832842614
    Cisco_IOS_XR_ipv4_hsrp_cfg_hello_msec_flag_ = "hello-msec-flag"
    Cisco_IOS_XR_ipv4_hsrp_cfg_primary_ipv4_address = 909234261
    Cisco_IOS_XR_ipv4_hsrp_cfg_primary_ipv4_address_ = "primary-ipv4-address"
    Cisco_IOS_XR_ipv4_hsrp_cfg_interface = 221572658
    Cisco_IOS_XR_ipv4_hsrp_cfg_interface_ = "interface"
    Cisco_IOS_XR_ipv4_hsrp_cfg_mac_refresh = 681701338
    Cisco_IOS_XR_ipv4_hsrp_cfg_mac_refresh_ = "mac-refresh"
    Cisco_IOS_XR_ipv4_hsrp_cfg_logging = 547433513
    Cisco_IOS_XR_ipv4_hsrp_cfg_logging_ = "logging"
    Cisco_IOS_XR_ipv4_hsrp_cfg_hello_msec = 701835117
    Cisco_IOS_XR_ipv4_hsrp_cfg_hello_msec_ = "hello-msec"
    Cisco_IOS_XR_ipv4_hsrp_cfg_version1 = 988573343
    Cisco_IOS_XR_ipv4_hsrp_cfg_version1_ = "version1"
    Cisco_IOS_XR_ipv4_hsrp_cfg_secondary_ipv4_addresses = 946991591
    Cisco_IOS_XR_ipv4_hsrp_cfg_secondary_ipv4_addresses_ = "secondary-ipv4-addresses"
    Cisco_IOS_XR_ipv4_hsrp_cfg_reload_delay = 524674778
    Cisco_IOS_XR_ipv4_hsrp_cfg_reload_delay_ = "reload-delay"
    Cisco_IOS_XR_ipv4_hsrp_cfg_hold_msec = 704709724
    Cisco_IOS_XR_ipv4_hsrp_cfg_hold_msec_ = "hold-msec"
    Cisco_IOS_XR_ipv4_hsrp_cfg_state_change_disable = 451551848
    Cisco_IOS_XR_ipv4_hsrp_cfg_state_change_disable_ = "state-change-disable"
    Cisco_IOS_XR_ipv4_hsrp_cfg_slave_group = 1554296456
    Cisco_IOS_XR_ipv4_hsrp_cfg_slave_group_ = "slave-group"
    Cisco_IOS_XR_ipv4_hsrp_cfg_groups = 575296803
    Cisco_IOS_XR_ipv4_hsrp_cfg_groups_ = "groups"
    Cisco_IOS_XR_ipv4_hsrp_cfg_enable = 448570367
    Cisco_IOS_XR_ipv4_hsrp_cfg_enable_ = "enable"
    Cisco_IOS_XR_ipv4_hsrp_cfg_virtual_ip_learn = 950511401
    Cisco_IOS_XR_ipv4_hsrp_cfg_virtual_ip_learn_ = "virtual-ip-learn"
    Cisco_IOS_XR_ipv4_hsrp_cfg_link_local_ipv6_address = 1693175395
    Cisco_IOS_XR_ipv4_hsrp_cfg_link_local_ipv6_address_ = "link-local-ipv6-address"
    Cisco_IOS_XR_ipv4_hsrp_cfg_interface_name = 1322899300
    Cisco_IOS_XR_ipv4_hsrp_cfg_interface_name_ = "interface-name"
    Cisco_IOS_XR_ipv4_hsrp_cfg_tracked_interface = 90856343
    Cisco_IOS_XR_ipv4_hsrp_cfg_tracked_interface_ = "tracked-interface"
    Cisco_IOS_XR_ipv4_hsrp_cfg_use_bia = 1933691307
    Cisco_IOS_XR_ipv4_hsrp_cfg_use_bia_ = "use-bia"
    Cisco_IOS_XR_ipv4_hsrp_cfg_ipv4 = 268057062
    Cisco_IOS_XR_ipv4_hsrp_cfg_ipv4_ = "ipv4"
    Cisco_IOS_XR_ipv4_hsrp_cfg_authentication = 838318934
    Cisco_IOS_XR_ipv4_hsrp_cfg_authentication_ = "authentication"
    Cisco_IOS_XR_ipv4_hsrp_cfg_manual = 0
    Cisco_IOS_XR_ipv4_hsrp_cfg_manual_ = "manual"
    Cisco_IOS_XR_ipv4_hsrp_cfg_interval = 559952988
    Cisco_IOS_XR_ipv4_hsrp_cfg_interval_ = "interval"
    Cisco_IOS_XR_ipv4_hsrp_cfg_group_number = 211814894
    Cisco_IOS_XR_ipv4_hsrp_cfg_group_number_ = "group-number"
    Cisco_IOS_XR_ipv4_hsrp_cfg_tracked_objects = 1606552237
    Cisco_IOS_XR_ipv4_hsrp_cfg_tracked_objects_ = "tracked-objects"
    Cisco_IOS_XR_ipv4_hsrp_cfg_ipv6 = 1228132394
    Cisco_IOS_XR_ipv4_hsrp_cfg_ipv6_ = "ipv6"
    Cisco_IOS_XR_ipv4_hsrp_cfg_auto = 1
    Cisco_IOS_XR_ipv4_hsrp_cfg_auto_ = "auto"
    Cisco_IOS_XR_ipv4_hsrp_cfg_tracked_interfaces = 1525418948
    Cisco_IOS_XR_ipv4_hsrp_cfg_tracked_interfaces_ = "tracked-interfaces"
    Cisco_IOS_XR_ipv4_hsrp_cfg_preempt = 419787493
    Cisco_IOS_XR_ipv4_hsrp_cfg_preempt_ = "preempt"
    Cisco_IOS_XR_ipv4_hsrp_cfg_bfd = 788285710
    Cisco_IOS_XR_ipv4_hsrp_cfg_bfd_ = "bfd"
    Cisco_IOS_XR_ipv4_hsrp_cfg_follow = 818518637
    Cisco_IOS_XR_ipv4_hsrp_cfg_follow_ = "follow"
    Cisco_IOS_XR_ipv4_hsrp_cfg_address = 1266954393
    Cisco_IOS_XR_ipv4_hsrp_cfg_address_ = "address"
    Cisco_IOS_XR_ipv4_hsrp_cfg_priority_decrement = 1718444560
    Cisco_IOS_XR_ipv4_hsrp_cfg_priority_decrement_ = "priority-decrement"
    Cisco_IOS_XR_ipv4_hsrp_cfg_hold_sec = 947989150
    Cisco_IOS_XR_ipv4_hsrp_cfg_hold_sec_ = "hold-sec"
    Cisco_IOS_XR_ipv4_hsrp_cfg_tracked_object = 241657522
    Cisco_IOS_XR_ipv4_hsrp_cfg_tracked_object_ = "tracked-object"
    Cisco_IOS_XR_ipv4_hsrp_cfg_minimum_delay = 1159887402
    Cisco_IOS_XR_ipv4_hsrp_cfg_minimum_delay_ = "minimum-delay"
    Cisco_IOS_XR_ipv4_hsrp_cfg_interfaces = 321503962
    Cisco_IOS_XR_ipv4_hsrp_cfg_interfaces_ = "interfaces"
    Cisco_IOS_XR_ipv4_hsrp_cfg_hello_sec = 2020188014
    Cisco_IOS_XR_ipv4_hsrp_cfg_hello_sec_ = "hello-sec"
    Cisco_IOS_XR_ipv4_hsrp_cfg_timers = 1742815315
    Cisco_IOS_XR_ipv4_hsrp_cfg_timers_ = "timers"
    Cisco_IOS_XR_ipv4_hsrp_cfg_hold_msec_flag = 959952986
    Cisco_IOS_XR_ipv4_hsrp_cfg_hold_msec_flag_ = "hold-msec-flag"
    Cisco_IOS_XR_ipv4_hsrp_cfg_virtual_mac_address = 1948414206
    Cisco_IOS_XR_ipv4_hsrp_cfg_virtual_mac_address_ = "virtual-mac-address"
    Cisco_IOS_XR_ipv4_hsrp_cfg_redirects_disable = 1995879334
    Cisco_IOS_XR_ipv4_hsrp_cfg_redirects_disable_ = "redirects-disable"
    Cisco_IOS_XR_ipv4_hsrp_cfg_delay = 200515694
    Cisco_IOS_XR_ipv4_hsrp_cfg_delay_ = "delay"
    Cisco_IOS_XR_ipv4_hsrp_cfg_slave_group_number = 1877231005
    Cisco_IOS_XR_ipv4_hsrp_cfg_slave_group_number_ = "slave-group-number"
    Cisco_IOS_XR_ipv4_hsrp_cfg_object_name = 657753792
    Cisco_IOS_XR_ipv4_hsrp_cfg_object_name_ = "object-name"
    Cisco_IOS_XR_ipv4_hsrp_cfg_legacy = 2
    Cisco_IOS_XR_ipv4_hsrp_cfg_legacy_ = "legacy"
    Cisco_IOS_XR_ipv4_hsrp_cfg_global_ipv6_address = 2013048288
    Cisco_IOS_XR_ipv4_hsrp_cfg_global_ipv6_address_ = "global-ipv6-address"
