#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-ncs5500-coherent-portmode-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-ncs5500-coherent-portmode-oper.yang


class ns(object):
    hash = 1512241974

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ncs5500-coherent-portmode-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ncs5500-coherent-portmode-oper"

    prefix = "Cisco-IOS-XR-ncs5500-coherent-portmode-oper"

    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_port_mode_info = 1632120413
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_port_mode_info_ = "port-mode-info"
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_speed = 1423237997
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_speed_ = "speed"
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_fec = 182018328
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_fec_ = "fec"
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_diff = 406548259
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_diff_ = "diff"
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_optics_name = 400947008
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_optics_name_ = "optics-name"
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_interface_name = 1322899300
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_interface_name_ = "interface-name"
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_controller_port_mode = 1344691009
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_controller_port_mode_ = "controller-port-mode"
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_modulation = 943580148
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_modulation_ = "modulation"
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_intf_name = 1900015443
    Cisco_IOS_XR_ncs5500_coherent_portmode_oper_intf_name_ = "intf-name"
