#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-mediasvr-linux-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-mediasvr-linux-oper.yang


class ns(object):
    hash = 1774127687

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mediasvr-linux-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mediasvr-linux-oper"

    prefix = "Cisco-IOS-XR-mediasvr-linux-oper"

    Cisco_IOS_XR_mediasvr_linux_oper_show_output = 1179770243
    Cisco_IOS_XR_mediasvr_linux_oper_show_output_ = "show-output"
    Cisco_IOS_XR_mediasvr_linux_oper_location_description = 187013583
    Cisco_IOS_XR_mediasvr_linux_oper_location_description_ = "location-description"
    Cisco_IOS_XR_mediasvr_linux_oper_location_descriptions = 987644990
    Cisco_IOS_XR_mediasvr_linux_oper_location_descriptions_ = "location-descriptions"
    Cisco_IOS_XR_mediasvr_linux_oper_all = 2031982792
    Cisco_IOS_XR_mediasvr_linux_oper_all_ = "all"
    Cisco_IOS_XR_mediasvr_linux_oper_media_svr = 767755381
    Cisco_IOS_XR_mediasvr_linux_oper_media_svr_ = "media-svr"
    Cisco_IOS_XR_mediasvr_linux_oper_node = 2084421367
    Cisco_IOS_XR_mediasvr_linux_oper_node_ = "node"
