#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-drivers-mpa-infra-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-drivers-mpa-infra-cfg.yang


class ns(object):
    hash = 2038584686

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-drivers-mpa-infra-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-drivers-mpa-infra-cfg"

    prefix = "Cisco-IOS-XR-drivers-mpa-infra-cfg"

    Cisco_IOS_XR_drivers_mpa_infra_cfg_hardware_module = 194943774
    Cisco_IOS_XR_drivers_mpa_infra_cfg_hardware_module_ = "hardware-module"
    Cisco_IOS_XR_drivers_mpa_infra_cfg_shutdown = 460723287
    Cisco_IOS_XR_drivers_mpa_infra_cfg_shutdown_ = "shutdown"
    Cisco_IOS_XR_drivers_mpa_infra_cfg_nodes = 650955465
    Cisco_IOS_XR_drivers_mpa_infra_cfg_nodes_ = "nodes"
    Cisco_IOS_XR_drivers_mpa_infra_cfg_node_name = 122353445
    Cisco_IOS_XR_drivers_mpa_infra_cfg_node_name_ = "node-name"
    Cisco_IOS_XR_drivers_mpa_infra_cfg_powered = 2
    Cisco_IOS_XR_drivers_mpa_infra_cfg_powered_ = "powered"
    Cisco_IOS_XR_drivers_mpa_infra_cfg_node = 2084421367
    Cisco_IOS_XR_drivers_mpa_infra_cfg_node_ = "node"
