#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-ip-iep-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-ip-iep-oper.yang


class ns(object):
    hash = 916454874

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-iep-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-iep-oper"

    prefix = "Cisco-IOS-XR-ip-iep-oper"

    Cisco_IOS_XR_ip_iep_oper_hop_type = 2122395161
    Cisco_IOS_XR_ip_iep_oper_hop_type_ = "hop-type"
    Cisco_IOS_XR_ip_iep_oper_mpls_label = 837233201
    Cisco_IOS_XR_ip_iep_oper_mpls_label_ = "mpls-label"
    Cisco_IOS_XR_ip_iep_oper_enabled = 0
    Cisco_IOS_XR_ip_iep_oper_enabled_ = "enabled"
    Cisco_IOS_XR_ip_iep_oper_names = 790727664
    Cisco_IOS_XR_ip_iep_oper_names_ = "names"
    Cisco_IOS_XR_ip_iep_oper_exclude = 1
    Cisco_IOS_XR_ip_iep_oper_exclude_ = "exclude"
    Cisco_IOS_XR_ip_iep_oper_exclude_srlg = 2
    Cisco_IOS_XR_ip_iep_oper_exclude_srlg_ = "exclude-srlg"
    Cisco_IOS_XR_ip_iep_oper_index = 827593980
    Cisco_IOS_XR_ip_iep_oper_index_ = "index"
    Cisco_IOS_XR_ip_iep_oper_name = 1998270519
    Cisco_IOS_XR_ip_iep_oper_name_ = "name"
    Cisco_IOS_XR_ip_iep_oper_loose = 1
    Cisco_IOS_XR_ip_iep_oper_loose_ = "loose"
    Cisco_IOS_XR_ip_iep_oper_explicit_paths = 1432404512
    Cisco_IOS_XR_ip_iep_oper_explicit_paths_ = "explicit-paths"
    Cisco_IOS_XR_ip_iep_oper_identifiers = 2120818111
    Cisco_IOS_XR_ip_iep_oper_identifiers_ = "identifiers"
    Cisco_IOS_XR_ip_iep_oper_path_name = 120196080
    Cisco_IOS_XR_ip_iep_oper_path_name_ = "path-name"
    Cisco_IOS_XR_ip_iep_oper_disabled = 1
    Cisco_IOS_XR_ip_iep_oper_disabled_ = "disabled"
    Cisco_IOS_XR_ip_iep_oper_strict = 0
    Cisco_IOS_XR_ip_iep_oper_strict_ = "strict"
    Cisco_IOS_XR_ip_iep_oper_address = 1266954393
    Cisco_IOS_XR_ip_iep_oper_address_ = "address"
    Cisco_IOS_XR_ip_iep_oper_identifier_id = 88741999
    Cisco_IOS_XR_ip_iep_oper_identifier_id_ = "identifier-id"
    Cisco_IOS_XR_ip_iep_oper_address_type = 1062059366
    Cisco_IOS_XR_ip_iep_oper_address_type_ = "address-type"
    Cisco_IOS_XR_ip_iep_oper_status = 1950810920
    Cisco_IOS_XR_ip_iep_oper_status_ = "status"
    Cisco_IOS_XR_ip_iep_oper_identifier = 1002883111
    Cisco_IOS_XR_ip_iep_oper_identifier_ = "identifier"
    Cisco_IOS_XR_ip_iep_oper_next = 0
    Cisco_IOS_XR_ip_iep_oper_next_ = "next"
    Cisco_IOS_XR_ip_iep_oper_if_index = 216876767
    Cisco_IOS_XR_ip_iep_oper_if_index_ = "if-index"
