#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-aaa-tacacs-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-aaa-tacacs-cfg.yang


class ns(object):
    hash = 2122138588

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-tacacs-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-tacacs-cfg"

    prefix = "Cisco-IOS-XR-aaa-tacacs-cfg"

    Cisco_IOS_XR_aaa_tacacs_cfg_tacacs_server_group = 1605689023
    Cisco_IOS_XR_aaa_tacacs_cfg_tacacs_server_group_ = "tacacs-server-group"
    Cisco_IOS_XR_aaa_tacacs_cfg_cs2 = 16
    Cisco_IOS_XR_aaa_tacacs_cfg_cs2_ = "cs2"
    Cisco_IOS_XR_aaa_tacacs_cfg_af13 = 14
    Cisco_IOS_XR_aaa_tacacs_cfg_af13_ = "af13"
    Cisco_IOS_XR_aaa_tacacs_cfg_cs1 = 8
    Cisco_IOS_XR_aaa_tacacs_cfg_cs1_ = "cs1"
    Cisco_IOS_XR_aaa_tacacs_cfg_tacacs = 1696327224
    Cisco_IOS_XR_aaa_tacacs_cfg_tacacs_ = "tacacs"
    Cisco_IOS_XR_aaa_tacacs_cfg_server_group_name = 179688880
    Cisco_IOS_XR_aaa_tacacs_cfg_server_group_name_ = "server-group-name"
    Cisco_IOS_XR_aaa_tacacs_cfg_af22 = 20
    Cisco_IOS_XR_aaa_tacacs_cfg_af22_ = "af22"
    Cisco_IOS_XR_aaa_tacacs_cfg_port_number = 1943255518
    Cisco_IOS_XR_aaa_tacacs_cfg_port_number_ = "port-number"
    Cisco_IOS_XR_aaa_tacacs_cfg_af32 = 28
    Cisco_IOS_XR_aaa_tacacs_cfg_af32_ = "af32"
    Cisco_IOS_XR_aaa_tacacs_cfg_af31 = 26
    Cisco_IOS_XR_aaa_tacacs_cfg_af31_ = "af31"
    Cisco_IOS_XR_aaa_tacacs_cfg_vrf = 1281310328
    Cisco_IOS_XR_aaa_tacacs_cfg_vrf_ = "vrf"
    Cisco_IOS_XR_aaa_tacacs_cfg_ef = 46
    Cisco_IOS_XR_aaa_tacacs_cfg_ef_ = "ef"
    Cisco_IOS_XR_aaa_tacacs_cfg_default = 0
    Cisco_IOS_XR_aaa_tacacs_cfg_default_ = "default"
    Cisco_IOS_XR_aaa_tacacs_cfg_tacacs_server_groups = 1489773233
    Cisco_IOS_XR_aaa_tacacs_cfg_tacacs_server_groups_ = "tacacs-server-groups"
    Cisco_IOS_XR_aaa_tacacs_cfg_private_servers = 617888648
    Cisco_IOS_XR_aaa_tacacs_cfg_private_servers_ = "private-servers"
    Cisco_IOS_XR_aaa_tacacs_cfg_ordering_index = 1251256028
    Cisco_IOS_XR_aaa_tacacs_cfg_ordering_index_ = "ordering-index"
    Cisco_IOS_XR_aaa_tacacs_cfg_cs6 = 48
    Cisco_IOS_XR_aaa_tacacs_cfg_cs6_ = "cs6"
    Cisco_IOS_XR_aaa_tacacs_cfg_af33 = 30
    Cisco_IOS_XR_aaa_tacacs_cfg_af33_ = "af33"
    Cisco_IOS_XR_aaa_tacacs_cfg_vrf_name = 2140916904
    Cisco_IOS_XR_aaa_tacacs_cfg_vrf_name_ = "vrf-name"
    Cisco_IOS_XR_aaa_tacacs_cfg_ipv4 = 268057062
    Cisco_IOS_XR_aaa_tacacs_cfg_ipv4_ = "ipv4"
    Cisco_IOS_XR_aaa_tacacs_cfg_af11 = 10
    Cisco_IOS_XR_aaa_tacacs_cfg_af11_ = "af11"
    Cisco_IOS_XR_aaa_tacacs_cfg_host = 1711485895
    Cisco_IOS_XR_aaa_tacacs_cfg_host_ = "host"
    Cisco_IOS_XR_aaa_tacacs_cfg_timeout = 614210192
    Cisco_IOS_XR_aaa_tacacs_cfg_timeout_ = "timeout"
    Cisco_IOS_XR_aaa_tacacs_cfg_ip_address = 36594129
    Cisco_IOS_XR_aaa_tacacs_cfg_ip_address_ = "ip-address"
    Cisco_IOS_XR_aaa_tacacs_cfg_cs3 = 24
    Cisco_IOS_XR_aaa_tacacs_cfg_cs3_ = "cs3"
    Cisco_IOS_XR_aaa_tacacs_cfg_ipv6 = 1228132394
    Cisco_IOS_XR_aaa_tacacs_cfg_ipv6_ = "ipv6"
    Cisco_IOS_XR_aaa_tacacs_cfg_single_connect = 1740593146
    Cisco_IOS_XR_aaa_tacacs_cfg_single_connect_ = "single-connect"
    Cisco_IOS_XR_aaa_tacacs_cfg_af42 = 36
    Cisco_IOS_XR_aaa_tacacs_cfg_af42_ = "af42"
    Cisco_IOS_XR_aaa_tacacs_cfg_af12 = 12
    Cisco_IOS_XR_aaa_tacacs_cfg_af12_ = "af12"
    Cisco_IOS_XR_aaa_tacacs_cfg_private_server = 266885179
    Cisco_IOS_XR_aaa_tacacs_cfg_private_server_ = "private-server"
    Cisco_IOS_XR_aaa_tacacs_cfg_af43 = 38
    Cisco_IOS_XR_aaa_tacacs_cfg_af43_ = "af43"
    Cisco_IOS_XR_aaa_tacacs_cfg_cs7 = 56
    Cisco_IOS_XR_aaa_tacacs_cfg_cs7_ = "cs7"
    Cisco_IOS_XR_aaa_tacacs_cfg_dscp = 1118112132
    Cisco_IOS_XR_aaa_tacacs_cfg_dscp_ = "dscp"
    Cisco_IOS_XR_aaa_tacacs_cfg_af23 = 22
    Cisco_IOS_XR_aaa_tacacs_cfg_af23_ = "af23"
    Cisco_IOS_XR_aaa_tacacs_cfg_hosts = 756968979
    Cisco_IOS_XR_aaa_tacacs_cfg_hosts_ = "hosts"
    Cisco_IOS_XR_aaa_tacacs_cfg_servers = 1403078918
    Cisco_IOS_XR_aaa_tacacs_cfg_servers_ = "servers"
    Cisco_IOS_XR_aaa_tacacs_cfg_af41 = 34
    Cisco_IOS_XR_aaa_tacacs_cfg_af41_ = "af41"
    Cisco_IOS_XR_aaa_tacacs_cfg_cs4 = 32
    Cisco_IOS_XR_aaa_tacacs_cfg_cs4_ = "cs4"
    Cisco_IOS_XR_aaa_tacacs_cfg_af21 = 18
    Cisco_IOS_XR_aaa_tacacs_cfg_af21_ = "af21"
    Cisco_IOS_XR_aaa_tacacs_cfg_vrfs = 777611836
    Cisco_IOS_XR_aaa_tacacs_cfg_vrfs_ = "vrfs"
    Cisco_IOS_XR_aaa_tacacs_cfg_key = 1348858669
    Cisco_IOS_XR_aaa_tacacs_cfg_key_ = "key"
    Cisco_IOS_XR_aaa_tacacs_cfg_server = 163548884
    Cisco_IOS_XR_aaa_tacacs_cfg_server_ = "server"
    Cisco_IOS_XR_aaa_tacacs_cfg_source_interface = 1180772123
    Cisco_IOS_XR_aaa_tacacs_cfg_source_interface_ = "source-interface"
    Cisco_IOS_XR_aaa_tacacs_cfg_cs5 = 40
    Cisco_IOS_XR_aaa_tacacs_cfg_cs5_ = "cs5"
