#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-watchd-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-watchd-cfg.yang


class ns(object):
    hash = 41405930

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-watchd-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-watchd-cfg"

    prefix = "Cisco-IOS-XR-watchd-cfg"

    Cisco_IOS_XR_watchd_cfg_threshold_memory = 1323613705
    Cisco_IOS_XR_watchd_cfg_threshold_memory_ = "threshold-memory"
    Cisco_IOS_XR_watchd_cfg_restart_memoryhog_disable = 1084270518
    Cisco_IOS_XR_watchd_cfg_restart_memoryhog_disable_ = "restart-memoryhog-disable"
    Cisco_IOS_XR_watchd_cfg_minor = 589662983
    Cisco_IOS_XR_watchd_cfg_minor_ = "minor"
    Cisco_IOS_XR_watchd_cfg_watchdog_node_threshold = 85784173
    Cisco_IOS_XR_watchd_cfg_watchdog_node_threshold_ = "watchdog-node-threshold"
    Cisco_IOS_XR_watchd_cfg_watchd = 803333141
    Cisco_IOS_XR_watchd_cfg_watchd_ = "watchd"
    Cisco_IOS_XR_watchd_cfg_overload_throttle_timeout = 1398951154
    Cisco_IOS_XR_watchd_cfg_overload_throttle_timeout_ = "overload-throttle-timeout"
    Cisco_IOS_XR_watchd_cfg_memory_threshold = 2065709127
    Cisco_IOS_XR_watchd_cfg_memory_threshold_ = "memory-threshold"
    Cisco_IOS_XR_watchd_cfg_overload_notification = 1388405155
    Cisco_IOS_XR_watchd_cfg_overload_notification_ = "overload-notification"
    Cisco_IOS_XR_watchd_cfg_watchdog = 1352410101
    Cisco_IOS_XR_watchd_cfg_watchdog_ = "watchdog"
    Cisco_IOS_XR_watchd_cfg_timeout = 614210192
    Cisco_IOS_XR_watchd_cfg_timeout_ = "timeout"
    Cisco_IOS_XR_watchd_cfg_disk_limit = 1073826599
    Cisco_IOS_XR_watchd_cfg_disk_limit_ = "disk-limit"
    Cisco_IOS_XR_watchd_cfg_disk_threshold = 788954322
    Cisco_IOS_XR_watchd_cfg_disk_threshold_ = "disk-threshold"
    Cisco_IOS_XR_watchd_cfg_restart_deadlock_disable = 2034209728
    Cisco_IOS_XR_watchd_cfg_restart_deadlock_disable_ = "restart-deadlock-disable"
    Cisco_IOS_XR_watchd_cfg_critical = 1856469166
    Cisco_IOS_XR_watchd_cfg_critical_ = "critical"
    Cisco_IOS_XR_watchd_cfg_severe = 2064617282
    Cisco_IOS_XR_watchd_cfg_severe_ = "severe"
