#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-crypto-sam-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-crypto-sam-cfg.yang


class ns(object):
    hash = 2022989225

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-crypto-sam-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-crypto-sam-cfg"

    prefix = "Cisco-IOS-XR-crypto-sam-cfg"

    Cisco_IOS_XR_crypto_sam_cfg_action = 571883887
    Cisco_IOS_XR_crypto_sam_cfg_action_ = "action"
    Cisco_IOS_XR_crypto_sam_cfg_sam = 160632091
    Cisco_IOS_XR_crypto_sam_cfg_sam_ = "sam"
    Cisco_IOS_XR_crypto_sam_cfg_terminate = 2
    Cisco_IOS_XR_crypto_sam_cfg_terminate_ = "terminate"
    Cisco_IOS_XR_crypto_sam_cfg_prompt_interval = 991789190
    Cisco_IOS_XR_crypto_sam_cfg_prompt_interval_ = "prompt-interval"
    Cisco_IOS_XR_crypto_sam_cfg_prompt_time = 918830485
    Cisco_IOS_XR_crypto_sam_cfg_prompt_time_ = "prompt-time"
    Cisco_IOS_XR_crypto_sam_cfg_proceed = 1
    Cisco_IOS_XR_crypto_sam_cfg_proceed_ = "proceed"
