#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-snmp-bridgemib-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-snmp-bridgemib-cfg.yang


class ns(object):
    hash = 1060389760

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-snmp-bridgemib-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-snmp-bridgemib-cfg"

    prefix = "Cisco-IOS-XR-snmp-bridgemib-cfg"

    Cisco_IOS_XR_snmp_bridgemib_cfg_enable = 448570367
    Cisco_IOS_XR_snmp_bridgemib_cfg_enable_ = "enable"
    Cisco_IOS_XR_snmp_bridgemib_cfg_bridge = 1176739432
    Cisco_IOS_XR_snmp_bridgemib_cfg_bridge_ = "bridge"
