#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-tty-vty-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-tty-vty-cfg.yang


class ns(object):
    hash = 210739209

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-tty-vty-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-tty-vty-cfg"

    prefix = "Cisco-IOS-XR-tty-vty-cfg"

    Cisco_IOS_XR_tty_vty_cfg_none = 432063804
    Cisco_IOS_XR_tty_vty_cfg_none_ = "none"
    Cisco_IOS_XR_tty_vty_cfg_first_vty = 732469440
    Cisco_IOS_XR_tty_vty_cfg_first_vty_ = "first-vty"
    Cisco_IOS_XR_tty_vty_cfg_pool_name = 1327909428
    Cisco_IOS_XR_tty_vty_cfg_pool_name_ = "pool-name"
    Cisco_IOS_XR_tty_vty_cfg_vty = 916699563
    Cisco_IOS_XR_tty_vty_cfg_vty_ = "vty"
    Cisco_IOS_XR_tty_vty_cfg_last_vty = 1236632551
    Cisco_IOS_XR_tty_vty_cfg_last_vty_ = "last-vty"
    Cisco_IOS_XR_tty_vty_cfg_line_template = 765280434
    Cisco_IOS_XR_tty_vty_cfg_line_template_ = "line-template"
    Cisco_IOS_XR_tty_vty_cfg_vty_pools = 1020774987
    Cisco_IOS_XR_tty_vty_cfg_vty_pools_ = "vty-pools"
    Cisco_IOS_XR_tty_vty_cfg_vty_pool = 754754805
    Cisco_IOS_XR_tty_vty_cfg_vty_pool_ = "vty-pool"
