#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-linux-os-reboot-history-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-linux-os-reboot-history-oper.yang


class ns(object):
    hash = 1384202976

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-linux-os-reboot-history-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-linux-os-reboot-history-oper"

    prefix = "Cisco-IOS-XR-linux-os-reboot-history-oper"

    Cisco_IOS_XR_linux_os_reboot_history_oper_time = 190171445
    Cisco_IOS_XR_linux_os_reboot_history_oper_time_ = "time"
    Cisco_IOS_XR_linux_os_reboot_history_oper_no = 1765947383
    Cisco_IOS_XR_linux_os_reboot_history_oper_no_ = "no"
    Cisco_IOS_XR_linux_os_reboot_history_oper_cause_code = 1140648699
    Cisco_IOS_XR_linux_os_reboot_history_oper_cause_code_ = "cause-code"
    Cisco_IOS_XR_linux_os_reboot_history_oper_reboot_history = 1986901483
    Cisco_IOS_XR_linux_os_reboot_history_oper_reboot_history_ = "reboot-history"
    Cisco_IOS_XR_linux_os_reboot_history_oper_node_name = 122353445
    Cisco_IOS_XR_linux_os_reboot_history_oper_node_name_ = "node-name"
    Cisco_IOS_XR_linux_os_reboot_history_oper_node = 2084421367
    Cisco_IOS_XR_linux_os_reboot_history_oper_node_ = "node"
    Cisco_IOS_XR_linux_os_reboot_history_oper_reason = 565156039
    Cisco_IOS_XR_linux_os_reboot_history_oper_reason_ = "reason"
