#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-mpls-ldp-oper-datatypes.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-mpls-ldp-oper-datatypes.yang


class ns(object):
    hash = 1940493731

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mpls-ldp-oper-datatypes"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mpls-ldp-oper-datatypes"

    prefix = "Cisco-IOS-XR-mpls-ldp-oper-datatypes"

    Cisco_IOS_XR_mpls_ldp_oper_datatypes_all = 65535
    Cisco_IOS_XR_mpls_ldp_oper_datatypes_all_ = "all"
    Cisco_IOS_XR_mpls_ldp_oper_datatypes_ipv4 = 1
    Cisco_IOS_XR_mpls_ldp_oper_datatypes_ipv4_ = "ipv4"
    Cisco_IOS_XR_mpls_ldp_oper_datatypes_ipv6 = 2
    Cisco_IOS_XR_mpls_ldp_oper_datatypes_ipv6_ = "ipv6"
