#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-isis-act.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-isis-act.yang


class ns(object):
    hash = 1298248580

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-isis-act"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-isis-act"

    prefix = "Cisco-IOS-XR-isis-act"

    Cisco_IOS_XR_isis_act_clear_isis = 1214661457
    Cisco_IOS_XR_isis_act_clear_isis_ = "clear-isis"
    Cisco_IOS_XR_isis_act_IPv4_MULTICAST = 3
    Cisco_IOS_XR_isis_act_IPv4_MULTICAST_ = "IPv4-MULTICAST"
    Cisco_IOS_XR_isis_act_clear_isis_local_lsp = 1209820122
    Cisco_IOS_XR_isis_act_clear_isis_local_lsp_ = "clear-isis-local-lsp"
    Cisco_IOS_XR_isis_act_AFI_ALL_UNICAST = 2
    Cisco_IOS_XR_isis_act_AFI_ALL_UNICAST_ = "AFI-ALL-UNICAST"
    Cisco_IOS_XR_isis_act_IPv6_MULTICAST = 6
    Cisco_IOS_XR_isis_act_IPv6_MULTICAST_ = "IPv6-MULTICAST"
    Cisco_IOS_XR_isis_act_AFI_ALL_MULTICAST = 0
    Cisco_IOS_XR_isis_act_AFI_ALL_MULTICAST_ = "AFI-ALL-MULTICAST"
    Cisco_IOS_XR_isis_act_distribution = 2032111206
    Cisco_IOS_XR_isis_act_distribution_ = "distribution"
    Cisco_IOS_XR_isis_act_route = 2058743578
    Cisco_IOS_XR_isis_act_route_ = "route"
    Cisco_IOS_XR_isis_act_rpc_clear_isis_local_lsp = 1386341531
    Cisco_IOS_XR_isis_act_rpc_clear_isis_local_lsp_ = "rpc-clear-isis-local-lsp"
    Cisco_IOS_XR_isis_act_instance_identifier = 1982553370
    Cisco_IOS_XR_isis_act_instance_identifier_ = "instance-identifier"
    Cisco_IOS_XR_isis_act_rpc_clear_isis_route = 310712269
    Cisco_IOS_XR_isis_act_rpc_clear_isis_route_ = "rpc-clear-isis-route"
    Cisco_IOS_XR_isis_act_topology = 333175635
    Cisco_IOS_XR_isis_act_topology_ = "topology"
    Cisco_IOS_XR_isis_act_IPv4_SAFI_ALL = 4
    Cisco_IOS_XR_isis_act_IPv4_SAFI_ALL_ = "IPv4-SAFI-ALL"
    Cisco_IOS_XR_isis_act_rpc_clear_isis_stat = 952334903
    Cisco_IOS_XR_isis_act_rpc_clear_isis_stat_ = "rpc-clear-isis-stat"
    Cisco_IOS_XR_isis_act_interface_name = 1322899300
    Cisco_IOS_XR_isis_act_interface_name_ = "interface-name"
    Cisco_IOS_XR_isis_act_rpc_clear_isis = 27431575
    Cisco_IOS_XR_isis_act_rpc_clear_isis_ = "rpc-clear-isis"
    Cisco_IOS_XR_isis_act_statistics = 1049034618
    Cisco_IOS_XR_isis_act_statistics_ = "statistics"
    Cisco_IOS_XR_isis_act_route_topology = 503620544
    Cisco_IOS_XR_isis_act_route_topology_ = "route-topology"
    Cisco_IOS_XR_isis_act_instance = 136214150
    Cisco_IOS_XR_isis_act_instance_ = "instance"
    Cisco_IOS_XR_isis_act_IPv6_UNICAST = 8
    Cisco_IOS_XR_isis_act_IPv6_UNICAST_ = "IPv6-UNICAST"
    Cisco_IOS_XR_isis_act_local_lsp = 1477744416
    Cisco_IOS_XR_isis_act_local_lsp_ = "local-lsp"
    Cisco_IOS_XR_isis_act_clear_isis_route = 783215828
    Cisco_IOS_XR_isis_act_clear_isis_route_ = "clear-isis-route"
    Cisco_IOS_XR_isis_act_rpc_clear_isis_process = 484855633
    Cisco_IOS_XR_isis_act_rpc_clear_isis_process_ = "rpc-clear-isis-process"
    Cisco_IOS_XR_isis_act_IPv6_SAFI_ALL = 7
    Cisco_IOS_XR_isis_act_IPv6_SAFI_ALL_ = "IPv6-SAFI-ALL"
    Cisco_IOS_XR_isis_act_rt_type = 1835744430
    Cisco_IOS_XR_isis_act_rt_type_ = "rt-type"
    Cisco_IOS_XR_isis_act_clear_isis_dist = 1268304731
    Cisco_IOS_XR_isis_act_clear_isis_dist_ = "clear-isis-dist"
    Cisco_IOS_XR_isis_act_rpc_clear_isis_dist = 2133376198
    Cisco_IOS_XR_isis_act_rpc_clear_isis_dist_ = "rpc-clear-isis-dist"
    Cisco_IOS_XR_isis_act_clear_isis_stat = 122947721
    Cisco_IOS_XR_isis_act_clear_isis_stat_ = "clear-isis-stat"
    Cisco_IOS_XR_isis_act_clear_isis_process = 176226809
    Cisco_IOS_XR_isis_act_clear_isis_process_ = "clear-isis-process"
    Cisco_IOS_XR_isis_act_process = 131926618
    Cisco_IOS_XR_isis_act_process_ = "process"
    Cisco_IOS_XR_isis_act_AFI_ALL_SAFI_ALL = 1
    Cisco_IOS_XR_isis_act_AFI_ALL_SAFI_ALL_ = "AFI-ALL-SAFI-ALL"
    Cisco_IOS_XR_isis_act_IPv4_UNICAST = 5
    Cisco_IOS_XR_isis_act_IPv4_UNICAST_ = "IPv4-UNICAST"
