#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-aaa-diameter-base-mib-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-aaa-diameter-base-mib-cfg.yang


class ns(object):
    hash = 826501433

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-diameter-base-mib-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-diameter-base-mib-cfg"

    prefix = "Cisco-IOS-XR-aaa-diameter-base-mib-cfg"

    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_peerdown = 735111996
    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_peerdown_ = "peerdown"
    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_peerup = 750540983
    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_peerup_ = "peerup"
    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_protocolerror = 402421500
    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_protocolerror_ = "protocolerror"
    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_diametermib = 196381379
    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_diametermib_ = "diametermib"
    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_permanentfail = 2095385547
    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_permanentfail_ = "permanentfail"
    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_transientfail = 923985454
    Cisco_IOS_XR_aaa_diameter_base_mib_cfg_transientfail_ = "transientfail"
