#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-sysadmin-led-mgr-ui.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-sysadmin-led-mgr-ui.yang


class ns(object):
    hash = 932781141

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-led-mgr-ui"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-led-mgr-ui"

    prefix = "Cisco-IOS-XR-sysadmin-led-mgr-ui"

    Cisco_IOS_XR_sysadmin_led_mgr_ui_led_name = 270551640
    Cisco_IOS_XR_sysadmin_led_mgr_ui_led_name_ = "led_name"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_loc_header = 622099705
    Cisco_IOS_XR_sysadmin_led_mgr_ui_loc_header_ = "loc_header"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_led_mode = 2045735545
    Cisco_IOS_XR_sysadmin_led_mgr_ui_led_mode_ = "led_mode"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_location_name = 1667135771
    Cisco_IOS_XR_sysadmin_led_mgr_ui_location_name_ = "location_name"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_location = 1827424758
    Cisco_IOS_XR_sysadmin_led_mgr_ui_location_ = "location"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_led = 1735545142
    Cisco_IOS_XR_sysadmin_led_mgr_ui_led_ = "led"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_trace = 1896625767
    Cisco_IOS_XR_sysadmin_led_mgr_ui_trace_ = "trace"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_print_header = 53474163
    Cisco_IOS_XR_sysadmin_led_mgr_ui_print_header_ = "print_header"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_led_color = 289950302
    Cisco_IOS_XR_sysadmin_led_mgr_ui_led_color_ = "led_color"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_trace_blocks = 1645607271
    Cisco_IOS_XR_sysadmin_led_mgr_ui_trace_blocks_ = "trace-blocks"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_all_options = 436979003
    Cisco_IOS_XR_sysadmin_led_mgr_ui_all_options_ = "all-options"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_led_attributes = 1270905779
    Cisco_IOS_XR_sysadmin_led_mgr_ui_led_attributes_ = "led_attributes"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_option = 265226539
    Cisco_IOS_XR_sysadmin_led_mgr_ui_option_ = "option"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_buffer = 1428421018
    Cisco_IOS_XR_sysadmin_led_mgr_ui_buffer_ = "buffer"
    Cisco_IOS_XR_sysadmin_led_mgr_ui_data = 535242711
    Cisco_IOS_XR_sysadmin_led_mgr_ui_data_ = "data"
