#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-lpts-lib-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-lpts-lib-cfg.yang


class ns(object):
    hash = 532425002

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-lpts-lib-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-lpts-lib-cfg"

    prefix = "Cisco-IOS-XR-lpts-lib-cfg"

    Cisco_IOS_XR_lpts_lib_cfg_lpts = 565852751
    Cisco_IOS_XR_lpts_lib_cfg_lpts_ = "lpts"
