#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-pbr-bng-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-pbr-bng-cfg.yang


class ns(object):
    hash = 2054755380

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-pbr-bng-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-pbr-bng-cfg"

    prefix = "Cisco-IOS-XR-pbr-bng-cfg"

    Cisco_IOS_XR_pbr_bng_cfg_http_enrichment = 1047290942
    Cisco_IOS_XR_pbr_bng_cfg_http_enrichment_ = "http-enrichment"
    Cisco_IOS_XR_pbr_bng_cfg_arg1 = 79740565
    Cisco_IOS_XR_pbr_bng_cfg_arg1_ = "arg1"
    Cisco_IOS_XR_pbr_bng_cfg_host_name = 4
    Cisco_IOS_XR_pbr_bng_cfg_host_name_ = "host-name"
    Cisco_IOS_XR_pbr_bng_cfg_arg3 = 498974064
    Cisco_IOS_XR_pbr_bng_cfg_arg3_ = "arg3"
    Cisco_IOS_XR_pbr_bng_cfg_subscriber_ip = 2
    Cisco_IOS_XR_pbr_bng_cfg_subscriber_ip_ = "subscriber-ip"
    Cisco_IOS_XR_pbr_bng_cfg_bng_pbr = 284320092
    Cisco_IOS_XR_pbr_bng_cfg_bng_pbr_ = "bng-pbr"
    Cisco_IOS_XR_pbr_bng_cfg_parameters = 716273249
    Cisco_IOS_XR_pbr_bng_cfg_parameters_ = "parameters"
    Cisco_IOS_XR_pbr_bng_cfg_arg2 = 1721732759
    Cisco_IOS_XR_pbr_bng_cfg_arg2_ = "arg2"
    Cisco_IOS_XR_pbr_bng_cfg_arg4 = 252968179
    Cisco_IOS_XR_pbr_bng_cfg_arg4_ = "arg4"
    Cisco_IOS_XR_pbr_bng_cfg_subscriber_mac = 1
    Cisco_IOS_XR_pbr_bng_cfg_subscriber_mac_ = "subscriber-mac"
    Cisco_IOS_XR_pbr_bng_cfg_bng_identifier_interface = 8
    Cisco_IOS_XR_pbr_bng_cfg_bng_identifier_interface_ = "bng-identifier-interface"
    Cisco_IOS_XR_pbr_bng_cfg_bng_interface = 1140141348
    Cisco_IOS_XR_pbr_bng_cfg_bng_interface_ = "bng-interface"
