#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-ipv4-msdp-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-ipv4-msdp-cfg.yang


class ns(object):
    hash = 1992949279

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-msdp-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-msdp-cfg"

    prefix = "Cisco-IOS-XR-ipv4-msdp-cfg"

    Cisco_IOS_XR_ipv4_msdp_cfg_connect_source = 1186441322
    Cisco_IOS_XR_ipv4_msdp_cfg_connect_source_ = "connect-source"
    Cisco_IOS_XR_ipv4_msdp_cfg_sa_filters = 1826079598
    Cisco_IOS_XR_ipv4_msdp_cfg_sa_filters_ = "sa-filters"
    Cisco_IOS_XR_ipv4_msdp_cfg_max_sa = 2030125102
    Cisco_IOS_XR_ipv4_msdp_cfg_max_sa_ = "max-sa"
    Cisco_IOS_XR_ipv4_msdp_cfg_global_max_sa = 986572725
    Cisco_IOS_XR_ipv4_msdp_cfg_global_max_sa_ = "global-max-sa"
    Cisco_IOS_XR_ipv4_msdp_cfg_default_context = 1713376183
    Cisco_IOS_XR_ipv4_msdp_cfg_default_context_ = "default-context"
    Cisco_IOS_XR_ipv4_msdp_cfg_keep_alive = 649483949
    Cisco_IOS_XR_ipv4_msdp_cfg_keep_alive_ = "keep-alive"
    Cisco_IOS_XR_ipv4_msdp_cfg_peer_timeout_period = 546514025
    Cisco_IOS_XR_ipv4_msdp_cfg_peer_timeout_period_ = "peer-timeout-period"
    Cisco_IOS_XR_ipv4_msdp_cfg_nsr_delay = 667143722
    Cisco_IOS_XR_ipv4_msdp_cfg_nsr_delay_ = "nsr-delay"
    Cisco_IOS_XR_ipv4_msdp_cfg_sa_holdtime = 2074676998
    Cisco_IOS_XR_ipv4_msdp_cfg_sa_holdtime_ = "sa-holdtime"
    Cisco_IOS_XR_ipv4_msdp_cfg_peers = 958391453
    Cisco_IOS_XR_ipv4_msdp_cfg_peers_ = "peers"
    Cisco_IOS_XR_ipv4_msdp_cfg_msdp = 56807041
    Cisco_IOS_XR_ipv4_msdp_cfg_msdp_ = "msdp"
    Cisco_IOS_XR_ipv4_msdp_cfg_sa_filter = 513282117
    Cisco_IOS_XR_ipv4_msdp_cfg_sa_filter_ = "sa-filter"
    Cisco_IOS_XR_ipv4_msdp_cfg_vrf = 1281310328
    Cisco_IOS_XR_ipv4_msdp_cfg_vrf_ = "vrf"
    Cisco_IOS_XR_ipv4_msdp_cfg_enable = 448570367
    Cisco_IOS_XR_ipv4_msdp_cfg_enable_ = "enable"
    Cisco_IOS_XR_ipv4_msdp_cfg_shutdown = 460723287
    Cisco_IOS_XR_ipv4_msdp_cfg_shutdown_ = "shutdown"
    Cisco_IOS_XR_ipv4_msdp_cfg_as_yy = 800638899
    Cisco_IOS_XR_ipv4_msdp_cfg_as_yy_ = "as-yy"
    Cisco_IOS_XR_ipv4_msdp_cfg_outgoing = 2
    Cisco_IOS_XR_ipv4_msdp_cfg_outgoing_ = "outgoing"
    Cisco_IOS_XR_ipv4_msdp_cfg_peer = 1450174230
    Cisco_IOS_XR_ipv4_msdp_cfg_peer_ = "peer"
    Cisco_IOS_XR_ipv4_msdp_cfg_peer_address = 2130238605
    Cisco_IOS_XR_ipv4_msdp_cfg_peer_address_ = "peer-address"
    Cisco_IOS_XR_ipv4_msdp_cfg_description = 202559156
    Cisco_IOS_XR_ipv4_msdp_cfg_description_ = "description"
    Cisco_IOS_XR_ipv4_msdp_cfg_vrf_name = 2140916904
    Cisco_IOS_XR_ipv4_msdp_cfg_vrf_name_ = "vrf-name"
    Cisco_IOS_XR_ipv4_msdp_cfg_default_peer = 38723936
    Cisco_IOS_XR_ipv4_msdp_cfg_default_peer_ = "default-peer"
    Cisco_IOS_XR_ipv4_msdp_cfg_incoming = 1
    Cisco_IOS_XR_ipv4_msdp_cfg_incoming_ = "incoming"
    Cisco_IOS_XR_ipv4_msdp_cfg_max_peer_sa = 1851104943
    Cisco_IOS_XR_ipv4_msdp_cfg_max_peer_sa_ = "max-peer-sa"
    Cisco_IOS_XR_ipv4_msdp_cfg_keep_alive_period = 2131067317
    Cisco_IOS_XR_ipv4_msdp_cfg_keep_alive_period_ = "keep-alive-period"
    Cisco_IOS_XR_ipv4_msdp_cfg_filter_type = 820859681
    Cisco_IOS_XR_ipv4_msdp_cfg_filter_type_ = "filter-type"
    Cisco_IOS_XR_ipv4_msdp_cfg_mesh_group = 33444955
    Cisco_IOS_XR_ipv4_msdp_cfg_mesh_group_ = "mesh-group"
    Cisco_IOS_XR_ipv4_msdp_cfg_remote_as = 81986873
    Cisco_IOS_XR_ipv4_msdp_cfg_remote_as_ = "remote-as"
    Cisco_IOS_XR_ipv4_msdp_cfg_ttl_threshold = 1121497846
    Cisco_IOS_XR_ipv4_msdp_cfg_ttl_threshold_ = "ttl-threshold"
    Cisco_IOS_XR_ipv4_msdp_cfg_access_list_name = 337693690
    Cisco_IOS_XR_ipv4_msdp_cfg_access_list_name_ = "access-list-name"
    Cisco_IOS_XR_ipv4_msdp_cfg_peer_password = 308343504
    Cisco_IOS_XR_ipv4_msdp_cfg_peer_password_ = "peer-password"
    Cisco_IOS_XR_ipv4_msdp_cfg_vrfs = 777611836
    Cisco_IOS_XR_ipv4_msdp_cfg_vrfs_ = "vrfs"
    Cisco_IOS_XR_ipv4_msdp_cfg_as_xx = 340094348
    Cisco_IOS_XR_ipv4_msdp_cfg_as_xx_ = "as-xx"
    Cisco_IOS_XR_ipv4_msdp_cfg_cache_state = 84105238
    Cisco_IOS_XR_ipv4_msdp_cfg_cache_state_ = "cache-state"
    Cisco_IOS_XR_ipv4_msdp_cfg_nsr_down = 857993819
    Cisco_IOS_XR_ipv4_msdp_cfg_nsr_down_ = "nsr-down"
    Cisco_IOS_XR_ipv4_msdp_cfg_originator_id = 919533201
    Cisco_IOS_XR_ipv4_msdp_cfg_originator_id_ = "originator-id"
