#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-infra-rmf-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-infra-rmf-oper.yang


class ns(object):
    hash = 1106573854

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-rmf-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-infra-rmf-oper"

    prefix = "Cisco-IOS-XR-infra-rmf-oper"

    Cisco_IOS_XR_infra_rmf_oper_err_log = 1266104576
    Cisco_IOS_XR_infra_rmf_oper_err_log_ = "err-log"
    Cisco_IOS_XR_infra_rmf_oper_groupinfo = 372579724
    Cisco_IOS_XR_infra_rmf_oper_groupinfo_ = "groupinfo"
    Cisco_IOS_XR_infra_rmf_oper_red_pair = 1923417332
    Cisco_IOS_XR_infra_rmf_oper_red_pair_ = "red-pair"
    Cisco_IOS_XR_infra_rmf_oper_nsr_state = 692081885
    Cisco_IOS_XR_infra_rmf_oper_nsr_state_ = "nsr-state"
    Cisco_IOS_XR_infra_rmf_oper_ha_state = 1633459074
    Cisco_IOS_XR_infra_rmf_oper_ha_state_ = "ha-state"
    Cisco_IOS_XR_infra_rmf_oper_standby = 1180054629
    Cisco_IOS_XR_infra_rmf_oper_standby_ = "standby"
    Cisco_IOS_XR_infra_rmf_oper_node_id = 98319925
    Cisco_IOS_XR_infra_rmf_oper_node_id_ = "node-id"
    Cisco_IOS_XR_infra_rmf_oper_standby_reboot_reason = 2139641814
    Cisco_IOS_XR_infra_rmf_oper_standby_reboot_reason_ = "standby-reboot-reason"
    Cisco_IOS_XR_infra_rmf_oper_redundancy = 2100062149
    Cisco_IOS_XR_infra_rmf_oper_redundancy_ = "redundancy"
    Cisco_IOS_XR_infra_rmf_oper_nodes = 650955465
    Cisco_IOS_XR_infra_rmf_oper_nodes_ = "nodes"
    Cisco_IOS_XR_infra_rmf_oper_log = 1285913844
    Cisco_IOS_XR_infra_rmf_oper_log_ = "log"
    Cisco_IOS_XR_infra_rmf_oper_summary = 738895761
    Cisco_IOS_XR_infra_rmf_oper_summary_ = "summary"
    Cisco_IOS_XR_infra_rmf_oper_active_reboot_reason = 1002629448
    Cisco_IOS_XR_infra_rmf_oper_active_reboot_reason_ = "active-reboot-reason"
    Cisco_IOS_XR_infra_rmf_oper_node = 2084421367
    Cisco_IOS_XR_infra_rmf_oper_node_ = "node"
    Cisco_IOS_XR_infra_rmf_oper_active = 124277386
    Cisco_IOS_XR_infra_rmf_oper_active_ = "active"
