#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-aaa-tacacs-oper.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-aaa-tacacs-oper.yang


class ns(object):
    hash = 77954992

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-tacacs-oper"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-aaa-tacacs-oper"

    prefix = "Cisco-IOS-XR-aaa-tacacs-oper"

    Cisco_IOS_XR_aaa_tacacs_oper_requests = 1968374847
    Cisco_IOS_XR_aaa_tacacs_oper_requests_ = "requests"
    Cisco_IOS_XR_aaa_tacacs_oper_up = 1984149991
    Cisco_IOS_XR_aaa_tacacs_oper_up_ = "up"
    Cisco_IOS_XR_aaa_tacacs_oper_port = 10387472
    Cisco_IOS_XR_aaa_tacacs_oper_port_ = "port"
    Cisco_IOS_XR_aaa_tacacs_oper_aborts = 1881297690
    Cisco_IOS_XR_aaa_tacacs_oper_aborts_ = "aborts"
    Cisco_IOS_XR_aaa_tacacs_oper_addr = 1376787785
    Cisco_IOS_XR_aaa_tacacs_oper_addr_ = "addr"
    Cisco_IOS_XR_aaa_tacacs_oper_tacacs = 1696327224
    Cisco_IOS_XR_aaa_tacacs_oper_tacacs_ = "tacacs"
    Cisco_IOS_XR_aaa_tacacs_oper_server_groups = 1274829888
    Cisco_IOS_XR_aaa_tacacs_oper_server_groups_ = "server-groups"
    Cisco_IOS_XR_aaa_tacacs_oper_time_remaining = 196459818
    Cisco_IOS_XR_aaa_tacacs_oper_time_remaining_ = "time-remaining"
    Cisco_IOS_XR_aaa_tacacs_oper_sock = 111088303
    Cisco_IOS_XR_aaa_tacacs_oper_sock_ = "sock"
    Cisco_IOS_XR_aaa_tacacs_oper_replies_expected = 866439261
    Cisco_IOS_XR_aaa_tacacs_oper_replies_expected_ = "replies-expected"
    Cisco_IOS_XR_aaa_tacacs_oper_paks_out = 164339905
    Cisco_IOS_XR_aaa_tacacs_oper_paks_out_ = "paks-out"
    Cisco_IOS_XR_aaa_tacacs_oper_tacacs_requestbag = 555066089
    Cisco_IOS_XR_aaa_tacacs_oper_tacacs_requestbag_ = "tacacs-requestbag"
    Cisco_IOS_XR_aaa_tacacs_oper_pak_type = 333997042
    Cisco_IOS_XR_aaa_tacacs_oper_pak_type_ = "pak-type"
    Cisco_IOS_XR_aaa_tacacs_oper_errors = 1226221644
    Cisco_IOS_XR_aaa_tacacs_oper_errors_ = "errors"
    Cisco_IOS_XR_aaa_tacacs_oper_closes = 1476655180
    Cisco_IOS_XR_aaa_tacacs_oper_closes_ = "closes"
    Cisco_IOS_XR_aaa_tacacs_oper_request = 1788176625
    Cisco_IOS_XR_aaa_tacacs_oper_request_ = "request"
    Cisco_IOS_XR_aaa_tacacs_oper_server_group = 1509005832
    Cisco_IOS_XR_aaa_tacacs_oper_server_group_ = "server-group"
    Cisco_IOS_XR_aaa_tacacs_oper_bytes_out = 1220607578
    Cisco_IOS_XR_aaa_tacacs_oper_bytes_out_ = "bytes-out"
    Cisco_IOS_XR_aaa_tacacs_oper_vrf_name = 2140916904
    Cisco_IOS_XR_aaa_tacacs_oper_vrf_name_ = "vrf-name"
    Cisco_IOS_XR_aaa_tacacs_oper_out_pak_size = 2101818522
    Cisco_IOS_XR_aaa_tacacs_oper_out_pak_size_ = "out-pak-size"
    Cisco_IOS_XR_aaa_tacacs_oper_timeout = 614210192
    Cisco_IOS_XR_aaa_tacacs_oper_timeout_ = "timeout"
    Cisco_IOS_XR_aaa_tacacs_oper_conn_up = 1518745001
    Cisco_IOS_XR_aaa_tacacs_oper_conn_up_ = "conn-up"
    Cisco_IOS_XR_aaa_tacacs_oper_session_id = 372565948
    Cisco_IOS_XR_aaa_tacacs_oper_session_id_ = "session-id"
    Cisco_IOS_XR_aaa_tacacs_oper_single_connect = 1740593146
    Cisco_IOS_XR_aaa_tacacs_oper_single_connect_ = "single-connect"
    Cisco_IOS_XR_aaa_tacacs_oper_in_pak_size = 1531443818
    Cisco_IOS_XR_aaa_tacacs_oper_in_pak_size_ = "in-pak-size"
    Cisco_IOS_XR_aaa_tacacs_oper_bytes_in = 1888630442
    Cisco_IOS_XR_aaa_tacacs_oper_bytes_in_ = "bytes-in"
    Cisco_IOS_XR_aaa_tacacs_oper_paks_in = 1373013541
    Cisco_IOS_XR_aaa_tacacs_oper_paks_in_ = "paks-in"
    Cisco_IOS_XR_aaa_tacacs_oper_family = 825379649
    Cisco_IOS_XR_aaa_tacacs_oper_family_ = "family"
    Cisco_IOS_XR_aaa_tacacs_oper_servers = 1403078918
    Cisco_IOS_XR_aaa_tacacs_oper_servers_ = "servers"
    Cisco_IOS_XR_aaa_tacacs_oper_opens = 1757114548
    Cisco_IOS_XR_aaa_tacacs_oper_opens_ = "opens"
    Cisco_IOS_XR_aaa_tacacs_oper_is_private = 1936113426
    Cisco_IOS_XR_aaa_tacacs_oper_is_private_ = "is-private"
    Cisco_IOS_XR_aaa_tacacs_oper_addr_buf = 117071408
    Cisco_IOS_XR_aaa_tacacs_oper_addr_buf_ = "addr-buf"
    Cisco_IOS_XR_aaa_tacacs_oper_group_name = 331590344
    Cisco_IOS_XR_aaa_tacacs_oper_group_name_ = "group-name"
    Cisco_IOS_XR_aaa_tacacs_oper_sg_map_num = 788589818
    Cisco_IOS_XR_aaa_tacacs_oper_sg_map_num_ = "sg-map-num"
    Cisco_IOS_XR_aaa_tacacs_oper_server = 163548884
    Cisco_IOS_XR_aaa_tacacs_oper_server_ = "server"
