#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-mpls-io-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-mpls-io-cfg.yang


class ns(object):
    hash = 904170456

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mpls-io-cfg"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-mpls-io-cfg"

    prefix = "Cisco-IOS-XR-mpls-io-cfg"

    Cisco_IOS_XR_mpls_io_cfg_multi_label_drop = 1595975921
    Cisco_IOS_XR_mpls_io_cfg_multi_label_drop_ = "multi-label-drop"
    Cisco_IOS_XR_mpls_io_cfg_mtu = 1751455506
    Cisco_IOS_XR_mpls_io_cfg_mtu_ = "mtu"
    Cisco_IOS_XR_mpls_io_cfg_label_security = 306468907
    Cisco_IOS_XR_mpls_io_cfg_label_security_ = "label-security"
    Cisco_IOS_XR_mpls_io_cfg_rpf = 510477663
    Cisco_IOS_XR_mpls_io_cfg_rpf_ = "rpf"
    Cisco_IOS_XR_mpls_io_cfg_mpls = 1138155655
    Cisco_IOS_XR_mpls_io_cfg_mpls_ = "mpls"
