#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-sysadmin-aaa-disaster-recovery.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-sysadmin-aaa-disaster-recovery.yang


class ns(object):
    hash = 1949431563

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-aaa-disaster-recovery"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://www.cisco.com/ns/yang/Cisco-IOS-XR-sysadmin-aaa-disaster-recovery"

    prefix = "Cisco-IOS-XR-sysadmin-aaa-disaster-recovery"

    Cisco_IOS_XR_sysadmin_aaa_disaster_recovery_username = 870658415
    Cisco_IOS_XR_sysadmin_aaa_disaster_recovery_username_ = "username"
    Cisco_IOS_XR_sysadmin_aaa_disaster_recovery_disaster_recovery = 2089420129
    Cisco_IOS_XR_sysadmin_aaa_disaster_recovery_disaster_recovery_ = "disaster-recovery"
    Cisco_IOS_XR_sysadmin_aaa_disaster_recovery_password = 880727685
    Cisco_IOS_XR_sysadmin_aaa_disaster_recovery_password_ = "password"
