#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-ipv4-autorp-datatypes.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-ipv4-autorp-datatypes.yang


class ns(object):
    hash = 639231759

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-autorp-datatypes"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-autorp-datatypes"

    prefix = "Cisco-IOS-XR-ipv4-autorp-datatypes"

    Cisco_IOS_XR_ipv4_autorp_datatypes_sparse = 0
    Cisco_IOS_XR_ipv4_autorp_datatypes_sparse_ = "sparse"
    Cisco_IOS_XR_ipv4_autorp_datatypes_bidirectional = 1
    Cisco_IOS_XR_ipv4_autorp_datatypes_bidirectional_ = "bidirectional"
