#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/cisco-xr-ietf-netconf-acm-deviations.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module cisco-xr-ietf-netconf-acm-deviations.yang


class ns(object):
    hash = 1507915123

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/cisco-xr-ietf-netconf-acm-deviations"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/cisco-xr-ietf-netconf-acm-deviations"

    prefix = "cisco-xr-ietf-netconf-acm-deviations"

