#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-cfgmgr-rollback-act.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-cfgmgr-rollback-act.yang


class ns(object):
    hash = 454061033

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-cfgmgr-rollback-act"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-cfgmgr-rollback-act"

    prefix = "Cisco-IOS-XR-cfgmgr-rollback-act"

    Cisco_IOS_XR_cfgmgr_rollback_act_roll_back_configuration = 1857334945
    Cisco_IOS_XR_cfgmgr_rollback_act_roll_back_configuration_ = "roll-back-configuration"
    Cisco_IOS_XR_cfgmgr_rollback_act_roll_back_configuration_last = 931872933
    Cisco_IOS_XR_cfgmgr_rollback_act_roll_back_configuration_last_ = "roll-back-configuration-last"
    Cisco_IOS_XR_cfgmgr_rollback_act_comment = 452863039
    Cisco_IOS_XR_cfgmgr_rollback_act_comment_ = "comment"
    Cisco_IOS_XR_cfgmgr_rollback_act_best_effort = 1556684121
    Cisco_IOS_XR_cfgmgr_rollback_act_best_effort_ = "best-effort"
    Cisco_IOS_XR_cfgmgr_rollback_act_roll_back_configuration_to = 1892435338
    Cisco_IOS_XR_cfgmgr_rollback_act_roll_back_configuration_to_ = "roll-back-configuration-to"
    Cisco_IOS_XR_cfgmgr_rollback_act_count = 180894398
    Cisco_IOS_XR_cfgmgr_rollback_act_count_ = "count"
    Cisco_IOS_XR_cfgmgr_rollback_act_rpc_roll_back_configuration_last = 648529142
    Cisco_IOS_XR_cfgmgr_rollback_act_rpc_roll_back_configuration_last_ = "rpc-roll-back-configuration-last"
    Cisco_IOS_XR_cfgmgr_rollback_act_rpc_roll_back_configuration = 2033886143
    Cisco_IOS_XR_cfgmgr_rollback_act_rpc_roll_back_configuration_ = "rpc-roll-back-configuration"
    Cisco_IOS_XR_cfgmgr_rollback_act_label = 1570796500
    Cisco_IOS_XR_cfgmgr_rollback_act_label_ = "label"
    Cisco_IOS_XR_cfgmgr_rollback_act_force = 1475309827
    Cisco_IOS_XR_cfgmgr_rollback_act_force_ = "force"
    Cisco_IOS_XR_cfgmgr_rollback_act_rpc_roll_back_configuration_to_exclude = 127897281
    Cisco_IOS_XR_cfgmgr_rollback_act_rpc_roll_back_configuration_to_exclude_ = "rpc-roll-back-configuration-to-exclude"
    Cisco_IOS_XR_cfgmgr_rollback_act_rpc_roll_back_configuration_to = 119117724
    Cisco_IOS_XR_cfgmgr_rollback_act_rpc_roll_back_configuration_to_ = "rpc-roll-back-configuration-to"
    Cisco_IOS_XR_cfgmgr_rollback_act_roll_back_configuration_to_exclude = 786585898
    Cisco_IOS_XR_cfgmgr_rollback_act_roll_back_configuration_to_exclude_ = "roll-back-configuration-to-exclude"
    Cisco_IOS_XR_cfgmgr_rollback_act_commit_id = 738560138
    Cisco_IOS_XR_cfgmgr_rollback_act_commit_id_ = "commit-id"
