#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/fit.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module fit.yang


class ns(object):
    hash = 1348942991

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/panini/calvados/fit"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://cisco.com/panini/calvados/fit"

    prefix = "fit"

