#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/IPV6-TC.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module IPV6-TC.yang


class ns(object):
    hash = 7547473

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://tail-f.com/ns/mibs/IPV6-TC/199812010000Z"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://tail-f.com/ns/mibs/IPV6-TC/199812010000Z"

    prefix = "IPV6-TC"

