#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/nc-notifications.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module nc-notifications.yang


class ns(object):
    hash = 446411982

    id = "_f5500-nc-1.0:f5500-nc-1.0#urn:ietf:params:xml:ns:netmod:notification"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#urn:ietf:params:xml:ns:netmod:notification"

    prefix = "nc-notifications"

    nc_notifications_stream = 1561687317
    nc_notifications_stream_ = "stream"
    nc_notifications_notificationComplete = 1889643646
    nc_notifications_notificationComplete_ = "notificationComplete"
    nc_notifications_name = 1998270519
    nc_notifications_name_ = "name"
    nc_notifications_replayComplete = 1742925218
    nc_notifications_replayComplete_ = "replayComplete"
    nc_notifications_replayLogCreationTime = 1643315608
    nc_notifications_replayLogCreationTime_ = "replayLogCreationTime"
    nc_notifications_replaySupport = 82524045
    nc_notifications_replaySupport_ = "replaySupport"
    nc_notifications_description = 202559156
    nc_notifications_description_ = "description"
    nc_notifications_streams = 1043459567
    nc_notifications_streams_ = "streams"
    nc_notifications_netconf = 1625535416
    nc_notifications_netconf_ = "netconf"
