#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/SNMP-MPD-MIB.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module SNMP-MPD-MIB.yang


class ns(object):
    hash = 380858603

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://tail-f.com/ns/mibs/SNMP-MPD-MIB/200210140000Z"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://tail-f.com/ns/mibs/SNMP-MPD-MIB/200210140000Z"

    prefix = "SNMP-MPD-MIB"

    SNMP_MPD_MIB_snmpMPDStats = 1511777835
    SNMP_MPD_MIB_snmpMPDStats_ = "snmpMPDStats"
    SNMP_MPD_MIB_snmpUnknownPDUHandlers = 1344232479
    SNMP_MPD_MIB_snmpUnknownPDUHandlers_ = "snmpUnknownPDUHandlers"
    SNMP_MPD_MIB_SNMP_MPD_MIB = 2044030364
    SNMP_MPD_MIB_SNMP_MPD_MIB_ = "SNMP-MPD-MIB"
    SNMP_MPD_MIB_snmpUnknownSecurityModels = 1966416054
    SNMP_MPD_MIB_snmpUnknownSecurityModels_ = "snmpUnknownSecurityModels"
    SNMP_MPD_MIB_snmpInvalidMsgs = 1895392688
    SNMP_MPD_MIB_snmpInvalidMsgs_ = "snmpInvalidMsgs"
