#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/SNMP-NOTIFICATION-MIB.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module SNMP-NOTIFICATION-MIB.yang


class ns(object):
    hash = 12856093

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://tail-f.com/ns/mibs/SNMP-NOTIFICATION-MIB/200210140000Z"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://tail-f.com/ns/mibs/SNMP-NOTIFICATION-MIB/200210140000Z"

    prefix = "SNMP-NOTIFICATION-MIB"

    SNMP_NOTIFICATION_MIB_SNMP_NOTIFICATION_MIB = 668327020
    SNMP_NOTIFICATION_MIB_SNMP_NOTIFICATION_MIB_ = "SNMP-NOTIFICATION-MIB"
    SNMP_NOTIFICATION_MIB_excluded = 2
    SNMP_NOTIFICATION_MIB_excluded_ = "excluded"
    SNMP_NOTIFICATION_MIB_snmpNotifyEntry = 400969116
    SNMP_NOTIFICATION_MIB_snmpNotifyEntry_ = "snmpNotifyEntry"
    SNMP_NOTIFICATION_MIB_inform = 2
    SNMP_NOTIFICATION_MIB_inform_ = "inform"
    SNMP_NOTIFICATION_MIB_snmpNotifyName = 1006089358
    SNMP_NOTIFICATION_MIB_snmpNotifyName_ = "snmpNotifyName"
    SNMP_NOTIFICATION_MIB_snmpNotifyTag = 2072898851
    SNMP_NOTIFICATION_MIB_snmpNotifyTag_ = "snmpNotifyTag"
    SNMP_NOTIFICATION_MIB_snmpNotifyStorageType = 1615501675
    SNMP_NOTIFICATION_MIB_snmpNotifyStorageType_ = "snmpNotifyStorageType"
    SNMP_NOTIFICATION_MIB_trap = 1
    SNMP_NOTIFICATION_MIB_trap_ = "trap"
    SNMP_NOTIFICATION_MIB_snmpNotifyType = 396454141
    SNMP_NOTIFICATION_MIB_snmpNotifyType_ = "snmpNotifyType"
    SNMP_NOTIFICATION_MIB_snmpNotifyTable = 1424847766
    SNMP_NOTIFICATION_MIB_snmpNotifyTable_ = "snmpNotifyTable"
    SNMP_NOTIFICATION_MIB_included = 1
    SNMP_NOTIFICATION_MIB_included_ = "included"
