#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/SNMPv2-MIB.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module SNMPv2-MIB.yang


class ns(object):
    hash = 807318330

    id = "_f5500-nc-1.0:f5500-nc-1.0#http://tail-f.com/ns/mibs/SNMPv2-MIB/200210160000Z"

    uri = "_f5500-nc-1.0:f5500-nc-1.0#http://tail-f.com/ns/mibs/SNMPv2-MIB/200210160000Z"

    prefix = "SNMPv2-MIB"

    SNMPv2_MIB_enabled = 1
    SNMPv2_MIB_enabled_ = "enabled"
    SNMPv2_MIB_sysUpTime = 1150642786
    SNMPv2_MIB_sysUpTime_ = "sysUpTime"
    SNMPv2_MIB_sysContact = 1532032912
    SNMPv2_MIB_sysContact_ = "sysContact"
    SNMPv2_MIB_sysName = 654371288
    SNMPv2_MIB_sysName_ = "sysName"
    SNMPv2_MIB_snmpSet = 873376850
    SNMPv2_MIB_snmpSet_ = "snmpSet"
    SNMPv2_MIB_sysDescr = 654800859
    SNMPv2_MIB_sysDescr_ = "sysDescr"
    SNMPv2_MIB_sysORIndex = 871737704
    SNMPv2_MIB_sysORIndex_ = "sysORIndex"
    SNMPv2_MIB_sysORDescr = 416462406
    SNMPv2_MIB_sysORDescr_ = "sysORDescr"
    SNMPv2_MIB_snmpSetSerialNo = 1219563317
    SNMPv2_MIB_snmpSetSerialNo_ = "snmpSetSerialNo"
    SNMPv2_MIB_sysORTable = 179652456
    SNMPv2_MIB_sysORTable_ = "sysORTable"
    SNMPv2_MIB_snmpInBadVersions = 2030007641
    SNMPv2_MIB_snmpInBadVersions_ = "snmpInBadVersions"
    SNMPv2_MIB_sysORLastChange = 603436437
    SNMPv2_MIB_sysORLastChange_ = "sysORLastChange"
    SNMPv2_MIB_snmpEnableAuthenTraps = 1996226828
    SNMPv2_MIB_snmpEnableAuthenTraps_ = "snmpEnableAuthenTraps"
    SNMPv2_MIB_sysORID = 2013931968
    SNMPv2_MIB_sysORID_ = "sysORID"
    SNMPv2_MIB_snmpProxyDrops = 345911551
    SNMPv2_MIB_snmpProxyDrops_ = "snmpProxyDrops"
    SNMPv2_MIB_snmpSilentDrops = 1329530629
    SNMPv2_MIB_snmpSilentDrops_ = "snmpSilentDrops"
    SNMPv2_MIB_snmpInBadCommunityUses = 1242252727
    SNMPv2_MIB_snmpInBadCommunityUses_ = "snmpInBadCommunityUses"
    SNMPv2_MIB_disabled = 2
    SNMPv2_MIB_disabled_ = "disabled"
    SNMPv2_MIB_sysObjectID = 1237423500
    SNMPv2_MIB_sysObjectID_ = "sysObjectID"
    SNMPv2_MIB_sysORUpTime = 754715181
    SNMPv2_MIB_sysORUpTime_ = "sysORUpTime"
    SNMPv2_MIB_sysOREntry = 1469072598
    SNMPv2_MIB_sysOREntry_ = "sysOREntry"
    SNMPv2_MIB_SNMPv2_MIB = 709663033
    SNMPv2_MIB_SNMPv2_MIB_ = "SNMPv2-MIB"
    SNMPv2_MIB_system = 1534086422
    SNMPv2_MIB_system_ = "system"
    SNMPv2_MIB_sysLocation = 462896534
    SNMPv2_MIB_sysLocation_ = "sysLocation"
    SNMPv2_MIB_snmp = 1480446066
    SNMPv2_MIB_snmp_ = "snmp"
    SNMPv2_MIB_snmpInPkts = 1387388380
    SNMPv2_MIB_snmpInPkts_ = "snmpInPkts"
    SNMPv2_MIB_snmpInASNParseErrs = 608266164
    SNMPv2_MIB_snmpInASNParseErrs_ = "snmpInASNParseErrs"
    SNMPv2_MIB_sysServices = 746549272
    SNMPv2_MIB_sysServices_ = "sysServices"
    SNMPv2_MIB_snmpInBadCommunityNames = 848262216
    SNMPv2_MIB_snmpInBadCommunityNames_ = "snmpInBadCommunityNames"
