#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/_3gpp-common-top.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module _3gpp-common-top.yang


class ns(object):
    hash = 1562807781

    id = "_tgpp-nc-1.0:tgpp-nc-1.0#urn:3gpp:sa5:_3gpp-common-top"

    uri = "_tgpp-nc-1.0:tgpp-nc-1.0#urn:3gpp:sa5:_3gpp-common-top"

    prefix = "top3gpp"

