#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/_3gpp-common-subnetwork.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module _3gpp-common-subnetwork.yang


class ns(object):
    hash = 953787633

    id = "_tgpp-nc-1.0:tgpp-nc-1.0#urn:3gpp:sa5:_3gpp-common-subnetwork"

    uri = "_tgpp-nc-1.0:tgpp-nc-1.0#urn:3gpp:sa5:_3gpp-common-subnetwork"

    prefix = "subnet3gpp"

    subnet3gpp_defaultStreamTarget = 1560611990
    subnet3gpp_defaultStreamTarget_ = "defaultStreamTarget"
    subnet3gpp_userDefinedNetworkType = 32336612
    subnet3gpp_userDefinedNetworkType_ = "userDefinedNetworkType"
    subnet3gpp_fileBasedGP = 1293308363
    subnet3gpp_fileBasedGP_ = "fileBasedGP"
    subnet3gpp_monitoredObjectDNs = 1308800195
    subnet3gpp_monitoredObjectDNs_ = "monitoredObjectDNs"
    subnet3gpp_nFSrvGroupId = 738854815
    subnet3gpp_nFSrvGroupId_ = "nFSrvGroupId"
    subnet3gpp_attributes = 564855297
    subnet3gpp_attributes_ = "attributes"
    subnet3gpp_fileLocation = 2025279126
    subnet3gpp_fileLocation_ = "fileLocation"
    subnet3gpp_defaultFileBasedGP = 528022994
    subnet3gpp_defaultFileBasedGP_ = "defaultFileBasedGP"
    subnet3gpp_fileReportingPeriod = 471590844
    subnet3gpp_fileReportingPeriod_ = "fileReportingPeriod"
    subnet3gpp_threshold_low = 1086063453
    subnet3gpp_threshold_low_ = "threshold-low"
    subnet3gpp_INCREASING = 0
    subnet3gpp_INCREASING_ = "INCREASING"
    subnet3gpp_managedObjectDNsBasic = 1424156604
    subnet3gpp_managedObjectDNsBasic_ = "managedObjectDNsBasic"
    subnet3gpp_MeasurementReader = 1585554405
    subnet3gpp_MeasurementReader_ = "MeasurementReader"
    subnet3gpp_pMAdministrativeState = 430035878
    subnet3gpp_pMAdministrativeState_ = "pMAdministrativeState"
    subnet3gpp_priority = 1346277862
    subnet3gpp_priority_ = "priority"
    subnet3gpp_monitoringGP = 63522496
    subnet3gpp_monitoringGP_ = "monitoringGP"
    subnet3gpp_thresholdLevel = 127106057
    subnet3gpp_thresholdLevel_ = "thresholdLevel"
    subnet3gpp_parents = 1912968603
    subnet3gpp_parents_ = "parents"
    subnet3gpp_EXPOSURE = 2
    subnet3gpp_EXPOSURE_ = "EXPOSURE"
    subnet3gpp_SUBSCRIPTION = 0
    subnet3gpp_SUBSCRIPTION_ = "SUBSCRIPTION"
    subnet3gpp_ThresholdMonitor = 345540386
    subnet3gpp_ThresholdMonitor_ = "ThresholdMonitor"
    subnet3gpp_thresholdValue = 1557248447
    subnet3gpp_thresholdValue_ = "thresholdValue"
    subnet3gpp_supportedMonitoringGPs = 1066075749
    subnet3gpp_supportedMonitoringGPs_ = "supportedMonitoringGPs"
    subnet3gpp_authzInfo = 1664447306
    subnet3gpp_authzInfo_ = "authzInfo"
    subnet3gpp_location = 1827424758
    subnet3gpp_location_ = "location"
    subnet3gpp_pMOperationalState = 339692622
    subnet3gpp_pMOperationalState_ = "pMOperationalState"
    subnet3gpp_DECREASING = 1
    subnet3gpp_DECREASING_ = "DECREASING"
    subnet3gpp_SubNetwork = 1824684375
    subnet3gpp_SubNetwork_ = "SubNetwork"
    subnet3gpp_gPs = 1761160070
    subnet3gpp_gPs_ = "gPs"
    subnet3gpp_measurementsList = 349662536
    subnet3gpp_measurementsList_ = "measurementsList"
    subnet3gpp_streamBasedGP = 1061964495
    subnet3gpp_streamBasedGP_ = "streamBasedGP"
    subnet3gpp_managedObjectDNs = 623232980
    subnet3gpp_managedObjectDNs_ = "managedObjectDNs"
    subnet3gpp_id = 1279252765
    subnet3gpp_id_ = "id"
    subnet3gpp_monitoredIOCName = 2061921308
    subnet3gpp_monitoredIOCName_ = "monitoredIOCName"
    subnet3gpp_measurementType = 302671918
    subnet3gpp_measurementType_ = "measurementType"
    subnet3gpp_nfType = 822410783
    subnet3gpp_nfType_ = "nfType"
    subnet3gpp_smfServingAreas = 333484022
    subnet3gpp_smfServingAreas_ = "smfServingAreas"
    subnet3gpp_thresholdInfoList = 622544740
    subnet3gpp_thresholdInfoList_ = "thresholdInfoList"
    subnet3gpp_userLabel = 1367743805
    subnet3gpp_userLabel_ = "userLabel"
    subnet3gpp_direction = 1468062370
    subnet3gpp_direction_ = "direction"
    subnet3gpp_hostAddr = 1785472006
    subnet3gpp_hostAddr_ = "hostAddr"
    subnet3gpp_priorityLabel = 1509091865
    subnet3gpp_priorityLabel_ = "priorityLabel"
    subnet3gpp_monitoringNotifTarget = 754534081
    subnet3gpp_monitoringNotifTarget_ = "monitoringNotifTarget"
    subnet3gpp_nfInstanceID = 1499370648
    subnet3gpp_nfInstanceID_ = "nfInstanceID"
    subnet3gpp_threshold_high = 1225571650
    subnet3gpp_threshold_high_ = "threshold-high"
    subnet3gpp_setOfMcc = 1592970403
    subnet3gpp_setOfMcc_ = "setOfMcc"
    subnet3gpp_measurementTypes = 2071082739
    subnet3gpp_measurementTypes_ = "measurementTypes"
    subnet3gpp_defaultFileReportingPeriod = 2097084703
    subnet3gpp_defaultFileReportingPeriod_ = "defaultFileReportingPeriod"
    subnet3gpp_capacity = 191070892
    subnet3gpp_capacity_ = "capacity"
    subnet3gpp_containedChildren = 7811900
    subnet3gpp_containedChildren_ = "containedChildren"
    subnet3gpp_ThresholdMonitoringCapability = 280211657
    subnet3gpp_ThresholdMonitoringCapability_ = "ThresholdMonitoringCapability"
    subnet3gpp_thresholdPack = 1261305660
    subnet3gpp_thresholdPack_ = "thresholdPack"
    subnet3gpp_APPLICATION = 3
    subnet3gpp_APPLICATION_ = "APPLICATION"
    subnet3gpp_dnPrefix = 805591200
    subnet3gpp_dnPrefix_ = "dnPrefix"
    subnet3gpp_defaultStreamBasedGP = 1302980464
    subnet3gpp_defaultStreamBasedGP_ = "defaultStreamBasedGP"
    subnet3gpp_idx = 518466655
    subnet3gpp_idx_ = "idx"
    subnet3gpp_MeasurementControl = 1203308997
    subnet3gpp_MeasurementControl_ = "MeasurementControl"
    subnet3gpp_POLICY = 1
    subnet3gpp_POLICY_ = "POLICY"
    subnet3gpp_supportedDataSetIds = 1330589453
    subnet3gpp_supportedDataSetIds_ = "supportedDataSetIds"
    subnet3gpp_streamTarget = 1826497402
    subnet3gpp_streamTarget_ = "streamTarget"
    subnet3gpp_defaultFileLocation = 905138560
    subnet3gpp_defaultFileLocation_ = "defaultFileLocation"
