/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-tgpp-nc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.tgpp.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-tgpp-nc.yang */
public class tailfNedIdTgppNc extends ConfNamespace {
    public static final int hash = 533226779;
    public int hash() {
        return tailfNedIdTgppNc.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/tgpp-nc";
    public String id() {
        return tailfNedIdTgppNc.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/tgpp-nc";
    public String uri() {
        return tailfNedIdTgppNc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdTgppNc.uri);
    }

    public static final String prefix = "tgpp-nc";
    public String prefix() {
        return tailfNedIdTgppNc.prefix;
    }

    public tailfNedIdTgppNc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    ned_id = 1326426014;
    public static final String ned_id_ = "tgpp-nc:tgpp-nc";
    public static final int    _tgpp_nc = 1326426014;
    public static final String _tgpp_nc_ = "tgpp-nc";
}
