#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/_3gpp-5g-common-yang-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module _3gpp-5g-common-yang-types.yang


class ns(object):
    hash = 614062700

    id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-5g-common-yang-types"

    uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-5g-common-yang-types"

    prefix = "types5g3gpp"

    types5g3gpp_DIRECT_COMMUNICATION_WITH_NRF = 1
    types5g3gpp_DIRECT_COMMUNICATION_WITH_NRF_ = "DIRECT_COMMUNICATION_WITH_NRF"
    types5g3gpp_INDIRECT_COMMUNICATION_WITH_DEDICATED_DISCOVERY = 3
    types5g3gpp_INDIRECT_COMMUNICATION_WITH_DEDICATED_DISCOVERY_ = "INDIRECT_COMMUNICATION_WITH_DEDICATED_DISCOVERY"
    types5g3gpp_INDIRECT_COMMUNICATION_WO_DEDICATED_DISCOVERY = 2
    types5g3gpp_INDIRECT_COMMUNICATION_WO_DEDICATED_DISCOVERY_ = "INDIRECT_COMMUNICATION_WO_DEDICATED_DISCOVERY"
    types5g3gpp_DIRECT_COMMUNICATION_WO_NRF = 0
    types5g3gpp_DIRECT_COMMUNICATION_WO_NRF_ = "DIRECT_COMMUNICATION_WO_NRF"
