#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/_3gpp-nr-nrm-externalgnbdufunction.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module _3gpp-nr-nrm-externalgnbdufunction.yang


class ns(object):
    hash = 430354166

    id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-nr-nrm-externalgnbdufunction"

    uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-nr-nrm-externalgnbdufunction"

    prefix = "extgnbdu3gpp"

    extgnbdu3gpp_environmentType = 252397055
    extgnbdu3gpp_environmentType_ = "environmentType"
    extgnbdu3gpp_operationalState = 880872221
    extgnbdu3gpp_operationalState_ = "operationalState"
    extgnbdu3gpp_allowedNFTypes = 189804508
    extgnbdu3gpp_allowedNFTypes_ = "allowedNFTypes"
    extgnbdu3gpp_attributes = 564855297
    extgnbdu3gpp_attributes_ = "attributes"
    extgnbdu3gpp_port = 10387472
    extgnbdu3gpp_port_ = "port"
    extgnbdu3gpp_peeParametersList = 1298381397
    extgnbdu3gpp_peeParametersList_ = "peeParametersList"
    extgnbdu3gpp_equipmentType = 1795612006
    extgnbdu3gpp_equipmentType_ = "equipmentType"
    extgnbdu3gpp_pLMNId = 139438964
    extgnbdu3gpp_pLMNId_ = "pLMNId"
    extgnbdu3gpp_usageState = 1489640591
    extgnbdu3gpp_usageState_ = "usageState"
    extgnbdu3gpp_name = 1998270519
    extgnbdu3gpp_name_ = "name"
    extgnbdu3gpp_operations = 1455304325
    extgnbdu3gpp_operations_ = "operations"
    extgnbdu3gpp_ExternalGNBDUFunction = 130935269
    extgnbdu3gpp_ExternalGNBDUFunction_ = "ExternalGNBDUFunction"
    extgnbdu3gpp_vnfInstanceId = 1359245082
    extgnbdu3gpp_vnfInstanceId_ = "vnfInstanceId"
    extgnbdu3gpp_siteDescription = 1034504377
    extgnbdu3gpp_siteDescription_ = "siteDescription"
    extgnbdu3gpp_siteLongitude = 18287823
    extgnbdu3gpp_siteLongitude_ = "siteLongitude"
    extgnbdu3gpp_mcc = 1243031439
    extgnbdu3gpp_mcc_ = "mcc"
    extgnbdu3gpp_gPs = 1761160070
    extgnbdu3gpp_gPs_ = "gPs"
    extgnbdu3gpp_registrationState = 421695678
    extgnbdu3gpp_registrationState_ = "registrationState"
    extgnbdu3gpp_measurementsList = 349662536
    extgnbdu3gpp_measurementsList_ = "measurementsList"
    extgnbdu3gpp_ManagedNFService = 736688724
    extgnbdu3gpp_ManagedNFService_ = "ManagedNFService"
    extgnbdu3gpp_operationSemantics = 844181866
    extgnbdu3gpp_operationSemantics_ = "operationSemantics"
    extgnbdu3gpp_id = 1279252765
    extgnbdu3gpp_id_ = "id"
    extgnbdu3gpp_siteIdentification = 726111887
    extgnbdu3gpp_siteIdentification_ = "siteIdentification"
    extgnbdu3gpp_administrativeState = 499558712
    extgnbdu3gpp_administrativeState_ = "administrativeState"
    extgnbdu3gpp_host = 1711485895
    extgnbdu3gpp_host_ = "host"
    extgnbdu3gpp_DEREGISTERED = 1
    extgnbdu3gpp_DEREGISTERED_ = "DEREGISTERED"
    extgnbdu3gpp_nFServiceType = 617372187
    extgnbdu3gpp_nFServiceType_ = "nFServiceType"
    extgnbdu3gpp_gNBId = 1445863304
    extgnbdu3gpp_gNBId_ = "gNBId"
    extgnbdu3gpp_powerInterface = 663222618
    extgnbdu3gpp_powerInterface_ = "powerInterface"
    extgnbdu3gpp_userLabel = 1367743805
    extgnbdu3gpp_userLabel_ = "userLabel"
    extgnbdu3gpp_REGISTERED = 0
    extgnbdu3gpp_REGISTERED_ = "REGISTERED"
    extgnbdu3gpp_flavourId = 1273445849
    extgnbdu3gpp_flavourId_ = "flavourId"
    extgnbdu3gpp_sAP = 1421749432
    extgnbdu3gpp_sAP_ = "sAP"
    extgnbdu3gpp_priorityLabel = 1509091865
    extgnbdu3gpp_priorityLabel_ = "priorityLabel"
    extgnbdu3gpp_vnfParametersList = 849315116
    extgnbdu3gpp_vnfParametersList_ = "vnfParametersList"
    extgnbdu3gpp_SUBSCRIBE_NOTIFY = 1
    extgnbdu3gpp_SUBSCRIBE_NOTIFY_ = "SUBSCRIBE_NOTIFY"
    extgnbdu3gpp_gNBIdLength = 523740309
    extgnbdu3gpp_gNBIdLength_ = "gNBIdLength"
    extgnbdu3gpp_mnc = 351025106
    extgnbdu3gpp_mnc_ = "mnc"
    extgnbdu3gpp_measurementTypes = 2071082739
    extgnbdu3gpp_measurementTypes_ = "measurementTypes"
    extgnbdu3gpp_vnfdId = 1550391235
    extgnbdu3gpp_vnfdId_ = "vnfdId"
    extgnbdu3gpp_autoScalable = 141263935
    extgnbdu3gpp_autoScalable_ = "autoScalable"
    extgnbdu3gpp_idx = 518466655
    extgnbdu3gpp_idx_ = "idx"
    extgnbdu3gpp_REQUEST_RESPONSE = 0
    extgnbdu3gpp_REQUEST_RESPONSE_ = "REQUEST_RESPONSE"
    extgnbdu3gpp_siteLatitude = 259835897
    extgnbdu3gpp_siteLatitude_ = "siteLatitude"
