#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/_3gpp-5gc-nrm-externalnssffunction.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module _3gpp-5gc-nrm-externalnssffunction.yang


class ns(object):
    hash = 385870050

    id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-5gc-nrm-externalnssffunction"

    uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-5gc-nrm-externalnssffunction"

    prefix = "extnssf3gpp"

    extnssf3gpp_operationalState = 880872221
    extnssf3gpp_operationalState_ = "operationalState"
    extnssf3gpp_environmentType = 252397055
    extnssf3gpp_environmentType_ = "environmentType"
    extnssf3gpp_allowedNFTypes = 189804508
    extnssf3gpp_allowedNFTypes_ = "allowedNFTypes"
    extnssf3gpp_attributes = 564855297
    extnssf3gpp_attributes_ = "attributes"
    extnssf3gpp_port = 10387472
    extnssf3gpp_port_ = "port"
    extnssf3gpp_ExternalNSSFFunction = 1006660022
    extnssf3gpp_ExternalNSSFFunction_ = "ExternalNSSFFunction"
    extnssf3gpp_pLMNIdList = 514534765
    extnssf3gpp_pLMNIdList_ = "pLMNIdList"
    extnssf3gpp_peeParametersList = 1298381397
    extnssf3gpp_peeParametersList_ = "peeParametersList"
    extnssf3gpp_equipmentType = 1795612006
    extnssf3gpp_equipmentType_ = "equipmentType"
    extnssf3gpp_usageState = 1489640591
    extnssf3gpp_usageState_ = "usageState"
    extnssf3gpp_name = 1998270519
    extnssf3gpp_name_ = "name"
    extnssf3gpp_operations = 1455304325
    extnssf3gpp_operations_ = "operations"
    extnssf3gpp_vnfInstanceId = 1359245082
    extnssf3gpp_vnfInstanceId_ = "vnfInstanceId"
    extnssf3gpp_siteDescription = 1034504377
    extnssf3gpp_siteDescription_ = "siteDescription"
    extnssf3gpp_siteLongitude = 18287823
    extnssf3gpp_siteLongitude_ = "siteLongitude"
    extnssf3gpp_mcc = 1243031439
    extnssf3gpp_mcc_ = "mcc"
    extnssf3gpp_gPs = 1761160070
    extnssf3gpp_gPs_ = "gPs"
    extnssf3gpp_registrationState = 421695678
    extnssf3gpp_registrationState_ = "registrationState"
    extnssf3gpp_measurementsList = 349662536
    extnssf3gpp_measurementsList_ = "measurementsList"
    extnssf3gpp_ManagedNFService = 736688724
    extnssf3gpp_ManagedNFService_ = "ManagedNFService"
    extnssf3gpp_operationSemantics = 844181866
    extnssf3gpp_operationSemantics_ = "operationSemantics"
    extnssf3gpp_id = 1279252765
    extnssf3gpp_id_ = "id"
    extnssf3gpp_siteIdentification = 726111887
    extnssf3gpp_siteIdentification_ = "siteIdentification"
    extnssf3gpp_administrativeState = 499558712
    extnssf3gpp_administrativeState_ = "administrativeState"
    extnssf3gpp_host = 1711485895
    extnssf3gpp_host_ = "host"
    extnssf3gpp_DEREGISTERED = 1
    extnssf3gpp_DEREGISTERED_ = "DEREGISTERED"
    extnssf3gpp_nFServiceType = 617372187
    extnssf3gpp_nFServiceType_ = "nFServiceType"
    extnssf3gpp_powerInterface = 663222618
    extnssf3gpp_powerInterface_ = "powerInterface"
    extnssf3gpp_userLabel = 1367743805
    extnssf3gpp_userLabel_ = "userLabel"
    extnssf3gpp_REGISTERED = 0
    extnssf3gpp_REGISTERED_ = "REGISTERED"
    extnssf3gpp_flavourId = 1273445849
    extnssf3gpp_flavourId_ = "flavourId"
    extnssf3gpp_sAP = 1421749432
    extnssf3gpp_sAP_ = "sAP"
    extnssf3gpp_priorityLabel = 1509091865
    extnssf3gpp_priorityLabel_ = "priorityLabel"
    extnssf3gpp_vnfParametersList = 849315116
    extnssf3gpp_vnfParametersList_ = "vnfParametersList"
    extnssf3gpp_SUBSCRIBE_NOTIFY = 1
    extnssf3gpp_SUBSCRIBE_NOTIFY_ = "SUBSCRIBE_NOTIFY"
    extnssf3gpp_mnc = 351025106
    extnssf3gpp_mnc_ = "mnc"
    extnssf3gpp_measurementTypes = 2071082739
    extnssf3gpp_measurementTypes_ = "measurementTypes"
    extnssf3gpp_vnfdId = 1550391235
    extnssf3gpp_vnfdId_ = "vnfdId"
    extnssf3gpp_autoScalable = 141263935
    extnssf3gpp_autoScalable_ = "autoScalable"
    extnssf3gpp_idx = 518466655
    extnssf3gpp_idx_ = "idx"
    extnssf3gpp_REQUEST_RESPONSE = 0
    extnssf3gpp_REQUEST_RESPONSE_ = "REQUEST_RESPONSE"
    extnssf3gpp_siteLatitude = 259835897
    extnssf3gpp_siteLatitude_ = "siteLatitude"
