#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/_3gpp-5gc-nrm-dnfunction.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module _3gpp-5gc-nrm-dnfunction.yang


class ns(object):
    hash = 1467425507

    id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5_3gpp-5gc-nrm-dnfunction"

    uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5_3gpp-5gc-nrm-dnfunction"

    prefix = "dn3gpp"

    dn3gpp_operationalState = 880872221
    dn3gpp_operationalState_ = "operationalState"
    dn3gpp_environmentType = 252397055
    dn3gpp_environmentType_ = "environmentType"
    dn3gpp_allowedNFTypes = 189804508
    dn3gpp_allowedNFTypes_ = "allowedNFTypes"
    dn3gpp_attributes = 564855297
    dn3gpp_attributes_ = "attributes"
    dn3gpp_port = 10387472
    dn3gpp_port_ = "port"
    dn3gpp_peeParametersList = 1298381397
    dn3gpp_peeParametersList_ = "peeParametersList"
    dn3gpp_equipmentType = 1795612006
    dn3gpp_equipmentType_ = "equipmentType"
    dn3gpp_usageState = 1489640591
    dn3gpp_usageState_ = "usageState"
    dn3gpp_name = 1998270519
    dn3gpp_name_ = "name"
    dn3gpp_operations = 1455304325
    dn3gpp_operations_ = "operations"
    dn3gpp_vnfInstanceId = 1359245082
    dn3gpp_vnfInstanceId_ = "vnfInstanceId"
    dn3gpp_siteDescription = 1034504377
    dn3gpp_siteDescription_ = "siteDescription"
    dn3gpp_DNFunction = 1216464693
    dn3gpp_DNFunction_ = "DNFunction"
    dn3gpp_siteLongitude = 18287823
    dn3gpp_siteLongitude_ = "siteLongitude"
    dn3gpp_gPs = 1761160070
    dn3gpp_gPs_ = "gPs"
    dn3gpp_registrationState = 421695678
    dn3gpp_registrationState_ = "registrationState"
    dn3gpp_measurementsList = 349662536
    dn3gpp_measurementsList_ = "measurementsList"
    dn3gpp_ManagedNFService = 736688724
    dn3gpp_ManagedNFService_ = "ManagedNFService"
    dn3gpp_operationSemantics = 844181866
    dn3gpp_operationSemantics_ = "operationSemantics"
    dn3gpp_id = 1279252765
    dn3gpp_id_ = "id"
    dn3gpp_siteIdentification = 726111887
    dn3gpp_siteIdentification_ = "siteIdentification"
    dn3gpp_administrativeState = 499558712
    dn3gpp_administrativeState_ = "administrativeState"
    dn3gpp_host = 1711485895
    dn3gpp_host_ = "host"
    dn3gpp_DEREGISTERED = 1
    dn3gpp_DEREGISTERED_ = "DEREGISTERED"
    dn3gpp_nFServiceType = 617372187
    dn3gpp_nFServiceType_ = "nFServiceType"
    dn3gpp_powerInterface = 663222618
    dn3gpp_powerInterface_ = "powerInterface"
    dn3gpp_userLabel = 1367743805
    dn3gpp_userLabel_ = "userLabel"
    dn3gpp_REGISTERED = 0
    dn3gpp_REGISTERED_ = "REGISTERED"
    dn3gpp_flavourId = 1273445849
    dn3gpp_flavourId_ = "flavourId"
    dn3gpp_sAP = 1421749432
    dn3gpp_sAP_ = "sAP"
    dn3gpp_priorityLabel = 1509091865
    dn3gpp_priorityLabel_ = "priorityLabel"
    dn3gpp_vnfParametersList = 849315116
    dn3gpp_vnfParametersList_ = "vnfParametersList"
    dn3gpp_SUBSCRIBE_NOTIFY = 1
    dn3gpp_SUBSCRIBE_NOTIFY_ = "SUBSCRIBE_NOTIFY"
    dn3gpp_measurementTypes = 2071082739
    dn3gpp_measurementTypes_ = "measurementTypes"
    dn3gpp_vnfdId = 1550391235
    dn3gpp_vnfdId_ = "vnfdId"
    dn3gpp_autoScalable = 141263935
    dn3gpp_autoScalable_ = "autoScalable"
    dn3gpp_idx = 518466655
    dn3gpp_idx_ = "idx"
    dn3gpp_REQUEST_RESPONSE = 0
    dn3gpp_REQUEST_RESPONSE_ = "REQUEST_RESPONSE"
    dn3gpp_siteLatitude = 259835897
    dn3gpp_siteLatitude_ = "siteLatitude"
