#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/_3gpp-common-subscription-control.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module _3gpp-common-subscription-control.yang


class ns(object):
    hash = 750491761

    id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-common-subscription-control"

    uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-common-subscription-control"

    prefix = "subscr3gpp"

    subscr3gpp_BASE_NTH_LEVEL = 2
    subscr3gpp_BASE_NTH_LEVEL_ = "BASE_NTH_LEVEL"
    subscr3gpp_attributes = 564855297
    subscr3gpp_attributes_ = "attributes"
    subscr3gpp_BASE_ALL = 1
    subscr3gpp_BASE_ALL_ = "BASE_ALL"
    subscr3gpp_id = 1279252765
    subscr3gpp_id_ = "id"
    subscr3gpp_notificationFilter = 1434578593
    subscr3gpp_notificationFilter_ = "notificationFilter"
    subscr3gpp_HeartbeatControl = 737546595
    subscr3gpp_HeartbeatControl_ = "HeartbeatControl"
    subscr3gpp_scope = 2046414572
    subscr3gpp_scope_ = "scope"
    subscr3gpp_scopeLevel = 42405351
    subscr3gpp_scopeLevel_ = "scopeLevel"
    subscr3gpp_BASE_SUBTREE = 3
    subscr3gpp_BASE_SUBTREE_ = "BASE_SUBTREE"
    subscr3gpp_BASE_ONLY = 0
    subscr3gpp_BASE_ONLY_ = "BASE_ONLY"
    subscr3gpp_heartbeatNtfPeriod = 1130106213
    subscr3gpp_heartbeatNtfPeriod_ = "heartbeatNtfPeriod"
    subscr3gpp_NtfSubscriptionControl = 1034717798
    subscr3gpp_NtfSubscriptionControl_ = "NtfSubscriptionControl"
    subscr3gpp_notificationRecipientAddress = 718226445
    subscr3gpp_notificationRecipientAddress_ = "notificationRecipientAddress"
    subscr3gpp_scopeType = 1277372679
    subscr3gpp_scopeType_ = "scopeType"
    subscr3gpp_notificationTypes = 891302328
    subscr3gpp_notificationTypes_ = "notificationTypes"
