#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/_3gpp-nr-nrm-externalservinggwfunction.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module _3gpp-nr-nrm-externalservinggwfunction.yang


class ns(object):
    hash = 1420568397

    id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-nr-nrm-externalservinggwfunction"

    uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-nr-nrm-externalservinggwfunction"

    prefix = "extservgw3gpp"

    extservgw3gpp_environmentType = 252397055
    extservgw3gpp_environmentType_ = "environmentType"
    extservgw3gpp_operationalState = 880872221
    extservgw3gpp_operationalState_ = "operationalState"
    extservgw3gpp_allowedNFTypes = 189804508
    extservgw3gpp_allowedNFTypes_ = "allowedNFTypes"
    extservgw3gpp_attributes = 564855297
    extservgw3gpp_attributes_ = "attributes"
    extservgw3gpp_port = 10387472
    extservgw3gpp_port_ = "port"
    extservgw3gpp_peeParametersList = 1298381397
    extservgw3gpp_peeParametersList_ = "peeParametersList"
    extservgw3gpp_equipmentType = 1795612006
    extservgw3gpp_equipmentType_ = "equipmentType"
    extservgw3gpp_usageState = 1489640591
    extservgw3gpp_usageState_ = "usageState"
    extservgw3gpp_name = 1998270519
    extservgw3gpp_name_ = "name"
    extservgw3gpp_operations = 1455304325
    extservgw3gpp_operations_ = "operations"
    extservgw3gpp_vnfInstanceId = 1359245082
    extservgw3gpp_vnfInstanceId_ = "vnfInstanceId"
    extservgw3gpp_siteDescription = 1034504377
    extservgw3gpp_siteDescription_ = "siteDescription"
    extservgw3gpp_siteLongitude = 18287823
    extservgw3gpp_siteLongitude_ = "siteLongitude"
    extservgw3gpp_gPs = 1761160070
    extservgw3gpp_gPs_ = "gPs"
    extservgw3gpp_registrationState = 421695678
    extservgw3gpp_registrationState_ = "registrationState"
    extservgw3gpp_measurementsList = 349662536
    extservgw3gpp_measurementsList_ = "measurementsList"
    extservgw3gpp_ManagedNFService = 736688724
    extservgw3gpp_ManagedNFService_ = "ManagedNFService"
    extservgw3gpp_operationSemantics = 844181866
    extservgw3gpp_operationSemantics_ = "operationSemantics"
    extservgw3gpp_id = 1279252765
    extservgw3gpp_id_ = "id"
    extservgw3gpp_siteIdentification = 726111887
    extservgw3gpp_siteIdentification_ = "siteIdentification"
    extservgw3gpp_administrativeState = 499558712
    extservgw3gpp_administrativeState_ = "administrativeState"
    extservgw3gpp_host = 1711485895
    extservgw3gpp_host_ = "host"
    extservgw3gpp_DEREGISTERED = 1
    extservgw3gpp_DEREGISTERED_ = "DEREGISTERED"
    extservgw3gpp_nFServiceType = 617372187
    extservgw3gpp_nFServiceType_ = "nFServiceType"
    extservgw3gpp_powerInterface = 663222618
    extservgw3gpp_powerInterface_ = "powerInterface"
    extservgw3gpp_userLabel = 1367743805
    extservgw3gpp_userLabel_ = "userLabel"
    extservgw3gpp_REGISTERED = 0
    extservgw3gpp_REGISTERED_ = "REGISTERED"
    extservgw3gpp_flavourId = 1273445849
    extservgw3gpp_flavourId_ = "flavourId"
    extservgw3gpp_sAP = 1421749432
    extservgw3gpp_sAP_ = "sAP"
    extservgw3gpp_priorityLabel = 1509091865
    extservgw3gpp_priorityLabel_ = "priorityLabel"
    extservgw3gpp_vnfParametersList = 849315116
    extservgw3gpp_vnfParametersList_ = "vnfParametersList"
    extservgw3gpp_ExternalServingGWFunction = 1752191481
    extservgw3gpp_ExternalServingGWFunction_ = "ExternalServingGWFunction"
    extservgw3gpp_SUBSCRIBE_NOTIFY = 1
    extservgw3gpp_SUBSCRIBE_NOTIFY_ = "SUBSCRIBE_NOTIFY"
    extservgw3gpp_measurementTypes = 2071082739
    extservgw3gpp_measurementTypes_ = "measurementTypes"
    extservgw3gpp_vnfdId = 1550391235
    extservgw3gpp_vnfdId_ = "vnfdId"
    extservgw3gpp_autoScalable = 141263935
    extservgw3gpp_autoScalable_ = "autoScalable"
    extservgw3gpp_idx = 518466655
    extservgw3gpp_idx_ = "idx"
    extservgw3gpp_REQUEST_RESPONSE = 0
    extservgw3gpp_REQUEST_RESPONSE_ = "REQUEST_RESPONSE"
    extservgw3gpp_siteLatitude = 259835897
    extservgw3gpp_siteLatitude_ = "siteLatitude"
