#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/_3gpp-nr-nrm-nrnetwork.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module _3gpp-nr-nrm-nrnetwork.yang


class ns(object):
    hash = 81304938

    id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-nr-nrm-nrnetwork"

    uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-nr-nrm-nrnetwork"

    prefix = "nrnet3gpp"

    nrnet3gpp_userDefinedNetworkType = 32336612
    nrnet3gpp_userDefinedNetworkType_ = "userDefinedNetworkType"
    nrnet3gpp_attributes = 564855297
    nrnet3gpp_attributes_ = "attributes"
    nrnet3gpp_NRNetwork = 1628014008
    nrnet3gpp_NRNetwork_ = "NRNetwork"
    nrnet3gpp_gPs = 1761160070
    nrnet3gpp_gPs_ = "gPs"
    nrnet3gpp_measurementsList = 349662536
    nrnet3gpp_measurementsList_ = "measurementsList"
    nrnet3gpp_id = 1279252765
    nrnet3gpp_id_ = "id"
    nrnet3gpp_userLabel = 1367743805
    nrnet3gpp_userLabel_ = "userLabel"
    nrnet3gpp_priorityLabel = 1509091865
    nrnet3gpp_priorityLabel_ = "priorityLabel"
    nrnet3gpp_setOfMcc = 1592970403
    nrnet3gpp_setOfMcc_ = "setOfMcc"
    nrnet3gpp_measurementTypes = 2071082739
    nrnet3gpp_measurementTypes_ = "measurementTypes"
    nrnet3gpp_dnPrefix = 805591200
    nrnet3gpp_dnPrefix_ = "dnPrefix"
    nrnet3gpp_idx = 518466655
    nrnet3gpp_idx_ = "idx"
