#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/_3gpp-common-yang-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module _3gpp-common-yang-types.yang


class ns(object):
    hash = 1061106629

    id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-common-yang-types"

    uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-common-yang-types"

    prefix = "types3gpp"

    types3gpp_AMF = 2
    types3gpp_AMF_ = "AMF"
    types3gpp_OFF_DUTY = 4
    types3gpp_OFF_DUTY_ = "OFF_DUTY"
    types3gpp_UL = 1
    types3gpp_UL_ = "UL"
    types3gpp_PWS = 2
    types3gpp_PWS_ = "PWS"
    types3gpp_N2_INFORMATION = 1
    types3gpp_N2_INFORMATION_ = "N2_INFORMATION"
    types3gpp_CHF = 19
    types3gpp_CHF_ = "CHF"
    types3gpp_SHUTTINGDOWN = 2
    types3gpp_SHUTTINGDOWN_ = "SHUTTINGDOWN"
    types3gpp_LOG_FULL = 8
    types3gpp_LOG_FULL_ = "LOG_FULL"
    types3gpp_BUSY = 2
    types3gpp_BUSY_ = "BUSY"
    types3gpp_SEPP = 13
    types3gpp_SEPP_ = "SEPP"
    types3gpp_N1_MESSAGES = 0
    types3gpp_N1_MESSAGES_ = "N1_MESSAGES"
    types3gpp_EXPOSURE = 2
    types3gpp_EXPOSURE_ = "EXPOSURE"
    types3gpp_BSF = 18
    types3gpp_BSF_ = "BSF"
    types3gpp_UDSF = 17
    types3gpp_UDSF_ = "UDSF"
    types3gpp_SUBSCRIPTION = 0
    types3gpp_SUBSCRIPTION_ = "SUBSCRIPTION"
    types3gpp_SMF = 3
    types3gpp_SMF_ = "SMF"
    types3gpp_LMF = 10
    types3gpp_LMF_ = "LMF"
    types3gpp_PWS_RF = 4
    types3gpp_PWS_RF_ = "PWS_RF"
    types3gpp_FULLY_MOBILITY = 3
    types3gpp_FULLY_MOBILITY_ = "FULLY_MOBILITY"
    types3gpp_5GMM = 0
    types3gpp_5GMM_ = "5GMM"
    types3gpp_OFF_LINE = 3
    types3gpp_OFF_LINE_ = "OFF_LINE"
    types3gpp_RESTRICTED_MOBILITY = 2
    types3gpp_RESTRICTED_MOBILITY_ = "RESTRICTED_MOBILITY"
    types3gpp_DEPENDENCY = 5
    types3gpp_DEPENDENCY_ = "DEPENDENCY"
    types3gpp_NOMADIC = 1
    types3gpp_NOMADIC_ = "NOMADIC"
    types3gpp_NEF = 5
    types3gpp_NEF_ = "NEF"
    types3gpp_NOT_INSTALLED = 7
    types3gpp_NOT_INSTALLED_ = "NOT_INSTALLED"
    types3gpp_STATIONARY = 0
    types3gpp_STATIONARY_ = "STATIONARY"
    types3gpp_UDR = 9
    types3gpp_UDR_ = "UDR"
    types3gpp_AF = 16
    types3gpp_AF_ = "AF"
    types3gpp_LPP = 2
    types3gpp_LPP_ = "LPP"
    types3gpp_DL_AND_UL = 2
    types3gpp_DL_AND_UL_ = "DL_AND_UL"
    types3gpp_UDM = 1
    types3gpp_UDM_ = "UDM"
    types3gpp_LOCATION_NOTIFICATION = 2
    types3gpp_LOCATION_NOTIFICATION_ = "LOCATION_NOTIFICATION"
    types3gpp_DISABLED = 0
    types3gpp_DISABLED_ = "DISABLED"
    types3gpp_NRF = 0
    types3gpp_NRF_ = "NRF"
    types3gpp_POWER_OFF = 2
    types3gpp_POWER_OFF_ = "POWER_OFF"
    types3gpp_DL = 0
    types3gpp_DL_ = "DL"
    types3gpp_5G_EIR = 12
    types3gpp_5G_EIR_ = "5G_EIR"
    types3gpp_SMSF = 7
    types3gpp_SMSF_ = "SMSF"
    types3gpp_NSSF = 8
    types3gpp_NSSF_ = "NSSF"
    types3gpp_INACTIVE = 1
    types3gpp_INACTIVE_ = "INACTIVE"
    types3gpp_FAILED = 1
    types3gpp_FAILED_ = "FAILED"
    types3gpp_UPF = 14
    types3gpp_UPF_ = "UPF"
    types3gpp_DEGRADED = 6
    types3gpp_DEGRADED_ = "DEGRADED"
    types3gpp_LOCKED = 0
    types3gpp_LOCKED_ = "LOCKED"
    types3gpp_N3IWF = 15
    types3gpp_N3IWF_ = "N3IWF"
    types3gpp_AUSF = 4
    types3gpp_AUSF_ = "AUSF"
    types3gpp_NOT_SHARED = 1
    types3gpp_NOT_SHARED_ = "NOT_SHARED"
    types3gpp_SMS = 3
    types3gpp_SMS_ = "SMS"
    types3gpp_ENABLED = 1
    types3gpp_ENABLED_ = "ENABLED"
    types3gpp_IDLE = 0
    types3gpp_IDLE_ = "IDLE"
    types3gpp_IN_TEST = 0
    types3gpp_IN_TEST_ = "IN_TEST"
    types3gpp_GMLC = 11
    types3gpp_GMLC_ = "GMLC"
    types3gpp_APPLICATION = 3
    types3gpp_APPLICATION_ = "APPLICATION"
    types3gpp_PCF = 6
    types3gpp_PCF_ = "PCF"
    types3gpp_SHARED = 0
    types3gpp_SHARED_ = "SHARED"
    types3gpp_UNLOCKED = 1
    types3gpp_UNLOCKED_ = "UNLOCKED"
    types3gpp_POLICY = 1
    types3gpp_POLICY_ = "POLICY"
    types3gpp_PWS_BCAL = 3
    types3gpp_PWS_BCAL_ = "PWS_BCAL"
    types3gpp_NRPPA = 1
    types3gpp_NRPPA_ = "NRPPA"
