#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/_3gpp-5gc-nrm-ep.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module _3gpp-5gc-nrm-ep.yang


class ns(object):
    hash = 1662622704

    id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:tsg:sa5:nrm:_3gpp-5gc-nrm-ep"

    uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:tsg:sa5:nrm:_3gpp-5gc-nrm-ep"

    prefix = "cep3gpp"

    cep3gpp_farEndEntity = 792998662
    cep3gpp_farEndEntity_ = "farEndEntity"
    cep3gpp_EP_N3 = 1459032139
    cep3gpp_EP_N3_ = "EP_N3"
    cep3gpp_attributes = 564855297
    cep3gpp_attributes_ = "attributes"
    cep3gpp_EP_N27 = 1185420112
    cep3gpp_EP_N27_ = "EP_N27"
    cep3gpp_EP_N22 = 722071580
    cep3gpp_EP_N22_ = "EP_N22"
    cep3gpp_EP_N26 = 242822374
    cep3gpp_EP_N26_ = "EP_N26"
    cep3gpp_EP_Rx = 70291351
    cep3gpp_EP_Rx_ = "EP_Rx"
    cep3gpp_remoteAddress = 1861109068
    cep3gpp_remoteAddress_ = "remoteAddress"
    cep3gpp_EP_N4 = 118977653
    cep3gpp_EP_N4_ = "EP_N4"
    cep3gpp_n32cParas = 1648225201
    cep3gpp_n32cParas_ = "n32cParas"
    cep3gpp_EP_N14 = 77196683
    cep3gpp_EP_N14_ = "EP_N14"
    cep3gpp_EP_S5U = 1815890953
    cep3gpp_EP_S5U_ = "EP_S5U"
    cep3gpp_remoteSeppId = 1307327399
    cep3gpp_remoteSeppId_ = "remoteSeppId"
    cep3gpp_vlanId = 694657269
    cep3gpp_vlanId_ = "vlanId"
    cep3gpp_EP_N8 = 1963057731
    cep3gpp_EP_N8_ = "EP_N8"
    cep3gpp_EP_MAP_SMSC = 804233039
    cep3gpp_EP_MAP_SMSC_ = "EP_MAP_SMSC"
    cep3gpp_localAddress = 105812027
    cep3gpp_localAddress_ = "localAddress"
    cep3gpp_EP_N16 = 851485012
    cep3gpp_EP_N16_ = "EP_N16"
    cep3gpp_EP_N11 = 1988462150
    cep3gpp_EP_N11_ = "EP_N11"
    cep3gpp_mcc = 1243031439
    cep3gpp_mcc_ = "mcc"
    cep3gpp_gPs = 1761160070
    cep3gpp_gPs_ = "gPs"
    cep3gpp_measurementsList = 349662536
    cep3gpp_measurementsList_ = "measurementsList"
    cep3gpp_EP_N20 = 1196419386
    cep3gpp_EP_N20_ = "EP_N20"
    cep3gpp_EP_N6 = 1148698924
    cep3gpp_EP_N6_ = "EP_N6"
    cep3gpp_remoteSeppAddress = 2095605240
    cep3gpp_remoteSeppAddress_ = "remoteSeppAddress"
    cep3gpp_id = 1279252765
    cep3gpp_id_ = "id"
    cep3gpp_EP_N21 = 1373282515
    cep3gpp_EP_N21_ = "EP_N21"
    cep3gpp_EP_N5 = 1006787923
    cep3gpp_EP_N5_ = "EP_N5"
    cep3gpp_remotePlmnId = 283091462
    cep3gpp_remotePlmnId_ = "remotePlmnId"
    cep3gpp_userLabel = 1367743805
    cep3gpp_userLabel_ = "userLabel"
    cep3gpp_EP_N2 = 1686195247
    cep3gpp_EP_N2_ = "EP_N2"
    cep3gpp_ipAddress = 1807541132
    cep3gpp_ipAddress_ = "ipAddress"
    cep3gpp_EP_N32 = 1672642508
    cep3gpp_EP_N32_ = "EP_N32"
    cep3gpp_n32fPolicy = 827264723
    cep3gpp_n32fPolicy_ = "n32fPolicy"
    cep3gpp_EP_S5C = 1867696519
    cep3gpp_EP_S5C_ = "EP_S5C"
    cep3gpp_mnc = 351025106
    cep3gpp_mnc_ = "mnc"
    cep3gpp_EP_N7 = 132587297
    cep3gpp_EP_N7_ = "EP_N7"
    cep3gpp_EP_N12 = 1669225430
    cep3gpp_EP_N12_ = "EP_N12"
    cep3gpp_EP_N31 = 1468912686
    cep3gpp_EP_N31_ = "EP_N31"
    cep3gpp_measurementTypes = 2071082739
    cep3gpp_measurementTypes_ = "measurementTypes"
    cep3gpp_EP_N9 = 1944323748
    cep3gpp_EP_N9_ = "EP_N9"
    cep3gpp_EP_EP_N6 = 2011141846
    cep3gpp_EP_EP_N6_ = "EP_EP_N6"
    cep3gpp_withIPX = 739653264
    cep3gpp_withIPX_ = "withIPX"
    cep3gpp_EP_N13 = 1312027881
    cep3gpp_EP_N13_ = "EP_N13"
    cep3gpp_EP_NLG = 1024568823
    cep3gpp_EP_NLG_ = "EP_NLG"
    cep3gpp_EP_N17 = 270267329
    cep3gpp_EP_N17_ = "EP_N17"
    cep3gpp_idx = 518466655
    cep3gpp_idx_ = "idx"
    cep3gpp_EP_NLS = 1564052394
    cep3gpp_EP_NLS_ = "EP_NLS"
    cep3gpp_EP_N10 = 1710920416
    cep3gpp_EP_N10_ = "EP_N10"
    cep3gpp_EP_N15 = 1236488421
    cep3gpp_EP_N15_ = "EP_N15"
