/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/_3gpp-common-measurements.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.fgc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module _3gpp-common-measurements.yang */
public class _3gppCommonMeasurements extends ConfNamespace {
    public static final int hash = 526045340;
    public int hash() {
        return _3gppCommonMeasurements.hash;
    }

    public static final String id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-common-measurements";
    public String id() {
        return _3gppCommonMeasurements.id;
    }

    public static final String uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-common-measurements";
    public String uri() {
        return _3gppCommonMeasurements.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(_3gppCommonMeasurements.uri);
    }

    public static final String prefix = "meas3gpp";
    public String prefix() {
        return _3gppCommonMeasurements.prefix;
    }

    public _3gppCommonMeasurements() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
