/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/_3gpp-nr-nrm-ep.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.fgc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module _3gpp-nr-nrm-ep.yang */
public class _3gppNrNrmEp extends ConfNamespace {
    public static final int hash = 470572806;
    public int hash() {
        return _3gppNrNrmEp.hash;
    }

    public static final String id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-nr-nrm-ep";
    public String id() {
        return _3gppNrNrmEp.id;
    }

    public static final String uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-nr-nrm-ep";
    public String uri() {
        return _3gppNrNrmEp.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(_3gppNrNrmEp.uri);
    }

    public static final String prefix = "ep3gpp";
    public String prefix() {
        return _3gppNrNrmEp.prefix;
    }

    public _3gppNrNrmEp() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _farEndEntity = 792998662;
    public static final String _farEndEntity_ = "farEndEntity";
    public static final int    _attributes = 564855297;
    public static final String _attributes_ = "attributes";
    public static final int    _remoteAddress = 1861109068;
    public static final String _remoteAddress_ = "remoteAddress";
    public static final int    _vlanId = 694657269;
    public static final String _vlanId_ = "vlanId";
    public static final int    _EP_NgU = 1712374833;
    public static final String _EP_NgU_ = "EP_NgU";
    public static final int    _EP_S1U = 367189507;
    public static final String _EP_S1U_ = "EP_S1U";
    public static final int    _localAddress = 105812027;
    public static final String _localAddress_ = "localAddress";
    public static final int    _EP_X2C = 181092064;
    public static final String _EP_X2C_ = "EP_X2C";
    public static final int    _gPs = 1761160070;
    public static final String _gPs_ = "gPs";
    public static final int    _measurementsList = 349662536;
    public static final String _measurementsList_ = "measurementsList";
    public static final int    _EP_NgC = 1738378856;
    public static final String _EP_NgC_ = "EP_NgC";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _EP_E1 = 1304526615;
    public static final String _EP_E1_ = "EP_E1";
    public static final int    _EP_X2U = 1312284670;
    public static final String _EP_X2U_ = "EP_X2U";
    public static final int    _userLabel = 1367743805;
    public static final String _userLabel_ = "userLabel";
    public static final int    _ipAddress = 1807541132;
    public static final String _ipAddress_ = "ipAddress";
    public static final int    _EP_F1U = 626479091;
    public static final String _EP_F1U_ = "EP_F1U";
    public static final int    _EP_XnC = 1667713020;
    public static final String _EP_XnC_ = "EP_XnC";
    public static final int    _EP_F1C = 42715440;
    public static final String _EP_F1C_ = "EP_F1C";
    public static final int    _EP_XnU = 1437274725;
    public static final String _EP_XnU_ = "EP_XnU";
    public static final int    _measurementTypes = 2071082739;
    public static final String _measurementTypes_ = "measurementTypes";
    public static final int    _idx = 518466655;
    public static final String _idx_ = "idx";
}
