/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/_3gpp-common-managed-function.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.fgc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module _3gpp-common-managed-function.yang */
public class _3gppCommonManagedFunction extends ConfNamespace {
    public static final int hash = 569753136;
    public int hash() {
        return _3gppCommonManagedFunction.hash;
    }

    public static final String id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-common-managed-function";
    public String id() {
        return _3gppCommonManagedFunction.id;
    }

    public static final String uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-common-managed-function";
    public String uri() {
        return _3gppCommonManagedFunction.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(_3gppCommonManagedFunction.uri);
    }

    public static final String prefix = "mf3gpp";
    public String prefix() {
        return _3gppCommonManagedFunction.prefix;
    }

    public _3gppCommonManagedFunction() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
