/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/_3gpp-common-subscription-control.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.fgc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module _3gpp-common-subscription-control.yang */
public class _3gppCommonSubscriptionControl extends ConfNamespace {
    public static final int hash = 750491761;
    public int hash() {
        return _3gppCommonSubscriptionControl.hash;
    }

    public static final String id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-common-subscription-control";
    public String id() {
        return _3gppCommonSubscriptionControl.id;
    }

    public static final String uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-common-subscription-control";
    public String uri() {
        return _3gppCommonSubscriptionControl.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(_3gppCommonSubscriptionControl.uri);
    }

    public static final String prefix = "subscr3gpp";
    public String prefix() {
        return _3gppCommonSubscriptionControl.prefix;
    }

    public _3gppCommonSubscriptionControl() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _attributes = 564855297;
    public static final String _attributes_ = "attributes";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _notificationFilter = 1434578593;
    public static final String _notificationFilter_ = "notificationFilter";
    public static final int    _HeartbeatControl = 737546595;
    public static final String _HeartbeatControl_ = "HeartbeatControl";
    public static final int    _scope = 2046414572;
    public static final String _scope_ = "scope";
    public static final int    _scopeLevel = 42405351;
    public static final String _scopeLevel_ = "scopeLevel";
    public static final int    _heartbeatNtfPeriod = 1130106213;
    public static final String _heartbeatNtfPeriod_ = "heartbeatNtfPeriod";
    public static final int    _NtfSubscriptionControl = 1034717798;
    public static final String _NtfSubscriptionControl_ = "NtfSubscriptionControl";
    public static final int    _notificationRecipientAddress = 718226445;
    public static final String _notificationRecipientAddress_ = "notificationRecipientAddress";
    public static final int    _scopeType = 1277372679;
    public static final String _scopeType_ = "scopeType";
    public static final int    _notificationTypes = 891302328;
    public static final String _notificationTypes_ = "notificationTypes";
}
