/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/_3gpp-nr-nrm-eutranetwork.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.fgc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module _3gpp-nr-nrm-eutranetwork.yang */
public class _3gppNrNrmEutranetwork extends ConfNamespace {
    public static final int hash = 1505106351;
    public int hash() {
        return _3gppNrNrmEutranetwork.hash;
    }

    public static final String id = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-nr-nrm-eutranetwork";
    public String id() {
        return _3gppNrNrmEutranetwork.id;
    }

    public static final String uri = "_fgc-nc-1.0:fgc-nc-1.0#urn:3gpp:sa5:_3gpp-nr-nrm-eutranetwork";
    public String uri() {
        return _3gppNrNrmEutranetwork.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(_3gppNrNrmEutranetwork.uri);
    }

    public static final String prefix = "eutranet3gpp";
    public String prefix() {
        return _3gppNrNrmEutranetwork.prefix;
    }

    public _3gppNrNrmEutranetwork() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _userDefinedNetworkType = 32336612;
    public static final String _userDefinedNetworkType_ = "userDefinedNetworkType";
    public static final int    _attributes = 564855297;
    public static final String _attributes_ = "attributes";
    public static final int    _parents = 1912968603;
    public static final String _parents_ = "parents";
    public static final int    _gPs = 1761160070;
    public static final String _gPs_ = "gPs";
    public static final int    _measurementsList = 349662536;
    public static final String _measurementsList_ = "measurementsList";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _EUtraNetwork = 1979635035;
    public static final String _EUtraNetwork_ = "EUtraNetwork";
    public static final int    _userLabel = 1367743805;
    public static final String _userLabel_ = "userLabel";
    public static final int    _priorityLabel = 1509091865;
    public static final String _priorityLabel_ = "priorityLabel";
    public static final int    _setOfMcc = 1592970403;
    public static final String _setOfMcc_ = "setOfMcc";
    public static final int    _measurementTypes = 2071082739;
    public static final String _measurementTypes_ = "measurementTypes";
    public static final int    _containedChildren = 7811900;
    public static final String _containedChildren_ = "containedChildren";
    public static final int    _dnPrefix = 805591200;
    public static final String _dnPrefix_ = "dnPrefix";
    public static final int    _idx = 518466655;
    public static final String _idx_ = "idx";
}
